# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::_init
# Entry address: 0x101000
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_ne, c_return_bits, c_store

def _init(param_0):
    abi_context = c_abi_context('function_entry:1052672')
    v_212 = 0
    if c_load(MEM, 0x103fe8, 64) == 0:
        pass
    else:
        v_212 = c_bits(c_abi_call(abi_context, PTR___gmon_start___00103fe8, (), plan_id='call_site:1052692:(ram, 0x101014, 23, 2):2'), 32)
    return c_abi_return(abi_context, v_212, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1052672')
