# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::_init
# Entry address: 0x101000
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_ne, c_return_bits, c_store

def _init(param_0):
    abi_context = c_abi_context('function_entry:1052672')
    v_212 = 0
    if c_load(MEM, 0x103fe8, 64) == 0:
        pass
    else:
        v_212 = c_bits(c_abi_call(abi_context, PTR___gmon_start___00103fe8, (), plan_id='call_site:1052692:(ram, 0x101014, 23, 2):2'), 32)
    return c_abi_return(abi_context, v_212, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1052672')
