# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::main
# Entry address: 0x1011e4
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_load, c_ne, c_ptrsub, c_return_bits, c_store

def main():
    abi_context = c_abi_context('function_entry:1053156')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    local_10 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    local_18 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x18, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x18, 64), 64))[1])(0x78563412efbeadde)
    v_96 = c_ptrsub(abi_stack_pointer, -0x18, 64)
    v_397 = c_bits(c_abi_call(abi_context, 'process_payload_block', (0x10203040, v_96, 8), plan_id='call_site:1053160:(ram, 0x101225, 48, 8):8'), 32)
    v_168 = c_load(MEM, c_add(in_FS_OFFSET, 0x28, 64), 64)
    if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 64) == v_168:
        return c_return_bits(v_397, 32)
    else:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1053247:(ram, 0x10123f, 75, 2):2')
