# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_route
# Entry address: 0x101d89
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_eq, c_load, c_ptradd, c_return_bits, c_store, c_sub, c_ult, c_zext

def command_route(param_0, param_1):
    abi_context = c_abi_context('function_entry:1056137')
    v_60 = c_load(MEM, param_0, 32)
    if c_eq(v_60, 1, 32):
        v_146 = c_load(MEM, c_add(param_1, 0x10, 64), 32)
        if not c_eq(v_146, 0, 32):
            v_215 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
            if not c_ult(c_sub(v_215, 1, 32), 4, 32):
                c_abi_call(abi_context, 'record_fault', (param_0, 0x103618), plan_id='call_site:1056331:(ram, 0x101e5c, 169, 1):1')
            else:
                v_296 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                v_311 = c_ptradd(param_0, 3, 4, 64)
                c_store(MEM, v_311, v_296, 32)
                c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1056245:(ram, 0x101e0a, 129, 5):5')
                v_345 = c_ptradd(param_0, 3, 4, 64)
                v_348 = c_load(MEM, v_345, 32)
                c_abi_call(abi_context, 'printf', (0x1035f3, c_zext(v_348, 32, 64)), plan_id='call_site:1056245:(ram, 0x101e27, 144, 11):11')
                v_381 = c_ptradd(param_0, 4, 4, 64)
                v_384 = c_load(MEM, v_381, 32)
                c_abi_call(abi_context, 'printf', (0x103579, c_zext(v_384, 32, 64)), plan_id='call_site:1056245:(ram, 0x101e44, 159, 17):17')
        else:
            c_abi_call(abi_context, 'record_fault', (param_0, 0x1035c8), plan_id='call_site:1056206:(ram, 0x101ddf, 78, 1):1')
    else:
        c_abi_call(abi_context, 'record_fault', (param_0, 0x103590), plan_id='call_site:1056168:(ram, 0x101db9, 44, 1):1')
    return c_return_bits(0, 64)
