# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::is_space_char
# Entry address: 0x1014c4
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_eq, c_return_bits

def is_space_char(param_0):
    if c_eq(param_0, 32, 8):
        v_266 = 1
    else:
        if c_eq(param_0, 9, 8):
            v_266 = 1
        else:
            if c_eq(param_0, 13, 8):
                v_266 = 1
            else:
                if not c_eq(param_0, 10, 8):
                    v_266 = 0
                else:
                    v_266 = 1
    return c_return_bits(v_266, 64)
