# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::mode_name
# Entry address: 0x1011c9
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_return_bits

def mode_name(param_0):
    _pal_dispatch_1011cd = param_0
    if _pal_dispatch_1011cd == 0:
        v_234 = 0x103008
    elif _pal_dispatch_1011cd == 1:
        v_234 = 0x103010
    elif _pal_dispatch_1011cd == 2:
        v_234 = 0x10301b
    elif _pal_dispatch_1011cd == 3:
        v_234 = 0x103021
    elif _pal_dispatch_1011cd == 4:
        v_234 = 0x103028
    else:
        v_234 = 0x10302f
    return c_return_bits(v_234, 64)
