# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::compute_checksum
# Entry address: 0x101985
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_bits, c_load, c_lshr, c_mul, c_ptradd, c_return_bits, c_slt, c_xor

def compute_checksum(param_0):
    abi_context = c_abi_context('function_entry:1055109')
    v_60 = c_ptradd(param_0, 1, 4, 64)
    v_63 = c_load(MEM, v_60, 32)
    v_258 = c_ptradd(param_0, 2, 4, 64)
    v_261 = c_load(MEM, v_258, 32)
    v_456 = c_ptradd(param_0, 3, 4, 64)
    v_459 = c_load(MEM, v_456, 32)
    v_654 = c_ptradd(param_0, 5, 4, 64)
    v_657 = c_load(MEM, v_654, 32)
    v_736 = c_ptradd(param_0, 7, 4, 64)
    v_739 = c_load(MEM, v_736, 32)
    v_934 = c_load(MEM, param_0, 32)
    local_14 = c_xor(c_xor(c_xor(c_xor(c_xor(c_xor(c_mul(v_63, 0x21, 32), 0x13579bdf, 32), c_mul(v_261, 0x11, 32), 32), c_mul(v_459, 0x101, 32), 32), c_mul(v_657, 0x1003, 32), 32), c_mul(v_739, 0x1fff, 32), 32), c_mul(v_934, 0x10001, 32), 32)
    v_1129 = c_ptradd(param_0, 1, 4, 64)
    v_1132 = c_load(MEM, v_1129, 32)
    v_1147 = c_ptradd(param_0, 2, 4, 64)
    v_1150 = c_load(MEM, v_1147, 32)
    v_1176 = c_ptradd(param_0, 3, 4, 64)
    v_1179 = c_load(MEM, v_1176, 32)
    v_1360 = c_ptradd(param_0, 6, 4, 64)
    v_1363 = c_load(MEM, v_1360, 32)
    local_10 = c_add(c_mul(v_1363, 0xb, 32), c_add(c_add(v_1132, v_1150, 32), c_mul(v_1179, 7, 32), 32), 32)
    local_c = 0
    while c_slt(local_c, 4, 32):
        v_3352 = c_bits(c_abi_call(abi_context, 'rotate_left_5', (local_14,), plan_id='call_site:1055297:(ram, 0x101a46, 631, 0):0'), 32)
        local_14 = c_xor(v_3352, c_add(local_10, c_mul(local_c, 0x1021, 32), 32), 32)
        local_10 = c_xor(c_lshr(local_14, 3, 32), c_mul(local_10, 0x1d, 32), 32)
        local_c = c_add(local_c, 1, 32)
        v_3352 = c_bits(c_abi_call(abi_context, 'rotate_left_5', (local_14,), plan_id='call_site:1055297:(ram, 0x101a46, 631, 0):0'), 32)
        local_14 = c_xor(v_3352, c_add(local_10, c_mul(local_c, 0x1021, 32), 32), 32)
        local_10 = c_xor(c_lshr(local_14, 3, 32), c_mul(local_10, 0x1d, 32), 32)
        local_c = c_add(local_c, 1, 32)
    return c_return_bits(c_xor(local_14, 0xa5a55a5a, 32), 32)
