# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_cool
# Entry address: 0x1021d0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_eq, c_load, c_mul, c_ptradd, c_return_bits, c_sdiv, c_slt, c_store, c_sub, c_zext

def command_cool(param_0):
    abi_context = c_abi_context('function_entry:1057232')
    v_52 = c_load(MEM, param_0, 32)
    if c_eq(v_52, 2, 32):
        v_135 = c_ptradd(param_0, 2, 4, 64)
        v_138 = c_load(MEM, v_135, 32)
        v_161 = c_ptradd(param_0, 3, 4, 64)
        v_164 = c_load(MEM, v_161, 32)
        v_215 = c_ptradd(param_0, 7, 4, 64)
        v_218 = c_load(MEM, v_215, 32)
        v_437 = c_ptradd(param_0, 2, 4, 64)
        v_440 = c_load(MEM, v_437, 32)
        v_499 = c_ptradd(param_0, 2, 4, 64)
        c_store(MEM, v_499, c_sub(v_440, c_add(c_sdiv(v_218, 2, 32), c_mul(c_add(v_164, 6, 32), 4, 32), 32), 32), 32)
        v_515 = c_ptradd(param_0, 2, 4, 64)
        v_518 = c_load(MEM, v_515, 32)
        if not c_slt(v_518, 0, 32):
            pass
        else:
            v_561 = c_ptradd(param_0, 2, 4, 64)
            c_store(MEM, v_561, 0, 32)
        c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1057375:(ram, 0x102266, 219, 0):0')
        c_abi_call(abi_context, 'puts', (0x103929,), plan_id='call_site:1057375:(ram, 0x102275, 224, 2):2')
        v_607 = c_ptradd(param_0, 2, 4, 64)
        v_610 = c_load(MEM, v_607, 32)
        c_abi_call(abi_context, 'printf', (0x103942, c_zext(v_138, 32, 64), c_zext(v_610, 32, 64)), plan_id='call_site:1057375:(ram, 0x102295, 243, 9):9')
    else:
        c_abi_call(abi_context, 'record_fault', (param_0, 0x1038f8), plan_id='call_site:1057259:(ram, 0x1021fc, 41, 1):1')
    return c_return_bits(0, 64)
