# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: <EXTERNAL>::printf
# Entry address: 0x1010c0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def printf(param_0):
    abi_context = c_abi_context('function_entry:1052864')
    abi_overflow_arguments = c_abi_get(abi_context, 'overflow_argument_area', None, None)
    v_15 = c_bits(c_abi_call(abi_context, PTR_printf_00105fc8, (), plan_id='call_site:1052868:(ram, 0x1010c4, 0, 2):2'), 32)
    return c_abi_return(abi_context, v_15, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1052864')
