# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::copy_token
# Entry address: 0x10159d
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_load, c_return_bits, c_sext, c_sle, c_slt, c_store

def copy_token(param_0, param_1, param_2, param_3):
    local_c = param_3
    if not c_sle(param_1, param_3, 32):
        pass
    else:
        local_c = c_add(param_1, 0xffffffff, 32)
    local_10 = 0
    while c_slt(local_10, local_c, 32):
        v_373 = c_load(MEM, c_add(param_2, c_sext(local_10, 32, 64), 64), 8)
        c_store(MEM, c_add(param_0, c_sext(local_10, 32, 64), 64), v_373, 8)
        local_10 = c_add(local_10, 1, 32)
        v_373 = c_load(MEM, c_add(param_2, c_sext(local_10, 32, 64), 64), 8)
        c_store(MEM, c_add(param_0, c_sext(local_10, 32, 64), 64), v_373, 8)
        local_10 = c_add(local_10, 1, 32)
    c_store(MEM, c_add(param_0, c_sext(local_c, 32, 64), 64), 0, 8)
    return c_return_bits(0, 64)
