# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::station_exit_code
# Entry address: 0x1026e7
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_eq, c_load, c_ptradd, c_return_bits

def station_exit_code(param_0):
    v_26 = c_ptradd(param_0, 8, 4, 64)
    v_29 = c_load(MEM, v_26, 32)
    if c_eq(v_29, 0, 32):
        v_90 = c_load(MEM, param_0, 32)
        if not c_eq(v_90, 4, 32):
            v_192 = 2
        else:
            v_192 = 3
    else:
        v_192 = 0
    return c_return_bits(v_192, 64)
