# Generated by PALExecInterface.
# Explicit modeled external boundaries. Unknown externals fail closed.

from __future__ import annotations

import re


class PALUnimplementedShim(RuntimeError):
    pass


class PALProcessExit(SystemExit):
    pass


class PALPrintShims:
    def __init__(self, memory):
        self.memory = memory

    def _string(self, value):
        if isinstance(value, str):
            return value
        try:
            address = int(value)
        except (TypeError, ValueError):
            return str(value)
        try:
            text = self.memory.read_c_string(address)
        except Exception:
            text = ""
        return text if text else "<cstr@0x%x>" % address

    def _format(self, fmt, values):
        fmt = self._string(fmt)
        items = iter(values)
        out = []
        index = 0
        pattern = re.compile(r"%(?:[-+ #0]*)(?:\d+|\*)?(?:\.\d+|\.\*)?(?:hh|h|ll|l|j|z|t|L)?([diuoxXfFeEgGaAcsp%])")
        for match in pattern.finditer(fmt):
            out.append(fmt[index:match.start()])
            kind = match.group(1)
            token = match.group(0)
            if kind == "%":
                out.append("%")
                index = match.end()
                continue
            try:
                value = next(items)
            except StopIteration:
                out.append(token)
                index = match.end()
                continue
            try:
                if kind in "di":
                    rendered = str(int(value))
                elif kind == "u":
                    rendered = str(int(value) & ((1 << 64) - 1))
                elif kind in "xX":
                    rendered = format(int(value) & ((1 << 64) - 1), kind)
                elif kind == "o":
                    rendered = format(int(value) & ((1 << 64) - 1), "o")
                elif kind in "fFeEgGaA":
                    rendered = str(float(value))
                elif kind == "c":
                    rendered = chr(int(value) & 0xff)
                elif kind == "s":
                    rendered = self._string(value)
                elif kind == "p":
                    rendered = "0x%x" % int(value)
                else:
                    rendered = str(value)
            except Exception:
                rendered = str(value)
            out.append(rendered)
            index = match.end()
        out.append(fmt[index:])
        remaining = list(items)
        if remaining:
            out.append(" " + " ".join(str(value) for value in remaining))
        return "".join(out)

    def printf(self, fmt, *values):
        text = self._format(fmt, values)
        print(text, end="")
        return len(text)

    def __printf_chk(self, flag, fmt, *values):
        return self.printf(fmt, *values)

    def fprintf(self, stream, fmt, *values):
        return self.printf(fmt, *values)

    def __fprintf_chk(self, stream, flag, fmt, *values):
        return self.printf(fmt, *values)

    def puts(self, value):
        text = self._string(value)
        print(text)
        return len(text) + 1

    def fputs(self, value, stream=None):
        text = self._string(value)
        print(text, end="")
        return len(text)

    def putchar(self, value):
        char = chr(int(value) & 0xff)
        print(char, end="")
        return int(value) & 0xff

    def fputc(self, value, stream=None):
        return self.putchar(value)

    def exit(self, status=0):
        raise PALProcessExit(int(status))

    def abort(self, *unused):
        raise PALProcessExit(134)

    def stack_chk_fail(self, *unused):
        raise PALProcessExit("PAL __stack_chk_fail trap")

    def unresolved(self, name):
        def trap(*values):
            raise PALUnimplementedShim(
                "PAL external shim %r is not implemented; args=%r" % (name, values)
            )
        trap.__name__ = "pal_unimplemented_%s" % str(name).replace("-", "_")
        return trap

    def mapping(self, names=()):
        table = {
            "printf": self.printf,
            "__printf_chk": self.__printf_chk,
            "fprintf": self.fprintf,
            "__fprintf_chk": self.__fprintf_chk,
            "puts": self.puts,
            "fputs": self.fputs,
            "fputs_unlocked": self.fputs,
            "putchar": self.putchar,
            "fputc": self.fputc,
            "fputc_unlocked": self.fputc,
            "exit": self.exit,
            "_exit": self.exit,
            "abort": self.abort,
            "__stack_chk_fail": self.stack_chk_fail,
        }
        for name in names:
            table.setdefault(str(name), self.unresolved(str(name)))
        return table
