# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::__stack_chk_fail
# Entry address: 0x101050
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def __stack_chk_fail():
    abi_context = c_abi_context('function_entry:1052752')
    c_abi_call(abi_context, PTR___stack_chk_fail_00103fd0, (), plan_id='call_site:1052756:(ram, 0x101054, 0, 2):2')
    return c_return_bits(0, 64)
