# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::process_payload_block
# Entry address: 0x101149
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_and, c_eq, c_load, c_lshr, c_mul, c_or, c_return_bits, c_sext, c_slt, c_ult, c_xor, c_zext

def process_payload_block(param_0, param_1, param_2):
    local_10 = 0
    if c_eq(param_1, 0, 64):
        v_1554 = 0
    else:
        if not c_slt(param_2, 1, 32):
            local_14 = param_0
            local_c = 0
            local_14 = param_0
            while c_slt(local_c, param_2, 32):
                v_416 = c_load(MEM, c_add(param_1, c_sext(local_c, 32, 64), 64), 8)
                v_479 = c_add(c_xor(c_zext(v_416, 8, 32), local_14, 32), 0x1f, 32)
                local_14 = c_or(c_mul(v_479, 8, 32), c_lshr(v_479, 0x1d, 32), 32)
                if not c_eq(c_and(v_416, 1, 8), 0, 8):
                    local_10 = c_xor(local_10, 0x55, 32)
                    local_c = c_add(local_c, 1, 32)
                else:
                    local_10 = c_add(local_10, 1, 32)
                    local_c = c_add(local_c, 1, 32)
            if c_ult(local_10, 11, 32):
                v_1554 = c_add(local_14, local_10, 32)
            else:
                v_1554 = c_xor(local_14, 0xa5a5a5a5, 32)
        else:
            v_1554 = 0
    return c_return_bits(v_1554, 32)
