# Generated by PALExecInterface.

from __future__ import annotations

import argparse
import os

from PAL_project_runtime import PALProcessExit, PALProjectRuntime


def parse_value(text):
    raw = str(text).strip()
    if raw.lower() in {"true", "false"}:
        return raw.lower() == "true"
    if raw.lower() in {"none", "null"}:
        return None
    try:
        return int(raw, 0)
    except ValueError:
        pass
    try:
        return float(raw)
    except ValueError:
        pass
    return raw


def main(argv=None):
    parser = argparse.ArgumentParser(description="Run a published PAL state machine")
    parser.add_argument("--function", "-f", help="name, function id, decimal address, or 0x address")
    parser.add_argument("--arg", action="append", default=[], help="fixed argument; use str:text for a C string")
    parser.add_argument("--vararg", action="append", default=[], help="variadic argument")
    parser.add_argument("--list", action="store_true", help="list published functions")
    parser.add_argument(
        "--trace",
        action="store_true",
        help="write generic internal-call trace to PAL_runtime_trace.jsonl",
    )
    parser.add_argument(
        "--trace-stderr",
        action="store_true",
        help="also mirror runtime trace records to stderr",
    )
    args = parser.parse_args(argv)

    if args.trace or args.trace_stderr:
        os.environ["PAL_EXEC_TRACE"] = "1"
    if args.trace_stderr:
        os.environ["PAL_EXEC_TRACE_STDERR"] = "1"

    runtime = PALProjectRuntime()
    print("PAL EXEC BUILD:", runtime.config.get("build", "unknown"), flush=True)
    if args.list:
        for record in runtime.records:
            print(
                "%s  %-28s  %-12s %s"
                % (
                    record.get("entry_hex") or "-",
                    record.get("name") or "-",
                    record.get("runtime_mode") or "-",
                    "SHIM" if record.get("is_shim_boundary") else "",
                )
            )
        return 0

    values = [parse_value(value) for value in args.arg]
    varargs = [parse_value(value) for value in args.vararg]
    try:
        result = runtime.run(args.function, values, varargs)
    except PALProcessExit as exc:
        print("\nPAL PROCESS EXIT:", exc.code)
        return int(exc.code) if isinstance(exc.code, int) else 1
    print("\nPAL RESULT:", result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
