# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::transform_a
# Entry address: 0x101149
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits, c_shl, c_xor

def transform_a(param_0):
    return c_return_bits(c_xor(c_shl(param_0, 2, 32), 0xaf, 32), 32)
