# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::check_bit
# Entry address: 0x10117e
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_and, c_ashr, c_return_bits

def check_bit(param_0, param_1):
    return c_return_bits(c_and(c_ashr(param_0, c_and(param_1, 0x1f, 8), 32), 1, 32), 32)
