# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::FUN_001084c0
# Entry address: 0x1084c0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_load, c_ne, c_return_bits, c_store

def FUN_001084c0():
    abi_context = c_abi_context('function_entry:1082560')
    v_10 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
    v_693 = c_bits(c_abi_call(abi_context, 'FUN_00104560', (v_10,), plan_id='call_site:1082564:(ram, 0x1084d0, 8, 5):5'), 32)
    if not c_ne(v_693, 0, 32):
        v_184 = c_load(MEM, c_load(MEM, 0x10bff0, 64), 64)
        v_728 = c_bits(c_abi_call(abi_context, 'FUN_00104560', (v_184,), plan_id='call_site:1082648:(ram, 0x108522, 78, 5):5'), 32)
        if not c_eq(v_728, 0, 32):
            c_abi_call(abi_context, '_exit', (c_load(MEM, 0x10c024, 32),), plan_id='call_site:1082670:(ram, 0x108534, 101, 3):3')
        else:
            return c_return_bits(0, 64)
    else:
        v_352 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1090ab, 5), plan_id='call_site:1082585:(ram, 0x1084e7, 33, 4):4'), 64)
        v_306 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1082585:(ram, 0x1084ef, 37, 8):8'), 64)
        v_127 = c_load(MEM, v_306, 32)
        c_abi_call(abi_context, 'error', (0, v_127, 0x109176, v_352), plan_id='call_site:1082585:(ram, 0x108504, 65, 14):14')
        c_abi_call(abi_context, '_exit', (c_load(MEM, 0x10c024, 32),), plan_id='call_site:1082585:(ram, 0x10850f, 70, 18):18')
