# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::FUN_00108560
# Entry address: 0x108560
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_and, c_bits, c_eq, c_load, c_mul, c_ne, c_neg, c_piece, c_ptradd, c_ptrsub, c_return_bits, c_sext, c_slt, c_store, c_sub, c_subpiece, c_ule, c_ult, c_zext

def FUN_00108560(param_0, param_1):
    abi_context = c_abi_context('function_entry:1082720')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    local_40 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    v_122 = c_ptrsub(abi_stack_pointer, -0x68, 64)
    v_6864 = c_bits(c_abi_call(abi_context, 'FUN_00103f60', (param_1, v_122), plan_id='call_site:1082720:(ram, 0x10858c, 50, 12):12'), 8)
    if not c_ne(v_6864, 0, 8):
        v_3598 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (param_1,), plan_id='call_site:1083494:(ram, 0x108869, 877, 6):6'), 64)
        v_3601 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109a68, 5), plan_id='call_site:1083494:(ram, 0x10887f, 893, 11):11'), 64)
        c_abi_call(abi_context, 'error', (0, 0, v_3601, v_3598), plan_id='call_site:1083494:(ram, 0x108890, 928, 15):15')
        c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1083494:(ram, 0x10889a, 932, 19):19')
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1083551:(ram, 0x10889f, 618, 6):6')
    else:
        v_9147 = c_piece(uStack_60, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64), 16, 64, 80)
        v_226 = float_nan(v_9147)
        if not v_226:
            v_9077 = c_ptrsub(0, 0x10c040, 64)
            v_3583 = c_bits(c_abi_call(abi_context, 'FUN_00108320', (1, param_1, v_9077), plan_id='call_site:1083399:(ram, 0x108819, 801, 4):4'), 64)
            v_9080 = c_ptrsub(0, 0x10c040, 64)
            v_3586 = c_bits(c_abi_call(abi_context, 'FUN_00108320', (0, 0x109154, v_9080), plan_id='call_site:1083399:(ram, 0x10882d, 817, 10):10'), 64)
            v_3589 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109161, 5), plan_id='call_site:1083399:(ram, 0x108843, 833, 15):15'), 64)
            c_abi_call(abi_context, 'error', (0, 0, v_3589, v_3586, v_3583), plan_id='call_site:1083399:(ram, 0x108857, 869, 19):19')
            c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1083399:(ram, 0x108861, 873, 23):23')
            v_3598 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (param_1,), plan_id='call_site:1083494:(ram, 0x108869, 877, 6):6'), 64)
            v_3601 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109a68, 5), plan_id='call_site:1083494:(ram, 0x10887f, 893, 11):11'), 64)
            c_abi_call(abi_context, 'error', (0, 0, v_3601, v_3598), plan_id='call_site:1083494:(ram, 0x108890, 928, 15):15')
            c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1083494:(ram, 0x10889a, 932, 19):19')
            c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1083551:(ram, 0x10889f, 618, 6):6')
        else:
            v_2514 = c_bits(c_abi_call(abi_context, '__ctype_b_loc', (), plan_id='call_site:1082794:(ram, 0x1085aa, 114, 6):6'), 64)
            v_280 = c_load(MEM, v_2514, 64)
            v_3927 = param_1
            while True:
                v_286 = c_load(MEM, v_3927, 8)
                v_306 = c_load(MEM, c_add(v_280, c_add(c_mul(c_zext(v_286, 8, 64), 2, 64), 1, 64), 64), 8)
                v_3927 = c_ptradd(v_3927, 1, 1, 64)
            local_58 = 0
            iStack_50 = 0x7fffffff
            v_9151 = c_bits(c_abi_call(abi_context, 'strchr', (v_3927, 0x2e), plan_id='call_site:1082828:(ram, 0x1085e5, 157, 11):11'), 64)
            if c_eq(v_9151, 0, 64):
                v_2530 = c_bits(c_abi_call(abi_context, 'strchr', (v_3927, 0x70), plan_id='call_site:1083229:(ram, 0x108765, 770, 9):9'), 64)
                if not c_eq(v_2530, 0, 64):
                    pass
                else:
                    local_50 = 0
            v_2538 = c_bits(c_abi_call(abi_context, 'strcspn', (v_3927, 0x109179), plan_id='call_site:1082870:(ram, 0x108600, 173, 18):18'), 64)
            v_434 = c_ptradd(v_3927, v_2538, 1, 64)
            v_437 = c_load(MEM, v_434, 8)
            if not c_eq(v_437, 0, 8):
                pass
            else:
                v_474 = int2float(0)
                v_515 = float_mult(v_9147, v_474)
                v_527 = float_equal(v_515, v_474)
                if v_527:
                    pass
                else:
                    v_9155 = c_bits(c_abi_call(abi_context, 'strlen', (v_3927,), plan_id='call_site:1082919:(ram, 0x10862a, 246, 9):9'), 64)
                    local_58 = v_9155
                    if c_eq(v_9151, 0, 64):
                        v_4437 = 0
                    else:
                        v_634 = c_ptradd(v_9151, 1, 1, 64)
                        v_2553 = c_bits(c_abi_call(abi_context, 'strcspn', (v_634, 0x10917c), plan_id='call_site:1082944:(ram, 0x10864b, 266, 11):11'), 64)
                        if c_ult(v_2553, 2147483648, 64):
                            local_50 = c_subpiece(v_2553, 0, 64, 32)
                            if not c_eq(v_2553, 0, 64):
                                if c_eq(v_3927, v_9151, 64):
                                    v_3625 = 1
                                else:
                                    v_712 = c_ptradd(v_9151, -1, 1, 64)
                                    v_715 = c_load(MEM, v_712, 8)
                                    v_3625 = c_zext(c_ult(9, c_sub(c_sext(v_715, 8, 32), 0x30, 32), 32), 8, 64)
                            else:
                                v_3625 = -1
                        v_795 = c_ptradd(v_9155, v_3625, 1, 64)
                        local_58 = v_795
                        v_4437 = v_2553
                    v_9159 = c_bits(c_abi_call(abi_context, 'strchr', (v_3927, 0x65), plan_id='call_site:1083008:(ram, 0x108688, 335, 18):18'), 64)
                    v_4400 = v_9159
                    if not c_ne(v_4400, 0, 64):
                        v_9161 = c_bits(c_abi_call(abi_context, 'strchr', (v_3927, 0x45), plan_id='call_site:1083272:(ram, 0x108790, 716, 9):9'), 64)
                        v_4400 = v_9161
                        if not c_ne(v_4400, 0, 64):
                            pass
                        else:
                            v_865 = c_ptradd(v_4400, 1, 1, 64)
                            v_2578 = c_bits(c_abi_call(abi_context, 'strtol', (v_865, 0, 0xa), plan_id='call_site:1083033:(ram, 0x1086a7, 363, 19):19'), 64)
                            v_7177 = c_subpiece(v_2578, 0, 64, 32)
                            if c_slt(v_2578, 0, 64):
                                v_2585 = c_bits(c_abi_call(abi_context, 'strlen', (v_3927,), plan_id='call_site:1083320:(ram, 0x1087c5, 639, 10):10'), 64)
                                v_9092 = c_ptradd(local_58, c_sub(c_neg(v_2585, 64), v_3927, 64), 1, 64)
                                v_1653 = c_ptradd(v_4400, v_9092, 1, 64)
                                if c_eq(v_9151, 0, 64):
                                    v_1806 = c_ptradd(v_1653, 1, 1, 64)
                                    local_58 = v_1806
                                else:
                                    v_1705 = c_ptradd(v_9151, 1, 1, 64)
                                    v_1725 = c_ptradd(v_1653, 1, 1, 64)
                                    local_58 = v_1653
                                    if c_eq(v_4400, v_1705, 64):
                                        pass
                                    else:
                                        local_58 = v_1725
                                v_3856 = c_neg(v_2578, 64)
                            else:
                                local_50 = iStack_50
                                v_6961 = local_50
                                if v_2578 < local_50:
                                    pass
                                else:
                                    v_6961 = v_7177
                                v_1067 = c_sub(iStack_50, v_6961, 32)
                                v_2592 = c_bits(c_abi_call(abi_context, 'strlen', (v_3927,), plan_id='call_site:1083093:(ram, 0x1086de, 439, 12):12'), 64)
                                v_9093 = c_ptradd(local_58, c_sub(c_neg(v_2592, 64), v_3927, 64), 1, 64)
                                local_58 = c_ptradd(v_4400, v_9093, 1, 64)
                                v_9050 = bool_and(c_ne(v_4437, 0, 64), c_ne(v_9151, 0, 64))
                                if not (c_ne(v_4437, 0, 64) and c_ne(v_9151, 0, 64)):
                                    pass
                                else:
                                    if local_50 - v_6961 != 0:
                                        pass
                                    else:
                                        local_58 = c_ptradd(local_58, -1, 1, 64)
                                v_4425 = v_4437
                                if c_ule(v_2578, v_4437, 64):
                                    pass
                                else:
                                    v_4425 = v_2578
                                v_3856 = c_sub(v_2578, v_4425, 64)
                            local_58 = c_ptradd(local_58, v_3856, 1, 64)
            v_7599 = c_piece(local_5e, local_60, 48, 16, 64)
            v_8002 = c_piece(local_4c, local_50, 32, 32, 64)
            c_store(MEM, param_0, local_68, 64)
            v_7292 = c_ptradd(param_0, 1, 8, 64)
            c_store(MEM, v_7292, v_7599, 64)
            v_1428 = c_ptradd(param_0, 2, 8, 64)
            c_store(MEM, v_1428, local_58, 64)
            v_7302 = c_ptradd(param_0, 3, 8, 64)
            c_store(MEM, v_7302, v_8002, 64)
            v_1459 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
            if not c_eq(local_40, v_1459, 64):
                c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1083551:(ram, 0x10889f, 618, 6):6')
            else:
                return c_return_bits(param_0, 64)
