# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::fseeko
# Entry address: 0x102690
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def fseeko(param_1, param_0, param_2):
    abi_context = c_abi_context('function_entry:1058448')
    v_17 = c_bits(c_abi_call(abi_context, PTR_fseeko_0010bf58, (), plan_id='call_site:1058452:(ram, 0x102694, 0, 2):2'), 32)
    return c_abi_return(abi_context, v_17, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1058448')
