# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00103f60
# Entry address: 0x103f60
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptrsub, c_return_bits, c_store

def FUN_00103f60(param_0, param_1):
    abi_context = c_abi_context('function_entry:1064800')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    abi_st0 = c_abi_get(abi_context, 'machine_state', 'ST0', 80)
    v_34 = c_ptrsub(abi_stack_pointer, -0x28, 64)
    local_20 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    v_504 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1064800:(ram, 0x103f7e, 38, 8):8'), 64)
    c_store(MEM, v_504, 0, 32)
    c_abi_call(abi_context, 'FUN_00103df0', (param_0, v_34), plan_id='call_site:1064800:(ram, 0x103f92, 46, 14):14')
    v_1171 = 0
    if param_0 == c_load(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), 64):
        pass
    else:
        v_184 = c_load(MEM, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), 64), 8)
        if c_eq(v_184, 0, 8):
            v_369 = int2float(0)
            v_404 = float_notequal(in_ST0, v_369)
            v_1171 = 1
            if v_404:
                v_451 = c_load(MEM, v_504, 32)
                v_1171 = c_ne(v_451, 0x22, 32)
    c_store(MEM, param_1, in_ST0, 80)
    v_267 = c_load(MEM, c_add(in_FS_OFFSET, 0x28, 64), 64)
    if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), 64) != v_267:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1064938:(ram, 0x103fea, 138, 1):1')
    else:
        return c_return_bits(v_1171, 8)
