# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::realloc
# Entry address: 0x102620
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def realloc(param_0, param_1):
    abi_context = c_abi_context('function_entry:1058336')
    v_40 = c_bits(c_abi_call(abi_context, PTR_realloc_0010bf20, (), plan_id='call_site:1058340:(ram, 0x102624, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_40, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1058336')
