# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::mbrtowc
# Entry address: 0x1024c0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def mbrtowc(param_2, param_3, param_0, param_1):
    abi_context = c_abi_context('function_entry:1057984')
    v_18 = c_bits(c_abi_call(abi_context, PTR_mbrtowc_0010be70, (), plan_id='call_site:1057988:(ram, 0x1024c4, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_18, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1057984')
