# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::FUN_00103db0
# Entry address: 0x103db0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_load, c_store

def FUN_00103db0():
    abi_context = c_abi_context('function_entry:1064368')
    v_221 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1090c8, 5), plan_id='call_site:1064368:(ram, 0x103dc4, 30, 2):2'), 64)
    c_abi_call(abi_context, 'error', (c_load(MEM, 0x10c024, 32), 0, 0x109176, v_221), plan_id='call_site:1064368:(ram, 0x103ddd, 57, 5):5')
    c_abi_call(abi_context, 'abort', (), plan_id='call_site:1064368:(ram, 0x103de2, 60, 7):7')
