# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: <EXTERNAL>::memset
# Entry address: 0x102510
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def memset(param_2, param_0, param_1):
    abi_context = c_abi_context('function_entry:1058064')
    v_46 = c_bits(c_abi_call(abi_context, PTR_memset_0010be98, (), plan_id='call_site:1058068:(ram, 0x102514, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_46, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1058064')
