# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::FUN_00103ff0
# Entry address: 0x103ff0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_and, c_bits, c_eq, c_load, c_ne, c_ptradd, c_ptrsub, c_return_bits

def FUN_00103ff0(param_0, param_1):
    abi_context = c_abi_context('function_entry:1064944')
    v_2204 = c_bits(c_abi_call(abi_context, 'nl_langinfo', (0xe,), plan_id='call_site:1064944:(ram, 0x104000, 21, 0):0'), 64)
    if not c_ne(v_2204, 0, 64):
        v_1573 = c_ptrsub(0, 0x1090e2, 64)
        if c_ne(param_1, 9, 32):
            pass
        else:
            v_1573 = c_ptrsub(0, 0x109202, 64)
        return c_return_bits(v_1573, 64)
    else:
        v_86 = c_load(MEM, v_2204, 8)
        if not c_ne(v_86, 0, 8):
            pass
        else:
            v_1936 = c_and(v_86, 0xdf, 8)
            if not c_eq(c_and(v_86, 223, 8), 85, 8):
                if not c_eq(c_and(v_86, 223, 8), 71, 8):
                    pass
                else:
                    v_644 = c_ptradd(v_2204, 1, 1, 64)
                    v_647 = c_load(MEM, v_644, 8)
                    if c_eq(c_and(v_647, 223, 8), 66, 8):
                        v_708 = c_ptradd(v_2204, 2, 1, 64)
                        v_711 = c_load(MEM, v_708, 8)
                        if not c_eq(v_711, 49, 8):
                            pass
                        else:
                            v_746 = c_ptradd(v_2204, 3, 1, 64)
                            v_749 = c_load(MEM, v_746, 8)
                            if not c_eq(v_749, 56, 8):
                                pass
                            else:
                                v_784 = c_ptradd(v_2204, 4, 1, 64)
                                v_787 = c_load(MEM, v_784, 8)
                                if not c_eq(v_787, 48, 8):
                                    pass
                                else:
                                    v_822 = c_ptradd(v_2204, 5, 1, 64)
                                    v_825 = c_load(MEM, v_822, 8)
                                    if not c_eq(v_825, 51, 8):
                                        pass
                                    else:
                                        v_860 = c_ptradd(v_2204, 6, 1, 64)
                                        v_863 = c_load(MEM, v_860, 8)
                                        if not c_eq(v_863, 48, 8):
                                            pass
                                        else:
                                            v_2055 = c_bits(c_abi_call(abi_context, 'FUN_001037b0', (v_2204, 0x1090ec, 0, 0), plan_id='call_site:1065134:(ram, 0x1040b9, 362, 1):1'), 32)
                                            if not c_ne(v_2055, 0, 32):
                                                pass
                                            else:
                                                v_986 = c_load(MEM, param_0, 8)
                                                v_1551 = c_ptrsub(0, 0x1090e4, 64)
                                                if c_ne(v_986, 96, 8):
                                                    pass
                                                else:
                                                    v_1551 = c_ptrsub(0, 0x1090df, 64)
                                                return c_return_bits(v_1551, 64)
            else:
                v_175 = c_ptradd(v_2204, 1, 1, 64)
                v_178 = c_load(MEM, v_175, 8)
                if not c_eq(c_and(v_178, 223, 8), 84, 8):
                    pass
                else:
                    v_241 = c_ptradd(v_2204, 2, 1, 64)
                    v_244 = c_load(MEM, v_241, 8)
                    if not c_eq(c_and(v_244, 223, 8), 70, 8):
                        pass
                    else:
                        v_307 = c_ptradd(v_2204, 3, 1, 64)
                        v_310 = c_load(MEM, v_307, 8)
                        if not c_eq(v_310, 45, 8):
                            pass
                        else:
                            v_345 = c_ptradd(v_2204, 4, 1, 64)
                            v_348 = c_load(MEM, v_345, 8)
                            if not c_eq(v_348, 56, 8):
                                pass
                            else:
                                v_383 = c_ptradd(v_2204, 5, 1, 64)
                                v_386 = c_load(MEM, v_383, 8)
                                if not c_eq(v_386, 0, 8):
                                    pass
                                else:
                                    v_421 = c_load(MEM, param_0, 8)
                                    v_1570 = c_ptrsub(0, 0x1090e8, 64)
                                    if c_ne(v_421, 96, 8):
                                        pass
                                    else:
                                        v_1570 = c_ptrsub(0, 0x1090db, 64)
                                    return c_return_bits(v_1570, 64)
