# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00103c60
# Entry address: 0x103c60
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptrsub, c_return_bits, c_store, c_ult

def FUN_00103c60():
    abi_context = c_abi_context('function_entry:1064032')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    v_10 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
    c_abi_call(abi_context, 'clearerr_unlocked', (v_10,), plan_id='call_site:1064032:(ram, 0x103c6c, 8, 6):6')
    v_905 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1090ab, 5), plan_id='call_site:1064032:(ram, 0x103c7f, 23, 12):12'), 64)
    v_675 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1064032:(ram, 0x103c87, 27, 17):17'), 64)
    v_75 = c_load(MEM, v_675, 32)
    c_abi_call(abi_context, 'error', (1, v_75, v_905), plan_id='call_site:1064032:(ram, 0x103c98, 45, 23):23')
    v_190 = c_ptrsub(abi_stack_pointer, -0x130, 64)
    lStack_28 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), 64))[1])(c_load(MEM, c_add(in_FS_OFFSET, 0x28, 64), 64))
    v_688 = c_bits(c_abi_call(abi_context, 'setlocale', (0, 0), plan_id='call_site:1064032:(ram, 0x103cc1, 99, 33):33'), 64)
    if c_eq(v_688, 0, 64):
        v_1961 = 0
    else:
        v_1961 = 0
        v_695 = c_bits(c_abi_call(abi_context, 'strlen', (v_688,), plan_id='call_site:1064143:(ram, 0x103cd8, 124, 6):6'), 64)
        if c_ult(v_695, 257, 64):
            v_1982 = c_bits(c_abi_call(abi_context, '__memcpy_chk', (v_190, v_688, c_add(v_695, 1, 64), 0x101), plan_id='call_site:1064208:(ram, 0x103d1f, 188, 6):6'), 64)
            if local_130 == 67:
                if local_12f == 0:
                    pass
                else:
                    v_708 = c_bits(c_abi_call(abi_context, 'strcmp', (v_1982, 0x1090b7), plan_id='call_site:1064237:(ram, 0x103d34, 205, 4):4'), 32)
                    v_1961 = c_ne(v_708, 0, 32)
            else:
                v_708 = c_bits(c_abi_call(abi_context, 'strcmp', (v_1982, 0x1090b7), plan_id='call_site:1064237:(ram, 0x103d34, 205, 4):4'), 32)
                v_1961 = c_ne(v_708, 0, 32)
    v_378 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    if local_28 != v_378:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1064285:(ram, 0x103d5d, 178, 2):2')
    else:
        return c_return_bits(v_1961, 8)
