# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::_INIT_0
# Entry address: 0x1037a0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_return_bits

def _INIT_0():
    abi_context = c_abi_context('function_entry:1062816')
    c_abi_call(abi_context, 'FUN_00103720', (), plan_id='call_site:1062820:(ram, 0x1037a4, 0, 0):0')
    return c_return_bits(0, 64)
