# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_001036f0
# Entry address: 0x1036f0
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def FUN_001036f0():
    return c_return_bits(0, 64)
