# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::FUN_001040e0
# Entry address: 0x1040e0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_ne, c_return_bits

def FUN_001040e0(param_0):
    abi_context = c_abi_context('function_entry:1065184')
    v_116 = c_bits(c_abi_call(abi_context, 'malloc', (param_0,), plan_id='call_site:1065184:(ram, 0x1040e4, 6, 0):0'), 64)
    if not c_eq(v_116, 0, 64):
        return c_return_bits(0, 64)
    else:
        if c_ne(param_0, 0, 64):
            c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1065205:(ram, 0x1040f5, 38, 0):0')
