# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::FUN_00104100
# Entry address: 0x104100
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_ne, c_return_bits

def FUN_00104100(param_0, param_1):
    abi_context = c_abi_context('function_entry:1065216')
    if not c_eq(param_1, 0, 64):
        v_236 = c_bits(c_abi_call(abi_context, 'realloc', (param_0, param_1), plan_id='call_site:1065230:(ram, 0x104111, 29, 0):0'), 64)
        if not c_eq(v_236, 0, 64):
            return c_return_bits(v_236, 64)
        else:
            if c_ne(param_1, 0, 64):
                c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1065265:(ram, 0x104131, 61, 0):0')
    else:
        if c_ne(param_0, 0, 64):
            c_abi_call(abi_context, 'free', (param_0,), plan_id='call_site:1065256:(ram, 0x104128, 66, 0):0')
            return c_return_bits(0, 64)
