# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::strspn
# Entry address: 0x102520
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def strspn(param_1, param_0):
    abi_context = c_abi_context('function_entry:1058080')
    v_16 = c_bits(c_abi_call(abi_context, PTR_strspn_0010bea0, (), plan_id='call_site:1058084:(ram, 0x102524, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_16, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1058080')
