# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::_FINI_0
# Entry address: 0x103760
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_eq, c_load, c_ne, c_return_bits, c_store

def _FINI_0():
    abi_context = c_abi_context('function_entry:1062752')
    if c_load(MEM, 0x10c0a0, 8) != 0:
        return c_return_bits(0, 64)
    else:
        if c_load(MEM, 0x10bfe8, 64) == 0:
            pass
        else:
            c_abi_call(abi_context, '__cxa_finalize', (c_load(MEM, 0x10c008, 64),), plan_id='call_site:1062779:(ram, 0x103782, 30, 3):3')
        c_abi_call(abi_context, 'FUN_001036f0', (), plan_id='call_site:1062791:(ram, 0x103787, 33, 6):6')
        return c_return_bits(0, 64)
