# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::entry
# Entry address: 0x1036c0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_load, c_ptrsub, c_store

def entry(param_0, param_1):
    abi_context = c_abi_context('function_entry:1062592')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_overflow_arguments = c_abi_get(abi_context, 'overflow_argument_area', None, None)
    v_33 = c_ptrsub(abi_stack_pointer, 8, 64)
    v_66 = c_ptrsub(abi_stack_pointer, -8, 64)
    v_337 = c_ptrsub(0, 0x102740, 64)
    c_abi_call(abi_context, PTR___libc_start_main_0010bfa0, (v_337, param_1, v_33, 0, 0, param_0, v_66), plan_id='call_site:1062596:(ram, 0x1036df, 55, 5):5')
    while True:
        pass
