# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_001038a0
# Entry address: 0x1038a0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptradd, c_ptrsub, c_store

def FUN_001038a0(param_0):
    abi_context = c_abi_context('function_entry:1063072')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    v_60 = c_ptrsub(abi_stack_pointer, -0xb8, 64)
    local_40 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    if not c_ne(param_0, 0, 32):
        v_2536 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109290, 5), plan_id='call_site:1063172:(ram, 0x103910, 111, 5):5'), 64)
        c_abi_call(abi_context, '__printf_chk', (1, v_2536, DAT_0010c1f8, DAT_0010c1f8, DAT_0010c1f8), plan_id='call_site:1063172:(ram, 0x103928, 129, 10):10')
        v_361 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9892 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1092f8, 5), plan_id='call_site:1063172:(ram, 0x103946, 147, 19):19'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9892, v_361), plan_id='call_site:1063172:(ram, 0x103951, 152, 25):25')
        v_386 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9894 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109338, 5), plan_id='call_site:1063172:(ram, 0x103968, 169, 33):33'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9894, v_386), plan_id='call_site:1063172:(ram, 0x103973, 174, 39):39')
        v_441 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9896 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109388, 5), plan_id='call_site:1063172:(ram, 0x10398a, 191, 47):47'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9896, v_441), plan_id='call_site:1063172:(ram, 0x103995, 196, 53):53')
        v_496 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9898 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109460, 5), plan_id='call_site:1063172:(ram, 0x1039ac, 213, 61):61'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9898, v_496), plan_id='call_site:1063172:(ram, 0x1039b7, 218, 67):67')
        v_551 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9900 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109490, 5), plan_id='call_site:1063172:(ram, 0x1039ce, 235, 75):75'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9900, v_551), plan_id='call_site:1063172:(ram, 0x1039d9, 240, 81):81')
        v_606 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9902 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1094c8, 5), plan_id='call_site:1063172:(ram, 0x1039f0, 257, 89):89'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9902, v_606), plan_id='call_site:1063172:(ram, 0x1039fb, 262, 95):95')
        v_661 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
        v_9904 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1096d0, 5), plan_id='call_site:1063172:(ram, 0x103a12, 279, 103):103'), 64)
        c_abi_call(abi_context, 'fputs_unlocked', (v_9904, v_661), plan_id='call_site:1063172:(ram, 0x103a24, 285, 109):109')
        local_58 = 0
        local_b8 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xb8, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xb8, 64), 64))[1])(c_ptrsub(0, 0x109008, 64))
        local_b0 = 0x10900a
        local_a8 = 0x109082
        local_a0 = 0x10901a
        local_88 = 0x109049
        local_98 = 0x109030
        local_78 = 0x109053
        local_90 = 0x10903a
        local_80 = 0x10903a
        local_70 = 0x10903a
        local_68 = 0x10905d
        local_60 = 0x10903a
        local_50 = 0
        v_9889 = v_60
        while not c_eq(v_848, 0, 64):
            v_845 = c_ptradd(v_9889, 0x10, 1, 64)
            v_848 = c_load(MEM, v_845, 64)
            v_859 = c_ptradd(v_9889, 0x10, 1, 64)
            v_1883 = c_bits(c_abi_call(abi_context, 'strcmp', (0x109004, v_848), plan_id='call_site:1063621:(ram, 0x103ac8, 361, 19):19'), 32)
            v_9889 = v_859
            if c_ne(v_1883, 0, 32):
                pass
            else:
                break
        v_943 = c_ptradd(v_9889, 0x18, 1, 64)
        v_946 = c_load(MEM, v_943, 64)
        if c_eq(v_946, 0, 64):
            v_2587 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109067, 5), plan_id='call_site:1063848:(ram, 0x103ba8, 567, 19):19'), 64)
            c_abi_call(abi_context, '__printf_chk', (1, v_2587, 0x10907e, 0x1097a0), plan_id='call_site:1063848:(ram, 0x103bc8, 585, 40):40')
            v_1901 = c_bits(c_abi_call(abi_context, 'setlocale', (5, 0), plan_id='call_site:1063848:(ram, 0x103bd4, 599, 59):59'), 64)
            if not c_ne(v_1901, 0, 64):
                v_2596 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109090, 5), plan_id='call_site:1063926:(ram, 0x103c04, 641, 37):37'), 64)
                v_1650 = c_ptrsub(0, 0x109004, 64)
                v_9729 = c_ptrsub(0, 0x109004, 64)
                c_abi_call(abi_context, '__printf_chk', (1, v_2596, 0x1097a0, v_9729), plan_id='call_site:1063926:(ram, 0x103c20, 659, 59):59')
            else:
                v_1910 = c_bits(c_abi_call(abi_context, 'strncmp', (v_1901, 0x10908c, 3), plan_id='call_site:1063905:(ram, 0x103bed, 615, 19):19'), 32)
                if c_ne(v_1910, 0, 32):
                    v_1663 = c_ptrsub(0, 0x109004, 64)
                    v_1366 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
                    v_9910 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1097c8, 5), plan_id='call_site:1063992:(ram, 0x103c4a, 558, 40):40'), 64)
                    c_abi_call(abi_context, 'fputs_unlocked', (v_9910, v_1366), plan_id='call_site:1063992:(ram, 0x103c55, 563, 60):60')
                else:
                    v_2596 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109090, 5), plan_id='call_site:1063926:(ram, 0x103c04, 641, 37):37'), 64)
                    v_1650 = c_ptrsub(0, 0x109004, 64)
                    v_9729 = c_ptrsub(0, 0x109004, 64)
                    c_abi_call(abi_context, '__printf_chk', (1, v_2596, 0x1097a0, v_9729), plan_id='call_site:1063926:(ram, 0x103c20, 659, 59):59')
        else:
            v_2602 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109067, 5), plan_id='call_site:1063660:(ram, 0x103aec, 400, 19):19'), 64)
            c_abi_call(abi_context, '__printf_chk', (1, v_2602, 0x10907e, 0x1097a0), plan_id='call_site:1063660:(ram, 0x103b0c, 418, 40):40')
            v_1938 = c_bits(c_abi_call(abi_context, 'setlocale', (5, 0), plan_id='call_site:1063660:(ram, 0x103b18, 432, 59):59'), 64)
            v_3764 = c_load(MEM, v_943, 64)
            if not c_ne(v_1938, 0, 64):
                pass
            else:
                v_1947 = c_bits(c_abi_call(abi_context, 'strncmp', (v_1938, 0x10908c, 3), plan_id='call_site:1063717:(ram, 0x103b31, 448, 19):19'), 32)
                v_3764 = c_load(MEM, v_943, 64)
                if c_ne(v_1947, 0, 32):
                    v_1366 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
                    v_9910 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1097c8, 5), plan_id='call_site:1063992:(ram, 0x103c4a, 558, 40):40'), 64)
                    c_abi_call(abi_context, 'fputs_unlocked', (v_9910, v_1366), plan_id='call_site:1063992:(ram, 0x103c55, 563, 60):60')
            v_2617 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109090, 5), plan_id='call_site:1063742:(ram, 0x103b4c, 474, 38):38'), 64)
            v_9723 = c_ptrsub(0, 0x109004, 64)
            c_abi_call(abi_context, '__printf_chk', (1, v_2617, 0x1097a0, v_9723), plan_id='call_site:1063742:(ram, 0x103b61, 491, 59):59')
            v_9726 = c_ptrsub(0, 0x109004, 64)
            if c_ne(v_3764, v_9726, 64):
                pass
            else:
                pass
        v_2623 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109810, 5), plan_id='call_site:1063803:(ram, 0x103b89, 523, 39):39'), 64)
        c_abi_call(abi_context, '__printf_chk', (1, v_2623, v_3757, v_3736), plan_id='call_site:1063803:(ram, 0x103b9e, 540, 58):58')
    else:
        v_2629 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109268, 5), plan_id='call_site:1063123:(ram, 0x1038dc, 70, 19):19'), 64)
        v_194 = c_load(MEM, c_load(MEM, 0x10bff0, 64), 64)
        c_abi_call(abi_context, '__fprintf_chk', (v_194, 1, v_2629, DAT_0010c1f8), plan_id='call_site:1063123:(ram, 0x1038f8, 89, 40):40')
    c_abi_call(abi_context, 'exit', (param_0,), plan_id='call_site:1063165:(ram, 0x1038ff, 94, 36):36')
