# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00103ca0
# Entry address: 0x103ca0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptrsub, c_return_bits, c_store, c_ult

def FUN_00103ca0():
    abi_context = c_abi_context('function_entry:1064096')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    v_74 = c_ptrsub(abi_stack_pointer, -0x128, 64)
    local_20 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    v_538 = c_bits(c_abi_call(abi_context, 'setlocale', (0, 0), plan_id='call_site:1064096:(ram, 0x103cc1, 53, 8):8'), 64)
    if c_eq(v_538, 0, 64):
        v_1382 = 0
    else:
        v_1382 = 0
        v_545 = c_bits(c_abi_call(abi_context, 'strlen', (v_538,), plan_id='call_site:1064143:(ram, 0x103cd8, 78, 5):5'), 64)
        if c_ult(v_545, 257, 64):
            v_1398 = c_bits(c_abi_call(abi_context, '__memcpy_chk', (v_74, v_538, c_add(v_545, 1, 64), 0x101), plan_id='call_site:1064208:(ram, 0x103d1f, 142, 5):5'), 64)
            if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x128, 64), 8) == 67:
                if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x127, 64), 8) == 0:
                    pass
                else:
                    v_558 = c_bits(c_abi_call(abi_context, 'strcmp', (v_1398, 0x1090b7), plan_id='call_site:1064237:(ram, 0x103d34, 159, 3):3'), 32)
                    v_1382 = c_ne(v_558, 0, 32)
            else:
                v_558 = c_bits(c_abi_call(abi_context, 'strcmp', (v_1398, 0x1090b7), plan_id='call_site:1064237:(ram, 0x103d34, 159, 3):3'), 32)
                v_1382 = c_ne(v_558, 0, 32)
    v_262 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), 64) != v_262:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1064285:(ram, 0x103d5d, 132, 1):1')
    else:
        return c_return_bits(v_1382, 8)
