# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::_exit
# Entry address: 0x10d048
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def _exit(param_0):
    return c_return_bits(1, 32)
