# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::getopt_long
# Entry address: 0x1024b0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def getopt_long():
    abi_context = c_abi_context('function_entry:1057968')
    c_abi_call(abi_context, PTR_getopt_long_0010be68, (), plan_id='call_site:1057972:(ram, 0x1024b4, 0, 2):2')
    return c_return_bits(0, 64)
