# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_001037b0
# Entry address: 0x1037b0
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_add, c_and, c_eq, c_load, c_ne, c_return_bits, c_sext, c_sub, c_ult, c_zext

def FUN_001037b0(param_0, param_1, param_2, param_3):
    v_2038 = c_load(MEM, c_add(param_0, 7, 64), 8)
    if not c_ult(c_sub(param_2, 65, 32), 26, 32):
        pass
    else:
        v_2038 = c_and(v_2038, 0xdf, 8)
    if c_ne(v_2038, param_2, 8):
        return c_return_bits(0, 8)
    else:
        v_2076 = 1
        if c_ne(param_2, 0, 8):
            v_2042 = c_load(MEM, c_add(param_0, 8, 64), 8)
            if not c_ult(c_sub(param_3, 65, 32), 26, 32):
                pass
            else:
                v_2042 = c_and(v_2042, 0xdf, 8)
            if c_ne(v_2042, param_3, 8):
                return c_return_bits(0, 8)
            else:
                v_2076 = 1
                if not c_ne(param_3, 0, 8):
                    pass
                else:
                    if not c_ne(param_0, param_1, 64):
                        pass
                    else:
                        v_1297 = 9
                        while True:
                            v_1962 = c_load(MEM, c_add(param_0, v_1297, 64), 8)
                            v_1989 = c_zext(v_1962, 8, 32)
                            if not c_ult(c_sub(v_1962, 65, 32), 26, 32):
                                pass
                            else:
                                v_1989 = c_add(c_zext(v_1962, 8, 32), 0x20, 32)
                                v_1962 = c_add(v_1962, 0x20, 8)
                            v_1967 = c_load(MEM, c_add(param_1, v_1297, 64), 8)
                            v_2017 = c_zext(v_1967, 8, 32)
                            if not c_ult(c_sub(v_1967, 65, 32), 26, 32):
                                pass
                            else:
                                v_2017 = c_add(c_zext(v_1967, 8, 32), 0x20, 32)
                                v_1967 = c_add(v_1967, 0x20, 8)
                            if not c_ne(v_1962, 0, 8):
                                break
                            v_1297 = c_add(v_1297, 1, 64)
                            if not c_eq(v_1962, v_1967, 8):
                                break
                        v_2076 = c_eq(v_1989, v_2017, 32)
                return c_return_bits(v_2076, 8)
        else:
            return c_return_bits(v_2076, 8)
