# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::feedback
# Entry address: 0x10115e
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_add, c_mul, c_return_bits

def feedback(param_0, param_1):
    return c_return_bits(c_add(param_0, c_mul(param_1, 0xfffffffd, 32), 32), 32)
