# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::_start
# Entry address: 0x101060
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_load, c_ptrsub, c_store

def _start(param_0, param_1):
    abi_context = c_abi_context('function_entry:1052768')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_overflow_arguments = c_abi_get(abi_context, 'overflow_argument_area', None, None)
    v_33 = c_ptrsub(abi_stack_pointer, 8, 64)
    v_66 = c_ptrsub(abi_stack_pointer, -8, 64)
    v_337 = c_ptrsub(0, 0x1011e4, 64)
    c_abi_call(abi_context, PTR___libc_start_main_00103fd8, (v_337, param_1, v_33, 0, 0, param_0, v_66), plan_id='call_site:1052772:(ram, 0x10107f, 55, 5):5')
    while True:
        pass
