# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::memset
# Entry address: 0x102510
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def memset(param_2, param_0, param_1):
    abi_context = c_abi_context('function_entry:1058064')
    v_46 = c_bits(c_abi_call(abi_context, PTR_memset_0010be98, (), plan_id='call_site:1058068:(ram, 0x102514, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_46, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1058064')
