# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::_DT_FINI
# Entry address: 0x1088c4
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def _DT_FINI():
    return c_return_bits(0, 64)
