# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: switchD_00106f26::default
# Entry address: 0x10272f
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context

def default():
    abi_context = c_abi_context('function_entry:1058607')
    c_abi_call(abi_context, 'abort', (), plan_id='call_site:1058607:(ram, 0x10272f, 2, 0):0')
