# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00108540
# Entry address: 0x108540
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_ptrsub, c_return_bits

def FUN_00108540(param_0):
    abi_context = c_abi_context('function_entry:1082688')
    v_105 = c_ptrsub(0, 0x10c040, 64)
    c_abi_call(abi_context, 'FUN_00108320', (0, param_0, v_105), plan_id='call_site:1082688:(ram, 0x10854c, 12, 1):1')
    return c_return_bits(0, 64)
