# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::free
# Entry address: 0x1023c0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def free(param_0):
    abi_context = c_abi_context('function_entry:1057728')
    c_abi_call(abi_context, PTR_free_0010bdf0, (), plan_id='call_site:1057732:(ram, 0x1023c4, 0, 2):2')
    return c_return_bits(0, 64)
