# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::__freading
# Entry address: 0x102600
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def __freading():
    abi_context = c_abi_context('function_entry:1058304')
    c_abi_call(abi_context, PTR___freading_0010bf10, (), plan_id='call_site:1058308:(ram, 0x102604, 0, 2):2')
    return c_return_bits(0, 64)
