# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::clearerr_unlocked
# Entry address: 0x102430
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def clearerr_unlocked(param_0):
    abi_context = c_abi_context('function_entry:1057840')
    c_abi_call(abi_context, PTR_clearerr_unlocked_0010be28, (), plan_id='call_site:1057844:(ram, 0x102434, 0, 2):2')
    return c_return_bits(0, 64)
