# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00108320
# Entry address: 0x108320
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_bits, c_eq, c_load, c_mul, c_ne, c_or, c_ptradd, c_ptrsub, c_return_bits, c_sext, c_shl, c_sle, c_store, c_sub, c_ule

def FUN_00108320(param_0, param_1, param_2):
    abi_context = c_abi_context('function_entry:1082144')
    v_1378 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1082144:(ram, 0x108337, 32, 5):5'), 64)
    v_102 = c_load(MEM, v_1378, 32)
    v_2088 = PTR_DAT_0010c090
    DAT_0010c020 = (lambda _pal_v: (c_store(MEM, 0x10c020, _pal_v, 32), c_load(MEM, 0x10c020, 32))[1])(c_load(MEM, 0x10c020, 32))
    if c_load(MEM, 0x10c020, 32) <= param_0:
        v_730 = c_load(MEM, param_2, 32)
        v_737 = c_ptradd(param_2, 2, 4, 64)
        v_750 = c_ptradd(v_2088, c_mul(c_sext(param_0, 32, 64), 2, 64), 8, 64)
        v_770 = c_ptradd(param_2, 1, 4, 64)
        v_773 = c_load(MEM, v_770, 32)
        v_782 = c_load(MEM, v_750, 64)
        v_787 = c_ptradd(v_750, 1, 8, 64)
        v_3996 = c_load(MEM, v_787, 64)
        v_2331 = v_3996
        v_795 = c_ptradd(param_2, 0xc, 4, 64)
        v_798 = c_load(MEM, v_795, 64)
        v_809 = c_ptradd(param_2, 0xa, 4, 64)
        v_812 = c_load(MEM, v_809, 64)
        v_1868 = c_bits(c_abi_call(abi_context, 'FUN_00106e80', (v_3996, v_782, param_1, v_730, c_or(v_773, 1, 32), v_737, v_812, v_798), plan_id='call_site:1082298:(ram, 0x1083f5, 322, 26):26'), 64)
        if not c_ule(v_782, v_1868, 64):
            c_store(MEM, v_1378, v_102, 32)
            return c_return_bits(v_2331, 64)
        else:
            v_934 = c_add(v_1868, 1, 64)
            c_store(MEM, v_750, v_934, 64)
            v_3946 = c_ptrsub(0, 0x10c0c0, 64)
            if not c_ne(v_3996, v_3946, 64):
                pass
            else:
                c_abi_call(abi_context, 'free', (v_3996,), plan_id='call_site:1082394:(ram, 0x108422, 369, 4):4')
            v_1420 = c_bits(c_abi_call(abi_context, 'malloc', (v_934,), plan_id='call_site:1082412:(ram, 0x108434, 379, 8):8'), 64)
            if not c_eq(v_1420, 0, 64):
                v_1086 = c_ptradd(v_750, 1, 8, 64)
                c_store(MEM, v_1086, v_1420, 64)
                v_1094 = c_load(MEM, param_2, 32)
                v_1105 = c_ptradd(param_2, 0xc, 4, 64)
                v_1108 = c_load(MEM, v_1105, 64)
                v_1125 = c_ptradd(param_2, 0xa, 4, 64)
                v_1128 = c_load(MEM, v_1125, 64)
                c_abi_call(abi_context, 'FUN_00106e80', (v_1420, v_934, param_1, v_1094, c_or(v_773, 1, 32), v_737, v_1128, v_1108), plan_id='call_site:1082443:(ram, 0x108469, 429, 18):18')
                v_2331 = v_1420
                c_store(MEM, v_1378, v_102, 32)
                return c_return_bits(v_2331, 64)
            else:
                if c_ne(c_add(v_1868, 1, 64), 0, 64):
                    c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1082552:(ram, 0x1084b8, 486, 8):8')
                else:
                    v_1086 = c_ptradd(v_750, 1, 8, 64)
                    c_store(MEM, v_1086, v_1420, 64)
                    v_1094 = c_load(MEM, param_2, 32)
                    v_1105 = c_ptradd(param_2, 0xc, 4, 64)
                    v_1108 = c_load(MEM, v_1105, 64)
                    v_1125 = c_ptradd(param_2, 0xa, 4, 64)
                    v_1128 = c_load(MEM, v_1125, 64)
                    c_abi_call(abi_context, 'FUN_00106e80', (v_1420, v_934, param_1, v_1094, c_or(v_773, 1, 32), v_737, v_1128, v_1108), plan_id='call_site:1082443:(ram, 0x108469, 429, 18):18')
                    v_2331 = v_1420
                    c_store(MEM, v_1378, v_102, 32)
                    return c_return_bits(v_2331, 64)
    else:
        v_153 = c_add(param_0, 1, 32)
        v_167 = c_shl(c_sext(v_153, 32, 64), 4, 64)
        v_3943 = c_ptrsub(0, 0x10c080, 64)
        if c_load(MEM, 0x10c090, 64) == v_3943:
            v_1385 = c_bits(c_abi_call(abi_context, 'malloc', (v_167,), plan_id='call_site:1082512:(ram, 0x108493, 492, 4):4'), 64)
            if c_eq(v_1385, 0, 64):
                c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1082552:(ram, 0x1084b8, 486, 8):8')
            else:
                c_store(MEM, v_1385, DAT_0010c080, 64)
                v_3070 = c_ptradd(v_1385, 1, 8, 64)
                c_store(MEM, v_3070, c_load(MEM, 0x10c088, 64), 64)
                v_3991 = PTR_DAT_0010c090
                v_2085 = v_1385
                v_611 = c_ptradd(v_2085, c_mul(c_sext(c_load(MEM, 0x10c020, 32), 32, 64), 2, 64), 8, 64)
                c_abi_call(abi_context, 'memset', (v_611, 0, c_shl(c_sext(c_sub(v_153, c_load(MEM, 0x10c020, 32), 32), 32, 64), 4, 64)), plan_id='call_site:1082256:(ram, 0x1083ae, 230, 17):17')
                DAT_0010c020 = (lambda _pal_v: (c_store(MEM, 0x10c020, _pal_v, 32), c_load(MEM, 0x10c020, 32))[1])(v_153)
                v_2088 = v_2085
        else:
            v_2085 = c_bits(c_abi_call(abi_context, 'realloc', (c_load(MEM, 0x10c090, 64), v_167), plan_id='call_site:1082229:(ram, 0x108378, 113, 4):4'), 64)
            v_3991 = v_2085
            if c_eq(v_2085, 0, 64):
                c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1082552:(ram, 0x1084b8, 486, 8):8')
            else:
                v_611 = c_ptradd(v_2085, c_mul(c_sext(c_load(MEM, 0x10c020, 32), 32, 64), 2, 64), 8, 64)
                c_abi_call(abi_context, 'memset', (v_611, 0, c_shl(c_sext(c_sub(v_153, c_load(MEM, 0x10c020, 32), 32), 32, 64), 4, 64)), plan_id='call_site:1082256:(ram, 0x1083ae, 230, 17):17')
                DAT_0010c020 = (lambda _pal_v: (c_store(MEM, 0x10c020, _pal_v, 32), c_load(MEM, 0x10c020, 32))[1])(v_153)
                v_2088 = v_2085
