# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::abort
# Entry address: 0x102720
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context

def abort():
    abi_context = c_abi_context('function_entry:1058592')
    c_abi_call(abi_context, 'abort', (), plan_id='call_site:1058592:(ram, 0x102720, 2, 0):0')
