# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::parse_command
# Entry address: 0x10176d
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptradd, c_return_bits, c_sext, c_slt, c_store, c_sub

def parse_command(param_0, param_1):
    abi_context = c_abi_context('function_entry:1054573')
    local_14 = 0
    c_store(MEM, param_1, 0, 8)
    v_81 = c_ptradd(param_1, 0x10, 1, 64)
    c_store(MEM, v_81, 0, 32)
    v_97 = c_ptradd(param_1, 0x14, 1, 64)
    c_store(MEM, v_97, 0, 32)
    while True:
        v_152 = c_load(MEM, c_add(param_0, c_sext(local_14, 32, 64), 64), 8)
        v_2071 = c_bits(c_abi_call(abi_context, 'is_space_char', (c_sext(v_152, 8, 32),), plan_id='call_site:1054635:(ram, 0x1017c0, 66, 7):7'), 32)
        if not (c_ne(v_2071, 0, 32)):
            break
        local_14 = c_add(local_14, 1, 32)
    v_2550 = local_14
    while True:
        v_268 = c_load(MEM, c_add(param_0, c_sext(local_14, 32, 64), 64), 8)
        if not (c_ne(v_268, 0, 8)):
            break
        v_347 = c_load(MEM, c_add(param_0, c_sext(local_14, 32, 64), 64), 8)
        v_2098 = c_bits(c_abi_call(abi_context, 'is_space_char', (c_sext(v_347, 8, 32),), plan_id='call_site:1054697:(ram, 0x1017fe, 142, 5):5'), 32)
        if not c_eq(v_2098, 0, 32):
            break
        local_14 = c_add(local_14, 1, 32)
    v_424 = c_sub(local_14, v_2550, 32)
    if not c_slt(v_424, 1, 32):
        c_abi_call(abi_context, 'copy_token', (param_1, 0x10, c_add(c_sext(v_2550, 32, 64), param_0, 64), v_424), plan_id='call_site:1054752:(ram, 0x101842, 223, 2):2')
        while True:
            v_627 = c_load(MEM, c_add(param_0, c_sext(local_14, 32, 64), 64), 8)
            v_2139 = c_bits(c_abi_call(abi_context, 'is_space_char', (c_sext(v_627, 8, 32),), plan_id='call_site:1054797:(ram, 0x101862, 251, 6):6'), 32)
            if not (c_ne(v_2139, 0, 32)):
                break
            local_14 = c_add(local_14, 1, 32)
        v_724 = c_load(MEM, c_add(param_0, c_sext(local_14, 32, 64), 64), 8)
        if not c_ne(v_724, 0, 8):
            v_1522 = 1
            return c_return_bits(v_1522, 64)
        else:
            v_765 = c_ptradd(param_1, 0x14, 1, 64)
            v_2155 = c_bits(c_abi_call(abi_context, 'parse_integer', (c_add(param_0, c_sext(local_14, 32, 64), 64), v_765), plan_id='call_site:1054847:(ram, 0x10189a, 319, 3):3'), 32)
            if not c_eq(v_2155, 0, 32):
                v_867 = c_ptradd(param_1, 0x10, 1, 64)
                c_store(MEM, v_867, 1, 32)
                v_1522 = 1
            else:
                return c_return_bits(0xffffffff, 64)
    else:
        v_1522 = 0
    return c_return_bits(v_1522, 64)
    return c_return_bits(v_1522, 64)
