# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::text_equal
# Entry address: 0x1014f7
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_eq, c_load, c_ne, c_return_bits, c_sext

def text_equal(param_0, param_1):
    local_c = 0
    while True:
        v_81 = c_load(MEM, c_add(param_0, c_sext(local_c, 32, 64), 64), 8)
        if not (c_ne(v_81, 0, 8)):
            break
        v_160 = c_load(MEM, c_add(param_1, c_sext(local_c, 32, 64), 64), 8)
        if not c_ne(v_160, 0, 8):
            break
        v_425 = c_load(MEM, c_add(param_0, c_sext(local_c, 32, 64), 64), 8)
        v_478 = c_load(MEM, c_add(param_1, c_sext(local_c, 32, 64), 64), 8)
        if c_ne(v_425, v_478, 8):
            return c_return_bits(0, 64)
        local_c = c_add(local_c, 1, 32)
    v_241 = c_load(MEM, c_add(param_0, c_sext(local_c, 32, 64), 64), 8)
    if not c_eq(v_241, 0, 8):
        v_842 = 0
    else:
        v_322 = c_load(MEM, c_add(param_1, c_sext(local_c, 32, 64), 64), 8)
        if not c_eq(v_322, 0, 8):
            v_842 = 0
        else:
            v_842 = 1
    return c_return_bits(v_842, 64)
