# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_arm
# Entry address: 0x101e64
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_and, c_eq, c_load, c_ptradd, c_return_bits, c_slt, c_store, c_xor

def command_arm(param_0):
    abi_context = c_abi_context('function_entry:1056356')
    v_2739 = 1
    v_60 = c_load(MEM, param_0, 32)
    if c_eq(v_60, 1, 32):
        v_143 = c_ptradd(param_0, 6, 4, 64)
        v_146 = c_load(MEM, v_143, 32)
        v_169 = c_ptradd(param_0, 6, 4, 64)
        c_store(MEM, v_169, c_add(v_146, 1, 32), 32)
        c_abi_call(abi_context, 'puts', (0x10367a,), plan_id='call_site:1056417:(ram, 0x101ebc, 72, 6):6')
        v_197 = c_ptradd(param_0, 1, 4, 64)
        v_200 = c_load(MEM, v_197, 32)
        if c_slt(v_200, 100, 32):
            c_abi_call(abi_context, 'puts', (0x103698,), plan_id='call_site:1056475:(ram, 0x101ee5, 116, 1):1')
            v_2739 = 0
        else:
            v_251 = c_ptradd(param_0, 1, 4, 64)
            v_254 = c_load(MEM, v_251, 32)
            if not c_slt(500, v_254, 32):
                c_abi_call(abi_context, 'puts', (0x1036b7,), plan_id='call_site:1056499:(ram, 0x101efd, 338, 1):1')
            else:
                c_abi_call(abi_context, 'puts', (0x103698,), plan_id='call_site:1056475:(ram, 0x101ee5, 116, 1):1')
                v_2739 = 0
        v_324 = c_ptradd(param_0, 3, 4, 64)
        v_327 = c_load(MEM, v_324, 32)
        if c_slt(v_327, 1, 32):
            c_abi_call(abi_context, 'puts', (0x1036d8,), plan_id='call_site:1056537:(ram, 0x101f23, 164, 1):1')
            v_2739 = 0
        else:
            v_374 = c_ptradd(param_0, 3, 4, 64)
            v_377 = c_load(MEM, v_374, 32)
            if not c_slt(4, v_377, 32):
                c_abi_call(abi_context, 'puts', (0x1036f7,), plan_id='call_site:1056561:(ram, 0x101f3b, 333, 1):1')
            else:
                c_abi_call(abi_context, 'puts', (0x1036d8,), plan_id='call_site:1056537:(ram, 0x101f23, 164, 1):1')
                v_2739 = 0
        c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1056576:(ram, 0x101f47, 175, 1):1')
        v_467 = c_ptradd(param_0, 4, 4, 64)
        v_470 = c_load(MEM, v_467, 32)
        v_485 = c_ptradd(param_0, 1, 4, 64)
        v_488 = c_load(MEM, v_485, 32)
        v_529 = c_ptradd(param_0, 3, 4, 64)
        v_532 = c_load(MEM, v_529, 32)
        if c_eq(c_and(c_xor(c_add(v_532, 1, 32), c_xor(v_470, v_488, 32), 32), 1, 32), 0, 32):
            c_abi_call(abi_context, 'puts', (0x103737,), plan_id='call_site:1056647:(ram, 0x101f91, 328, 1):1')
        else:
            c_abi_call(abi_context, 'puts', (0x103718,), plan_id='call_site:1056623:(ram, 0x101f79, 251, 1):1')
            v_2739 = 0
        v_674 = c_ptradd(param_0, 5, 4, 64)
        v_677 = c_load(MEM, v_674, 32)
        if c_eq(v_677, 0, 32):
            c_abi_call(abi_context, 'puts', (0x103780,), plan_id='call_site:1056697:(ram, 0x101fc3, 323, 1):1')
        else:
            c_abi_call(abi_context, 'puts', (0x103758,), plan_id='call_site:1056673:(ram, 0x101fab, 277, 1):1')
            v_2739 = 0
        if v_2739:
            c_store(MEM, param_0, 2, 32)
            c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1056735:(ram, 0x101ff0, 313, 1):1')
            c_abi_call(abi_context, 'puts', (0x1037af,), plan_id='call_site:1056735:(ram, 0x101fff, 318, 3):3')
        else:
            c_abi_call(abi_context, 'puts', (0x1037a0,), plan_id='call_site:1056718:(ram, 0x101fd8, 300, 1):1')
    else:
        c_abi_call(abi_context, 'record_fault', (param_0, 0x103640), plan_id='call_site:1056390:(ram, 0x101e97, 44, 1):1')
    return c_return_bits(0, 64)
