# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::read_command
# Entry address: 0x1018bc
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ptrsub, c_return_bits, c_slt, c_store

def read_command(param_0):
    abi_context = c_abi_context('function_entry:1054908')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    local_10 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    v_88 = c_ptrsub(abi_stack_pointer, -0x78, 64)
    v_394 = c_bits(c_abi_call(abi_context, 'fgets', (v_88, 0x60, c_load(MEM, 0x106010, 64)), plan_id='call_site:1054912:(ram, 0x1018f4, 39, 7):7'), 64)
    if not c_eq(v_394, 0, 64):
        v_229 = c_ptrsub(abi_stack_pointer, -0x78, 64)
        v_899 = c_bits(c_abi_call(abi_context, 'parse_command', (v_229, param_0), plan_id='call_site:1054996:(ram, 0x101925, 95, 4):4'), 32)
        if not c_eq(v_899, 0, 32):
            if not c_slt(v_899, 0, 32):
                v_684 = abi_tls_base
                v_1149 = v_899
            else:
                c_abi_call(abi_context, 'puts', (0x1032fd,), plan_id='call_site:1055050:(ram, 0x101954, 141, 4):4')
                v_1149 = v_899
        else:
            c_abi_call(abi_context, 'puts', (0x1032ef,), plan_id='call_site:1055027:(ram, 0x10193d, 117, 4):4')
            v_1149 = v_899
    else:
        c_abi_call(abi_context, 'puts', (0x1032e1,), plan_id='call_site:1054974:(ram, 0x101908, 55, 4):4')
        v_1149 = 0
    v_171 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    if c_eq(c_load(MEM, c_ptrsub(abi_stack_pointer, -16, 64), 64), v_171, 64):
        return c_return_bits(v_1149, 32)
    else:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1055083:(ram, 0x10196b, 77, 2):2')
