# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::dispatch_command
# Entry address: 0x1024df
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_ne, c_ptrsub, c_return_bits

def dispatch_command(param_0, param_1):
    abi_context = c_abi_context('function_entry:1058015')
    v_2914 = c_ptrsub(0, 0x103b70, 64)
    v_2210 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, v_2914), plan_id='call_site:1058019:(ram, 0x102504, 27, 1):1'), 32)
    if c_eq(v_2210, 0, 32):
        v_2221 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, 0x103b75), plan_id='call_site:1058071:(ram, 0x102528, 57, 1):1'), 32)
        if c_eq(v_2221, 0, 32):
            v_2920 = c_ptrsub(0, 0x103b7c, 64)
            v_2232 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, v_2920), plan_id='call_site:1058114:(ram, 0x102553, 84, 1):1'), 32)
            if c_eq(v_2232, 0, 32):
                v_2243 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, 0x103b81), plan_id='call_site:1058157:(ram, 0x10257e, 111, 1):1'), 32)
                if c_eq(v_2243, 0, 32):
                    v_2926 = c_ptrsub(0, 0x103b87, 64)
                    v_2254 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, v_2926), plan_id='call_site:1058200:(ram, 0x1025a9, 138, 1):1'), 32)
                    if c_eq(v_2254, 0, 32):
                        v_2265 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, 0x103b8c), plan_id='call_site:1058250:(ram, 0x1025db, 169, 1):1'), 32)
                        if c_eq(v_2265, 0, 32):
                            v_2932 = c_ptrsub(0, 0x103b92, 64)
                            v_2276 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, v_2932), plan_id='call_site:1058300:(ram, 0x10260d, 200, 1):1'), 32)
                            if c_eq(v_2276, 0, 32):
                                v_2287 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, 0x103b96), plan_id='call_site:1058343:(ram, 0x102638, 227, 1):1'), 32)
                                if c_eq(v_2287, 0, 32):
                                    v_2938 = c_ptrsub(0, 0x103b9c, 64)
                                    v_2298 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, v_2938), plan_id='call_site:1058393:(ram, 0x10266a, 258, 1):1'), 32)
                                    if c_eq(v_2298, 0, 32):
                                        v_2309 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, 0x103ba1), plan_id='call_site:1058433:(ram, 0x102692, 285, 1):1'), 32)
                                        if c_eq(v_2309, 0, 32):
                                            v_2944 = c_ptrsub(0, 0x103ba8, 64)
                                            v_2320 = c_bits(c_abi_call(abi_context, 'text_equal', (param_1, v_2944), plan_id='call_site:1058473:(ram, 0x1026ba, 312, 1):1'), 32)
                                            if not c_ne(v_2320, 0, 32):
                                                c_abi_call(abi_context, 'record_fault', (param_0, 0x103bad), plan_id='call_site:1058506:(ram, 0x1026db, 333, 1):1')
                                                return c_return_bits(1, 64)
                                            else:
                                                return c_return_bits(0, 64)
                                        else:
                                            c_abi_call(abi_context, 'command_commit', (param_0,), plan_id='call_site:1058459:(ram, 0x1026a2, 302, 0):0')
                                            return c_return_bits(1, 64)
                                    else:
                                        c_abi_call(abi_context, 'command_cool', (param_0,), plan_id='call_site:1058419:(ram, 0x10267a, 275, 0):0')
                                        return c_return_bits(1, 64)
                                else:
                                    c_abi_call(abi_context, 'command_pulse', (param_0, param_1), plan_id='call_site:1058369:(ram, 0x10264f, 248, 0):0')
                                    return c_return_bits(1, 64)
                            else:
                                c_abi_call(abi_context, 'command_arm', (param_0,), plan_id='call_site:1058326:(ram, 0x10261d, 217, 0):0')
                                return c_return_bits(1, 64)
                        else:
                            c_abi_call(abi_context, 'command_route', (param_0, param_1), plan_id='call_site:1058276:(ram, 0x1025f2, 190, 0):0')
                            return c_return_bits(1, 64)
                    else:
                        c_abi_call(abi_context, 'command_load', (param_0, param_1), plan_id='call_site:1058226:(ram, 0x1025c0, 159, 0):0')
                        return c_return_bits(1, 64)
                else:
                    c_abi_call(abi_context, 'command_clear', (param_0,), plan_id='call_site:1058183:(ram, 0x10258e, 128, 0):0')
                    return c_return_bits(1, 64)
            else:
                c_abi_call(abi_context, 'command_boot', (param_0,), plan_id='call_site:1058140:(ram, 0x102563, 101, 0):0')
                return c_return_bits(1, 64)
        else:
            c_abi_call(abi_context, 'print_status', (param_0,), plan_id='call_site:1058097:(ram, 0x102538, 74, 0):0')
            return c_return_bits(1, 64)
    else:
        c_abi_call(abi_context, 'print_help', (), plan_id='call_site:1058061:(ram, 0x10250d, 40, 0):0')
        return c_return_bits(1, 64)
