# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::main
# Entry address: 0x10121c
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptrsub, c_return_bits, c_store, c_sub, c_zext

def main():
    abi_context = c_abi_context('function_entry:1053212')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    local_10 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    local_5c = 0x64
    c_abi_call(abi_context, 'puts', (0x102010,), plan_id='call_site:1053216:(ram, 0x101248, 36, 8):8')
    c_abi_call(abi_context, 'puts', (0x102048,), plan_id='call_site:1053216:(ram, 0x101257, 41, 13):13')
    c_abi_call(abi_context, 'puts', (0x102010,), plan_id='call_site:1053216:(ram, 0x101266, 46, 18):18')
    c_abi_call(abi_context, 'puts', (0x102080,), plan_id='call_site:1053216:(ram, 0x101275, 51, 23):23')
    c_abi_call(abi_context, 'puts', (0x1020a8,), plan_id='call_site:1053216:(ram, 0x101284, 56, 28):28')
    c_abi_call(abi_context, 'puts', (0x1020e8,), plan_id='call_site:1053216:(ram, 0x101293, 61, 33):33')
    c_abi_call(abi_context, 'puts', (0x102140,), plan_id='call_site:1053216:(ram, 0x1012a2, 66, 38):38')
    c_abi_call(abi_context, 'puts', (0x102198,), plan_id='call_site:1053216:(ram, 0x1012b1, 71, 43):43')
    c_abi_call(abi_context, 'printf', (0x1021e0,), plan_id='call_site:1053216:(ram, 0x1012c5, 77, 48):48')
    v_198 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    c_abi_call(abi_context, 'fgets', (v_198, 0x40, c_load(MEM, 0x104010, 64)), plan_id='call_site:1053216:(ram, 0x1012dd, 85, 53):53')
    v_215 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    c_abi_call(abi_context, 'clean_input', (v_215,), plan_id='call_site:1053216:(ram, 0x1012e9, 91, 58):58')
    v_230 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    v_1201 = c_bits(c_abi_call(abi_context, 'strcmp', (v_230, 0x10220a), plan_id='call_site:1053216:(ram, 0x1012ff, 99, 64):64'), 32)
    if not c_eq(v_1201, 0, 32):
        c_abi_call(abi_context, 'puts', (0x102290,), plan_id='call_site:1053480:(ram, 0x101332, 369, 4):4')
        c_abi_call(abi_context, 'puts', (0x1022d8,), plan_id='call_site:1053480:(ram, 0x101341, 374, 9):9')
        local_5c = 0x41
    else:
        c_abi_call(abi_context, 'puts', (0x102218,), plan_id='call_site:1053448:(ram, 0x101312, 115, 4):4')
        c_abi_call(abi_context, 'puts', (0x102250,), plan_id='call_site:1053448:(ram, 0x101321, 120, 9):9')
    c_abi_call(abi_context, 'puts', (0x102320,), plan_id='call_site:1053514:(ram, 0x101354, 126, 8):8')
    c_abi_call(abi_context, 'puts', (0x102370,), plan_id='call_site:1053514:(ram, 0x101363, 131, 13):13')
    c_abi_call(abi_context, 'puts', (0x1023a8,), plan_id='call_site:1053514:(ram, 0x101372, 136, 18):18')
    c_abi_call(abi_context, 'printf', (0x1023f8,), plan_id='call_site:1053514:(ram, 0x101386, 142, 23):23')
    v_354 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    c_abi_call(abi_context, 'fgets', (v_354, 0x40, c_load(MEM, 0x104010, 64)), plan_id='call_site:1053514:(ram, 0x10139e, 150, 28):28')
    v_371 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    c_abi_call(abi_context, 'clean_input', (v_371,), plan_id='call_site:1053514:(ram, 0x1013aa, 156, 33):33')
    v_386 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    v_1279 = c_bits(c_abi_call(abi_context, 'strcmp', (v_386, 0x10220a), plan_id='call_site:1053514:(ram, 0x1013c0, 164, 39):39'), 32)
    if not c_eq(v_1279, 0, 32):
        c_abi_call(abi_context, 'puts', (0x1024b8,), plan_id='call_site:1053673:(ram, 0x1013f3, 342, 4):4')
        c_abi_call(abi_context, 'puts', (0x102500,), plan_id='call_site:1053673:(ram, 0x101402, 347, 9):9')
        local_5c = c_sub(local_5c, 0x2d, 32)
    else:
        c_abi_call(abi_context, 'puts', (0x102428,), plan_id='call_site:1053641:(ram, 0x1013d3, 180, 4):4')
        c_abi_call(abi_context, 'puts', (0x102468,), plan_id='call_site:1053641:(ram, 0x1013e2, 185, 9):9')
    c_abi_call(abi_context, 'puts', (0x102548,), plan_id='call_site:1053707:(ram, 0x101415, 191, 8):8')
    c_abi_call(abi_context, 'puts', (0x1025a0,), plan_id='call_site:1053707:(ram, 0x101424, 196, 13):13')
    c_abi_call(abi_context, 'puts', (0x1025f8,), plan_id='call_site:1053707:(ram, 0x101433, 201, 18):18')
    c_abi_call(abi_context, 'printf', (0x102648,), plan_id='call_site:1053707:(ram, 0x101447, 207, 23):23')
    v_510 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    c_abi_call(abi_context, 'fgets', (v_510, 0x40, c_load(MEM, 0x104010, 64)), plan_id='call_site:1053707:(ram, 0x10145f, 215, 28):28')
    v_527 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    c_abi_call(abi_context, 'clean_input', (v_527,), plan_id='call_site:1053707:(ram, 0x10146b, 221, 33):33')
    v_542 = c_ptrsub(abi_stack_pointer, -0x58, 64)
    v_1357 = c_bits(c_abi_call(abi_context, 'strcmp', (v_542, 0x10220a), plan_id='call_site:1053707:(ram, 0x101481, 229, 39):39'), 32)
    if not c_eq(v_1357, 0, 32):
        c_abi_call(abi_context, 'puts', (0x102678,), plan_id='call_site:1053951:(ram, 0x101509, 317, 4):4')
        c_abi_call(abi_context, 'puts', (0x1027e0,), plan_id='call_site:1053951:(ram, 0x101518, 322, 9):9')
        c_abi_call(abi_context, 'puts', (0x102010,), plan_id='call_site:1053951:(ram, 0x101527, 327, 14):14')
        c_abi_call(abi_context, 'puts', (0x102818,), plan_id='call_site:1053951:(ram, 0x101536, 332, 19):19')
        c_abi_call(abi_context, 'puts', (0x102860,), plan_id='call_site:1053951:(ram, 0x101545, 337, 24):24')
    else:
        c_abi_call(abi_context, 'puts', (0x102678,), plan_id='call_site:1053834:(ram, 0x101494, 245, 4):4')
        c_abi_call(abi_context, 'puts', (0x1026b0,), plan_id='call_site:1053834:(ram, 0x1014a3, 250, 9):9')
        c_abi_call(abi_context, 'puts', (0x102010,), plan_id='call_site:1053834:(ram, 0x1014b2, 255, 14):14')
        c_abi_call(abi_context, 'puts', (0x1026e8,), plan_id='call_site:1053834:(ram, 0x1014c1, 260, 19):19')
        c_abi_call(abi_context, 'puts', (0x102728,), plan_id='call_site:1053834:(ram, 0x1014d0, 265, 24):24')
        c_abi_call(abi_context, 'puts', (0x102758,), plan_id='call_site:1053834:(ram, 0x1014df, 270, 29):29')
        c_abi_call(abi_context, 'printf', (0x1027b0, c_zext(local_5c, 32, 64)), plan_id='call_site:1053834:(ram, 0x1014f8, 282, 35):35')
    v_715 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 64) == v_715:
        return c_return_bits(0, 64)
    else:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1054046:(ram, 0x10155e, 304, 2):2')
