# Generated by PALExecInterface.
# Minimal sparse byte-addressable memory for clear-case execution.

from __future__ import annotations

from collections.abc import MutableMapping


class PALMemory(MutableMapping):
    def __init__(self, initial=None, *, allocation_base=0x700000000000):
        self._bytes = {}
        self._next_allocation = int(allocation_base)
        if initial:
            for address, value in dict(initial).items():
                self[int(address)] = int(value)

    def __getitem__(self, address):
        return self._bytes.get(int(address), 0)

    def __setitem__(self, address, value):
        self._bytes[int(address)] = int(value) & 0xff

    def __delitem__(self, address):
        del self._bytes[int(address)]

    def __iter__(self):
        return iter(self._bytes)

    def __len__(self):
        return len(self._bytes)

    def get(self, address, default=0):
        return self._bytes.get(int(address), default)

    # PALhelpers memory protocol.  MutableMapping compatibility alone is not
    # sufficient because PALhelpers deliberately accepts only bytearray, an
    # actual dict, or an object exposing load_byte/store_byte.
    def load_byte(self, address):
        return self._bytes.get(int(address), 0) & 0xff

    def store_byte(self, address, value):
        byte_value = int(value) & 0xff
        self._bytes[int(address)] = byte_value
        return byte_value

    # Compatibility aliases for runtime components using read/write wording.
    read_byte = load_byte
    write_byte = store_byte

    def load(self, address, width_bits):
        width_bits = int(width_bits)
        if width_bits <= 0 or width_bits % 8:
            raise ValueError("memory load width must be whole bytes")
        value = 0
        for index in range(width_bits // 8):
            value |= (self[int(address) + index] & 0xff) << (index * 8)
        return value

    def store(self, address, value, width_bits):
        width_bits = int(width_bits)
        if width_bits <= 0 or width_bits % 8:
            raise ValueError("memory store width must be whole bytes")
        raw = int(value)
        for index in range(width_bits // 8):
            self[int(address) + index] = raw >> (index * 8)
        return raw & ((1 << width_bits) - 1)

    read_int = load
    write_int = store

    def map_bytes(self, address, data):
        raw = bytes(data)
        for index, value in enumerate(raw):
            self[int(address) + index] = value
        return int(address)

    def read_bytes(self, address, size):
        return bytes(self[int(address) + index] for index in range(int(size)))

    def read_c_string(self, address, *, limit=65536, encoding="utf-8"):
        data = bytearray()
        for index in range(int(limit)):
            value = self[int(address) + index]
            if value == 0:
                break
            data.append(value)
        return bytes(data).decode(encoding, errors="replace")

    def allocate(self, size, *, alignment=16, zero=True):
        size = max(int(size), 1)
        alignment = max(int(alignment), 1)
        address = (self._next_allocation + alignment - 1) & -alignment
        self._next_allocation = address + size
        if zero:
            for index in range(size):
                self[address + index] = 0
        return address

    def allocate_c_string(self, text, *, encoding="utf-8"):
        raw = str(text).encode(encoding) + b"\0"
        address = self.allocate(len(raw), alignment=1, zero=False)
        self.map_bytes(address, raw)
        return address
