# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::PALexec
# Entry address: 0x101129
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_and, c_ashr, c_eq, c_lshr, c_ne, c_not, c_or, c_return_bits, c_sdiv, c_sext, c_shl, c_slt, c_srem, c_subpiece, c_ult, c_xor, c_zext

def PALexec(param_0, param_1, param_2):
    local_22 = c_subpiece(param_0, 0, 32, 8)
    local_21 = c_subpiece(param_1, 0, 32, 8)
    local_1e = c_subpiece(param_0, 0, 32, 16)
    local_1c = 0x12345678
    local_18 = 0x80000000
    local_14 = 0
    local_20 = param_2
    while not c_slt(2, local_14, 32):
        if c_ult(param_0, param_1, 32) and c_slt(local_21, local_22, 8) or c_slt(param_2, 0, 16):
            local_1c = c_add(param_1, c_xor(local_1c, 0x5f5f5f5f, 32), 32)
            v_4149 = local_18
        else:
            v_4149 = param_0
            if not c_ne(local_18, 0, 32):
                pass
            else:
                v_4149 = c_sdiv(local_18, param_1, 32)
        local_18 = v_4149
        local_10 = 0
        while c_slt(c_add(local_10, 1, 32), 3, 32):
            local_10 = c_add(local_10, 1, 32)
            local_21 = c_ashr(local_21, 2, 8)
            local_22 = c_lshr(local_22, 2, 8)
            local_20 = c_shl(local_20, 5, 16)
            if not c_ne(c_and(local_20, 61440, 16), 0, 16):
                pass
            else:
                local_1c = c_or(local_1c, c_xor(c_sext(local_21, 8, 32), c_zext(local_22, 8, 32), 32), 32)
        v_1443 = c_and(local_1c, 3, 32)
        if c_eq(c_and(local_1c, 3, 32), 2, 32):
            local_18 = c_srem(local_18, c_sext(c_or(local_1e, 1, 16), 16, 32), 32)
            local_14 = c_add(local_14, 1, 32)
        else:
            if not c_ult(c_and(local_1c, 3, 32), 3, 32):
                local_1c = c_not(local_1c, 32)
                local_14 = c_add(local_14, 1, 32)
            else:
                if c_eq(c_and(local_1c, 3, 32), 0, 32):
                    local_1e = c_add(param_2, local_1e, 16)
                    local_20 = c_xor(local_20, 0xaaaa, 16)
                    local_14 = c_add(local_14, 1, 32)
                else:
                    if not c_ne(c_and(local_1c, 3, 32), 1, 32):
                        local_20 = c_xor(local_20, 0xaaaa, 16)
                        local_14 = c_add(local_14, 1, 32)
                    else:
                        local_1c = c_not(local_1c, 32)
                        local_14 = c_add(local_14, 1, 32)
    return c_return_bits(c_add(c_or(c_zext(local_20, 16, 32), c_or(c_shl(c_zext(local_22, 8, 32), 0x18, 32), c_shl(c_sext(local_21, 8, 32), 0x10, 32), 32), 32), c_xor(local_18, local_1c, 32), 32), 32)
