# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::_ITM_registerTMCloneTable
# Entry address: 0x105018
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def _ITM_registerTMCloneTable():
    return c_return_bits(1, 32)
