# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::deregister_tm_clones
# Entry address: 0x101070
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def deregister_tm_clones():
    return c_return_bits(0, 64)
