# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::check_bit
# Entry address: 0x10117e
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_context, c_abi_return
from PALhelpers import c_and, c_ashr, c_return_bits, c_subpiece

def check_bit(param_1, param_0):
    abi_context = c_abi_context('function_entry:1053054')
    return c_abi_return(abi_context, c_and(c_ashr(param_1, c_and(c_subpiece(param_0, 0, 32, 8), 0x1f, 8), 32), 1, 32), 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1053054')
