# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::main
# Entry address: 0x10119d
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_add, c_and, c_ashr, c_bits, c_eq, c_ne, c_return_bits, c_shl, c_slt, c_srem, c_subpiece, c_xor, c_zext

def main():
    abi_context = c_abi_context('function_entry:1053085')
    local_2c = 0x64
    local_28 = 0
    local_24 = 0
    while not c_slt(4, local_24, 32):
        v_2683 = c_bits(c_abi_call(abi_context, 'transform_a', (c_add(local_2c, local_24, 32),), plan_id='call_site:1053130:(ram, 0x1011d4, 92, 1):1'), 32)
        if c_eq(c_and(v_2683, 1, 32), 0, 32) or (c_slt(1, local_24, 32) and c_slt(v_2683, 500, 32)):
            local_20 = 0
            while c_slt(local_20, 3, 32):
                v_2704 = c_bits(c_abi_call(abi_context, 'transform_b', (c_add(local_24, local_20, 32),), plan_id='call_site:1053193:(ram, 0x101213, 468, 1):1'), 32)
                v_1460 = c_srem(v_2704, 4, 32)
                if c_eq(c_srem(v_2704, 4, 32), 2, 32):
                    if c_slt(local_2c, 201, 32):
                        local_2c = c_add(local_2c, 0x32, 32)
                        local_20 = c_add(local_20, 1, 32)
                    else:
                        local_2c = c_add(local_2c, 0xffffffec, 32)
                        local_20 = c_add(local_20, 1, 32)
                else:
                    if not c_slt(c_srem(v_2704, 4, 32), 3, 32):
                        local_2c = c_shl(local_2c, 1, 32)
                        local_20 = c_add(local_20, 1, 32)
                    else:
                        if c_eq(c_srem(v_2704, 4, 32), 0, 32):
                            local_2c = c_add(local_2c, c_xor(v_2704, 0x12, 32), 32)
                            local_20 = c_add(local_20, 1, 32)
                        else:
                            if not c_ne(c_srem(v_2704, 4, 32), 1, 32):
                                v_2712 = c_bits(c_abi_call(abi_context, 'check_bit', (local_2c, 3), plan_id='call_site:1053257:(ram, 0x101253, 638, 0):0'), 32)
                                if c_eq(v_2712, 0, 32):
                                    local_2c = c_bits(c_abi_call(abi_context, 'transform_a', (local_2c,), plan_id='call_site:1053282:(ram, 0x101267, 675, 0):0'), 32)
                                    local_20 = c_add(local_20, 1, 32)
                                else:
                                    local_2c = c_add(local_2c, 0xfffffffb, 32)
                                    local_20 = c_add(local_20, 1, 32)
                            else:
                                local_2c = c_shl(local_2c, 1, 32)
                                local_20 = c_add(local_20, 1, 32)
        else:
            if not c_eq(c_and(local_24, 1, 32), 0, 32):
                v_5848 = c_bits(c_abi_call(abi_context, 'transform_a', (local_24,), plan_id='call_site:1053367:(ram, 0x1012bc, 981, 0):0'), 32)
            else:
                v_5848 = c_bits(c_abi_call(abi_context, 'transform_b', (local_2c,), plan_id='call_site:1053355:(ram, 0x1012b0, 793, 0):0'), 32)
            local_1c = 0
            while c_slt(local_1c, 2, 32):
                if c_eq(c_and(c_ashr(v_5848, c_and(c_subpiece(local_1c, 0, 32, 8), 31, 8), 32), 1, 32), 0, 32):
                    local_2c = c_add(local_2c, c_ashr(v_5848, 2, 32), 32)
                    local_1c = c_add(local_1c, 1, 32)
                else:
                    local_2c = c_xor(local_2c, 0xff, 32)
                    local_1c = c_add(local_1c, 1, 32)
        v_1041 = c_srem(c_add(local_28, local_2c, 32), 0xa, 32)
        if not c_eq(c_srem(c_add(local_28, local_2c, 32), 10, 32), 7, 32):
            local_24 = c_add(local_24, 1, 32)
            local_28 = c_srem(c_add(local_28, local_2c, 32), 0xa, 32)
        else:
            local_2c = c_add(local_2c, 0xffffff9c, 32)
            local_24 = c_add(local_24, 1, 32)
            local_28 = c_srem(c_add(local_28, local_2c, 32), 0xa, 32)
    c_abi_call(abi_context, 'printf', (0x102004, c_zext(local_28, 32, 64), c_zext(local_2c, 32, 64)), plan_id='call_site:1053514:(ram, 0x101361, 59, 5):5')
    return c_abi_return(abi_context, local_2c, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1053085')
