# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::craft_row_for_altitude
# Entry address: 0x1011b0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_return_bits, c_slt

def craft_row_for_altitude(param_0):
    if c_slt(param_0, 27, 32):
        if c_slt(param_0, 23, 32):
            if c_slt(param_0, 19, 32):
                if c_slt(param_0, 15, 32):
                    if c_slt(param_0, 11, 32):
                        if c_slt(param_0, 7, 32):
                            if c_slt(param_0, 3, 32):
                                v_437 = 7
                            else:
                                v_437 = 6
                        else:
                            v_437 = 5
                    else:
                        v_437 = 4
                else:
                    v_437 = 3
            else:
                v_437 = 2
        else:
            v_437 = 1
    else:
        v_437 = 0
    return c_return_bits(v_437, 64)
