# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::parse_burn
# Entry address: 0x1013bf
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_eq, c_load, c_return_bits, c_sext, c_slt, c_store

def parse_burn(param_0, param_1):
    c_store(MEM, param_1, 0, 32)
    v_47 = c_load(MEM, param_0, 8)
    if not c_eq(v_47, 113, 8):
        v_112 = c_load(MEM, param_0, 8)
        if not c_eq(v_112, 81, 8):
            v_160 = c_load(MEM, param_0, 8)
            if not c_slt(v_160, 48, 8):
                v_214 = c_load(MEM, param_0, 8)
                if c_slt(v_214, 58, 8):
                    v_266 = c_load(MEM, param_0, 8)
                    c_store(MEM, param_1, c_add(c_sext(v_266, 8, 32), 0xffffffd0, 32), 32)
                    v_450 = 1
                else:
                    v_450 = 0xffffffff
            else:
                v_450 = 0xffffffff
        else:
            v_450 = 0
    else:
        v_450 = 0
    return c_return_bits(v_450, 64)
