# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::draw_lander
# Entry address: 0x101252
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_bits, c_load, c_ptradd, c_return_bits, c_slt, c_zext

def draw_lander(param_0):
    abi_context = c_abi_context('function_entry:1053266')
    v_52 = c_load(MEM, param_0, 32)
    v_1878 = c_bits(c_abi_call(abi_context, 'craft_row_for_altitude', (v_52,), plan_id='call_site:1053266:(ram, 0x101266, 26, 1):1'), 32)
    c_abi_call(abi_context, 'puts', (0x102048,), plan_id='call_site:1053266:(ram, 0x101278, 34, 3):3')
    c_abi_call(abi_context, 'puts', (0x102088,), plan_id='call_site:1053266:(ram, 0x101287, 39, 5):5')
    c_abi_call(abi_context, 'puts', (0x1020b0,), plan_id='call_site:1053266:(ram, 0x101296, 44, 7):7')
    c_abi_call(abi_context, 'puts', (0x102048,), plan_id='call_site:1053266:(ram, 0x1012a5, 49, 9):9')
    v_135 = c_ptradd(param_0, 2, 4, 64)
    v_138 = c_load(MEM, v_135, 32)
    v_153 = c_ptradd(param_0, 1, 4, 64)
    v_156 = c_load(MEM, v_153, 32)
    v_171 = c_load(MEM, param_0, 32)
    v_186 = c_ptradd(param_0, 3, 4, 64)
    v_189 = c_load(MEM, v_186, 32)
    c_abi_call(abi_context, 'printf', (0x1020e0, c_zext(v_189, 32, 64), c_zext(v_171, 32, 64), c_zext(v_156, 32, 64), c_zext(v_138, 32, 64)), plan_id='call_site:1053266:(ram, 0x1012d9, 86, 22):22')
    c_abi_call(abi_context, 'puts', (0x102118,), plan_id='call_site:1053266:(ram, 0x1012e8, 91, 24):24')
    local_c = 0
    while c_slt(local_c, 8, 32):
        c_abi_call(abi_context, 'print_sky_row', (local_c, v_1878), plan_id='call_site:1053430:(ram, 0x101300, 219, 0):0')
        local_c = c_add(local_c, 1, 32)
        c_abi_call(abi_context, 'print_sky_row', (local_c, v_1878), plan_id='call_site:1053430:(ram, 0x101300, 219, 0):0')
        local_c = c_add(local_c, 1, 32)
    c_abi_call(abi_context, 'puts', (0x102158,), plan_id='call_site:1053455:(ram, 0x101319, 115, 1):1')
    c_abi_call(abi_context, 'puts', (0x102198,), plan_id='call_site:1053455:(ram, 0x101328, 120, 3):3')
    c_abi_call(abi_context, 'puts', (0x102118,), plan_id='call_site:1053455:(ram, 0x101337, 125, 5):5')
    v_325 = c_ptradd(param_0, 1, 4, 64)
    v_328 = c_load(MEM, v_325, 32)
    if c_slt(v_328, 4, 32):
        v_447 = c_ptradd(param_0, 1, 4, 64)
        v_450 = c_load(MEM, v_447, 32)
        if not c_slt(v_450, 4294967294, 32):
            c_abi_call(abi_context, 'puts', (0x1021f5,), plan_id='call_site:1053558:(ram, 0x101380, 204, 1):1')
        else:
            c_abi_call(abi_context, 'puts', (0x1021dd,), plan_id='call_site:1053541:(ram, 0x10136f, 198, 1):1')
    else:
        c_abi_call(abi_context, 'puts', (0x1021c8,), plan_id='call_site:1053512:(ram, 0x101352, 150, 1):1')
    c_abi_call(abi_context, 'printf', (0x102210, 2), plan_id='call_site:1053573:(ram, 0x101399, 158, 1):1')
    c_abi_call(abi_context, 'puts', (0x10223f,), plan_id='call_site:1053573:(ram, 0x1013a8, 163, 3):3')
    c_abi_call(abi_context, 'puts', (0x102257,), plan_id='call_site:1053573:(ram, 0x1013b7, 168, 5):5')
    return c_return_bits(0, 64)
