# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::main
# Entry address: 0x1016f0
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_bits, c_eq, c_load, c_ptrsub, c_return_bits, c_slt, c_store

def main():
    abi_context = c_abi_context('function_entry:1054448')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    v_36 = c_ptrsub(abi_stack_pointer, -0x38, 64)
    c_abi_call(abi_context, 'initialize_lander', (v_36,), plan_id='call_site:1054448:(ram, 0x1016ff, 18, 3):3')
    local_3c = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x3c, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x3c, 64), 32))[1])(0)
    local_c = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xc, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xc, 64), 32))[1])(1)
    local_10 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 32))[1])(1)
    while not c_eq(c_load(MEM, c_ptrsub(abi_stack_pointer, -12, 64), 32), 0, 32):
        v_159 = c_ptrsub(abi_stack_pointer, -0x38, 64)
        c_abi_call(abi_context, 'draw_lander', (v_159,), plan_id='call_site:1054491:(ram, 0x101722, 66, 6):6')
        v_174 = c_ptrsub(abi_stack_pointer, -0x3c, 64)
        local_10 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x10, 64), 32))[1])(c_bits(c_abi_call(abi_context, 'read_burn', (v_174,), plan_id='call_site:1054491:(ram, 0x10172e, 72, 13):13'), 32))
        if c_eq(c_load(MEM, c_ptrsub(abi_stack_pointer, -16, 64), 32), 0, 32):
            local_20 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x20, 64), 32))[1])(1)
            break
        if c_slt(4294967295, c_load(MEM, c_ptrsub(abi_stack_pointer, -16, 64), 32), 32):
            pass
        else:
            continue
        v_293 = c_ptrsub(abi_stack_pointer, -0x38, 64)
        c_abi_call(abi_context, 'apply_burn', (v_293, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x3c, 64), 32)), plan_id='call_site:1054541:(ram, 0x101759, 120, 6):6')
        local_c = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xc, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xc, 64), 32))[1])(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), 32))
    v_114 = c_ptrsub(abi_stack_pointer, -0x38, 64)
    c_abi_call(abi_context, 'print_result', (v_114,), plan_id='call_site:1054570:(ram, 0x101771, 48, 9):9')
    v_129 = c_ptrsub(abi_stack_pointer, -0x38, 64)
    c_abi_call(abi_context, 'lander_exit_code', (v_129,), plan_id='call_site:1054570:(ram, 0x10177d, 54, 15):15')
    return c_return_bits(0, 64)
