# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::print_sky_row
# Entry address: 0x101219
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_eq, c_return_bits

def print_sky_row(param_0, param_1):
    abi_context = c_abi_context('function_entry:1053209')
    if not c_eq(param_0, param_1, 32):
        c_abi_call(abi_context, 'puts', (0x102025,), plan_id='call_site:1053248:(ram, 0x10124a, 53, 1):1')
    else:
        c_abi_call(abi_context, 'puts', (0x102008,), plan_id='call_site:1053231:(ram, 0x101239, 41, 1):1')
    return c_return_bits(0, 64)
