# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::parse_integer
# Entry address: 0x101611
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_bits, c_eq, c_load, c_mul, c_ne, c_return_bits, c_sext, c_slt, c_store

def parse_integer(param_0, param_1):
    abi_context = c_abi_context('function_entry:1054225')
    local_1c = 0
    local_18 = 1
    local_14 = 0
    local_10 = 0
    while True:
        v_131 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        v_2776 = c_bits(c_abi_call(abi_context, 'is_space_char', (c_sext(v_131, 8, 32),), plan_id='call_site:1054279:(ram, 0x10165c, 58, 6):6'), 32)
        if not (c_ne(v_2776, 0, 32)):
            break
        local_1c = c_add(local_1c, 1, 32)
    v_228 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
    if not c_eq(v_228, 45, 8):
        v_1346 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        if not c_eq(v_1346, 43, 8):
            pass
        else:
            local_1c = c_add(local_1c, 1, 32)
    else:
        local_18 = 0xffffffff
        local_1c = c_add(local_1c, 1, 32)
    while True:
        v_370 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        if not (c_slt(47, v_370, 8)):
            break
        v_457 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        if not c_slt(v_457, 58, 8):
            break
        v_882 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        if c_slt(1000000, local_14, 32):
            return c_return_bits(0, 64)
        local_14 = c_add(c_add(c_sext(v_882, 8, 32), 0xffffffd0, 32), c_mul(local_14, 0xa, 32), 32)
        local_10 = c_add(local_10, 1, 32)
        local_1c = c_add(local_1c, 1, 32)
    while True:
        v_545 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        v_2882 = c_bits(c_abi_call(abi_context, 'is_space_char', (c_sext(v_545, 8, 32),), plan_id='call_site:1054488:(ram, 0x10172d, 213, 6):6'), 32)
        if not (c_ne(v_2882, 0, 32)):
            break
        local_1c = c_add(local_1c, 1, 32)
    if c_eq(local_10, 0, 32):
        v_2351 = 0
    else:
        v_678 = c_load(MEM, c_add(param_0, c_sext(local_1c, 32, 64), 64), 8)
        if not c_ne(v_678, 0, 8):
            c_store(MEM, param_1, c_mul(local_14, local_18, 32), 32)
            v_2351 = 1
        else:
            v_2351 = 0
    return c_return_bits(v_2351, 64)
