# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_boot
# Entry address: 0x101b3a
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_eq, c_load, c_ptradd, c_return_bits, c_store

def command_boot(param_0):
    abi_context = c_abi_context('function_entry:1055546')
    v_52 = c_load(MEM, param_0, 32)
    if c_eq(v_52, 0, 32):
        c_abi_call(abi_context, 'puts', (0x103382,), plan_id='call_site:1055599:(ram, 0x101b79, 52, 1):1')
        c_abi_call(abi_context, 'puts', (0x10339d,), plan_id='call_site:1055599:(ram, 0x101b88, 57, 3):3')
        c_abi_call(abi_context, 'puts', (0x1033ba,), plan_id='call_site:1055599:(ram, 0x101b97, 62, 5):5')
        c_abi_call(abi_context, 'puts', (0x1033d7,), plan_id='call_site:1055599:(ram, 0x101ba6, 67, 7):7')
        c_abi_call(abi_context, 'puts', (0x1033f4,), plan_id='call_site:1055599:(ram, 0x101bb5, 72, 9):9')
        c_store(MEM, param_0, 1, 32)
        v_204 = c_ptradd(param_0, 1, 4, 64)
        c_store(MEM, v_204, 0, 32)
        v_220 = c_ptradd(param_0, 2, 4, 64)
        c_store(MEM, v_220, 0, 32)
        v_236 = c_ptradd(param_0, 3, 4, 64)
        c_store(MEM, v_236, 0, 32)
        v_252 = c_ptradd(param_0, 7, 4, 64)
        c_store(MEM, v_252, 0, 32)
        c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1055599:(ram, 0x101bf7, 108, 19):19')
        c_abi_call(abi_context, 'puts', (0x103418,), plan_id='call_site:1055599:(ram, 0x101c06, 113, 21):21')
    else:
        c_abi_call(abi_context, 'record_fault', (param_0, 0x103358), plan_id='call_site:1055572:(ram, 0x101b65, 40, 1):1')
    return c_return_bits(0, 64)
