# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_clear
# Entry address: 0x101c0d
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_eq, c_load, c_ptradd, c_return_bits, c_store

def command_clear(param_0):
    abi_context = c_abi_context('function_entry:1055757')
    v_52 = c_load(MEM, param_0, 32)
    if c_eq(v_52, 1, 32):
        v_125 = c_ptradd(param_0, 5, 4, 64)
        v_128 = c_load(MEM, v_125, 32)
        if not c_eq(v_128, 0, 32):
            v_184 = c_ptradd(param_0, 5, 4, 64)
            c_store(MEM, v_184, 0, 32)
            c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1055829:(ram, 0x101c67, 81, 2):2')
            c_abi_call(abi_context, 'puts', (0x103495,), plan_id='call_site:1055829:(ram, 0x101c76, 86, 4):4')
        else:
            c_abi_call(abi_context, 'puts', (0x103477,), plan_id='call_site:1055812:(ram, 0x101c4e, 67, 1):1')
    else:
        c_abi_call(abi_context, 'puts', (0x103440,), plan_id='call_site:1055784:(ram, 0x101c32, 37, 1):1')
    return c_return_bits(0, 64)
