# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_load
# Entry address: 0x101c7d
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_eq, c_load, c_ptradd, c_return_bits, c_sdiv, c_slt, c_store, c_zext

def command_load(param_0, param_1):
    abi_context = c_abi_context('function_entry:1055869')
    v_60 = c_load(MEM, param_0, 32)
    if c_eq(v_60, 1, 32):
        v_146 = c_load(MEM, c_add(param_1, 0x10, 64), 32)
        if not c_eq(v_146, 0, 32):
            v_215 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
            if c_slt(v_215, 100, 32):
                c_abi_call(abi_context, 'record_fault', (param_0, 0x103520), plan_id='call_site:1055991:(ram, 0x101d08, 127, 1):1')
            else:
                v_269 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                if not c_slt(500, v_269, 32):
                    v_344 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                    v_359 = c_ptradd(param_0, 1, 4, 64)
                    c_store(MEM, v_359, v_344, 32)
                    v_378 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                    v_743 = c_ptradd(param_0, 2, 4, 64)
                    c_store(MEM, v_743, c_sdiv(v_378, 0x28, 32), 32)
                    c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1056015:(ram, 0x101d48, 288, 11):11')
                    v_777 = c_ptradd(param_0, 1, 4, 64)
                    v_780 = c_load(MEM, v_777, 32)
                    c_abi_call(abi_context, 'printf', (0x103558, c_zext(v_780, 32, 64)), plan_id='call_site:1056015:(ram, 0x101d65, 303, 17):17')
                    v_813 = c_ptradd(param_0, 4, 4, 64)
                    v_816 = c_load(MEM, v_813, 32)
                    c_abi_call(abi_context, 'printf', (0x103579, c_zext(v_816, 32, 64)), plan_id='call_site:1056015:(ram, 0x101d82, 318, 23):23')
                else:
                    c_abi_call(abi_context, 'record_fault', (param_0, 0x103520), plan_id='call_site:1055991:(ram, 0x101d08, 127, 1):1')
        else:
            c_abi_call(abi_context, 'record_fault', (param_0, 0x1034f0), plan_id='call_site:1055938:(ram, 0x101cd3, 78, 1):1')
    else:
        c_abi_call(abi_context, 'record_fault', (param_0, 0x1034b8), plan_id='call_site:1055900:(ram, 0x101cad, 44, 1):1')
    return c_return_bits(0, 64)
