# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::print_help
# Entry address: 0x1012ce
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_return_bits

def print_help():
    abi_context = c_abi_context('function_entry:1053390')
    c_abi_call(abi_context, 'putchar', (0xa,), plan_id='call_site:1053394:(ram, 0x1012db, 7, 0):0')
    c_abi_call(abi_context, 'puts', (0x10308c,), plan_id='call_site:1053394:(ram, 0x1012ea, 12, 2):2')
    c_abi_call(abi_context, 'puts', (0x103098,), plan_id='call_site:1053394:(ram, 0x1012f9, 17, 4):4')
    c_abi_call(abi_context, 'puts', (0x1030c0,), plan_id='call_site:1053394:(ram, 0x101308, 22, 6):6')
    c_abi_call(abi_context, 'puts', (0x1030e8,), plan_id='call_site:1053394:(ram, 0x101317, 27, 8):8')
    c_abi_call(abi_context, 'puts', (0x103118,), plan_id='call_site:1053394:(ram, 0x101326, 32, 10):10')
    c_abi_call(abi_context, 'puts', (0x103140,), plan_id='call_site:1053394:(ram, 0x101335, 37, 12):12')
    c_abi_call(abi_context, 'puts', (0x103170,), plan_id='call_site:1053394:(ram, 0x101344, 42, 14):14')
    c_abi_call(abi_context, 'puts', (0x1031a0,), plan_id='call_site:1053394:(ram, 0x101353, 47, 16):16')
    c_abi_call(abi_context, 'puts', (0x1031c8,), plan_id='call_site:1053394:(ram, 0x101362, 52, 18):18')
    c_abi_call(abi_context, 'puts', (0x1031f8,), plan_id='call_site:1053394:(ram, 0x101371, 57, 20):20')
    c_abi_call(abi_context, 'puts', (0x103230,), plan_id='call_site:1053394:(ram, 0x101380, 62, 22):22')
    c_abi_call(abi_context, 'putchar', (0xa,), plan_id='call_site:1053394:(ram, 0x10138a, 66, 23):23')
    return c_return_bits(0, 64)
