# Generated by PALExecInterface.
# Explicit modeled external boundaries. Unknown externals fail closed.

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


class PALUnimplementedShim(RuntimeError):
    pass


class PALProcessExit(SystemExit):
    pass


class PALPrintShims:
    def __init__(self, memory, stdin=None, stdout=None):
        self.memory = memory
        self.stdin = stdin if stdin is not None else sys.stdin
        self.stdout = stdout if stdout is not None else sys.stdout
        self._load_stdio_literals()

    def _load_stdio_literals(self):
        path = Path(__file__).resolve().parent.parent / "PAL_stdio_strings.json"
        if not path.is_file():
            return
        try:
            with open(path, "rt", encoding="utf-8") as handle:
                payload = json.load(handle)
            literals = payload.get("strings", payload)
            if not isinstance(literals, dict):
                return
            for raw_address, text in literals.items():
                address = int(str(raw_address), 0)
                data = str(text).encode("utf-8") + b"\0"
                self.memory.map_bytes(address, data)
        except Exception as exc:
            raise PALUnimplementedShim(
                "PAL stdio literal overlay failed: %s" % exc
            )

    def _write(self, text):
        self.stdout.write(str(text))
        self.stdout.flush()

    def _write_c_buffer(self, address, data, size):
        size = int(size)
        if size <= 0:
            return 0
        raw = bytes(data)[: max(size - 1, 0)]
        self.memory.map_bytes(int(address), raw + b"\0")
        return int(address)

    def _string(self, value):
        if isinstance(value, str):
            return value
        try:
            address = int(value)
        except (TypeError, ValueError):
            return str(value)
        try:
            text = self.memory.read_c_string(address)
        except Exception:
            text = ""
        return text if text else "<cstr@0x%x>" % address

    def _format(self, fmt, values):
        fmt = self._string(fmt)
        items = iter(values)
        out = []
        index = 0
        pattern = re.compile(r"%(?:[-+ #0]*)(?:\d+|\*)?(?:\.\d+|\.\*)?(?:hh|h|ll|l|j|z|t|L)?([diuoxXfFeEgGaAcsp%])")
        for match in pattern.finditer(fmt):
            out.append(fmt[index:match.start()])
            kind = match.group(1)
            token = match.group(0)
            if kind == "%":
                out.append("%")
                index = match.end()
                continue
            try:
                value = next(items)
            except StopIteration:
                out.append(token)
                index = match.end()
                continue
            try:
                if kind in "di":
                    rendered = str(int(value))
                elif kind == "u":
                    rendered = str(int(value) & ((1 << 64) - 1))
                elif kind in "xX":
                    rendered = format(int(value) & ((1 << 64) - 1), kind)
                elif kind == "o":
                    rendered = format(int(value) & ((1 << 64) - 1), "o")
                elif kind in "fFeEgGaA":
                    rendered = str(float(value))
                elif kind == "c":
                    rendered = chr(int(value) & 0xff)
                elif kind == "s":
                    rendered = self._string(value)
                elif kind == "p":
                    rendered = "0x%x" % int(value)
                else:
                    rendered = str(value)
            except Exception:
                rendered = str(value)
            out.append(rendered)
            index = match.end()
        out.append(fmt[index:])
        remaining = list(items)
        if remaining:
            out.append(" " + " ".join(str(value) for value in remaining))
        return "".join(out)

    def printf(self, fmt, *values):
        text = self._format(fmt, values)
        self._write(text)
        return len(text)

    def __printf_chk(self, flag, fmt, *values):
        return self.printf(fmt, *values)

    def fprintf(self, stream, fmt, *values):
        return self.printf(fmt, *values)

    def __fprintf_chk(self, stream, flag, fmt, *values):
        return self.printf(fmt, *values)

    def puts(self, value):
        text = self._string(value)
        self._write(text + "\n")
        return len(text) + 1

    def fputs(self, value, stream=None):
        text = self._string(value)
        self._write(text)
        return len(text)

    def putchar(self, value):
        char = chr(int(value) & 0xff)
        self._write(char)
        return int(value) & 0xff

    def fgets(self, destination, size, stream=None):
        self.stdout.flush()
        line = self.stdin.readline()
        if line == "":
            return 0
        return self._write_c_buffer(
            destination,
            line.encode("utf-8", errors="replace"),
            size,
        )

    def strcmp(self, left, right):
        left_text = self._string(left)
        right_text = self._string(right)
        if left_text == right_text:
            return 0
        return -1 if left_text < right_text else 1

    def strcspn(self, text, reject):
        text_value = self._string(text)
        reject_value = self._string(reject)
        # Bounded compatibility for clean_input(str, "\n") when the tiny
        # static reject literal is not yet present in the overlay.
        if reject_value.startswith("<cstr@"):
            reject_value = "\n"
        rejected = set(reject_value)
        for index, char in enumerate(text_value):
            if char in rejected:
                return index
        return len(text_value)

    def fputc(self, value, stream=None):
        return self.putchar(value)

    def exit(self, status=0):
        raise PALProcessExit(int(status))

    def abort(self, *unused):
        raise PALProcessExit(134)

    def stack_chk_fail(self, *unused):
        raise PALProcessExit("PAL __stack_chk_fail trap")

    def unresolved(self, name):
        def trap(*values):
            raise PALUnimplementedShim(
                "PAL external shim %r is not implemented; args=%r" % (name, values)
            )
        trap.__name__ = "pal_unimplemented_%s" % str(name).replace("-", "_")
        return trap

    def mapping(self, names=()):
        table = {
            "printf": self.printf,
            "__printf_chk": self.__printf_chk,
            "fprintf": self.fprintf,
            "__fprintf_chk": self.__fprintf_chk,
            "puts": self.puts,
            "fputs": self.fputs,
            "fputs_unlocked": self.fputs,
            "putchar": self.putchar,
            "fputc": self.fputc,
            "fputc_unlocked": self.fputc,
            "fgets": self.fgets,
            "strcmp": self.strcmp,
            "strcspn": self.strcspn,
            "exit": self.exit,
            "_exit": self.exit,
            "abort": self.abort,
            "__stack_chk_fail": self.stack_chk_fail,
        }
        for name in names:
            table.setdefault(str(name), self.unresolved(str(name)))
        return table
