# Generated by PAL batch_v1_function_modules_and_dispatch
# Deterministic function dispatch table.  Modules are loaded lazily.

import importlib
import json
import os

MANIFEST_PATH = 'PAL_function_manifest.json'
JUMP_TABLE_PATH = 'PAL_jump_table.json'
NAME_REGISTRY_PATH = 'PAL_ONCS.json'
FUNCTIONS = ({'active_name': 'f_init',
  'address': 1052672,
  'address_hex': '0x101000',
  'external': False,
  'function_id': 'function:0x101000',
  'generated_name': None,
  'module': 'functions.f_0000000000101000_init',
  'name': '_init',
  'operator_name': None,
  'python_symbol': '_init',
  'qualified_name': 'Global::_init',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_thyme',
  'address': 1052704,
  'address_hex': '0x101020',
  'external': False,
  'function_id': 'function:0x101020',
  'generated_name': 'f_thyme',
  'module': 'functions.f_0000000000101020_FUN_00101020',
  'name': 'FUN_00101020',
  'operator_name': None,
  'python_symbol': 'FUN_00101020',
  'qualified_name': 'Global::FUN_00101020',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_cxa_finalize',
  'address': 1052736,
  'address_hex': '0x101040',
  'external': False,
  'function_id': 'function:0x101040',
  'generated_name': None,
  'module': 'functions.f_0000000000101040_cxa_finalize',
  'name': '__cxa_finalize',
  'operator_name': None,
  'python_symbol': '__cxa_finalize',
  'qualified_name': '<EXTERNAL>::__cxa_finalize',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_stack_chk_fail',
  'address': 1052752,
  'address_hex': '0x101050',
  'external': False,
  'function_id': 'function:0x101050',
  'generated_name': None,
  'module': 'functions.f_0000000000101050_stack_chk_fail',
  'name': '__stack_chk_fail',
  'operator_name': None,
  'python_symbol': '__stack_chk_fail',
  'qualified_name': '<EXTERNAL>::__stack_chk_fail',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_start',
  'address': 1052768,
  'address_hex': '0x101060',
  'external': False,
  'function_id': 'function:0x101060',
  'generated_name': None,
  'module': 'functions.f_0000000000101060_start',
  'name': '_start',
  'operator_name': None,
  'python_symbol': '_start',
  'qualified_name': 'Global::_start',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_deregister_tm_clones',
  'address': 1052816,
  'address_hex': '0x101090',
  'external': False,
  'function_id': 'function:0x101090',
  'generated_name': None,
  'module': 'functions.f_0000000000101090_deregister_tm_clones',
  'name': 'deregister_tm_clones',
  'operator_name': None,
  'python_symbol': 'deregister_tm_clones',
  'qualified_name': 'Global::deregister_tm_clones',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_register_tm_clones',
  'address': 1052864,
  'address_hex': '0x1010c0',
  'external': False,
  'function_id': 'function:0x1010c0',
  'generated_name': None,
  'module': 'functions.f_00000000001010c0_register_tm_clones',
  'name': 'register_tm_clones',
  'operator_name': None,
  'python_symbol': 'register_tm_clones',
  'qualified_name': 'Global::register_tm_clones',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_do_global_dtors_aux',
  'address': 1052928,
  'address_hex': '0x101100',
  'external': False,
  'function_id': 'function:0x101100',
  'generated_name': None,
  'module': 'functions.f_0000000000101100_do_global_dtors_aux',
  'name': '__do_global_dtors_aux',
  'operator_name': None,
  'python_symbol': None,
  'qualified_name': 'Global::__do_global_dtors_aux',
  'status': 'failed',
  'thunk': False},
 {'active_name': 'f_frame_dummy',
  'address': 1052992,
  'address_hex': '0x101140',
  'external': False,
  'function_id': 'function:0x101140',
  'generated_name': None,
  'module': 'functions.f_0000000000101140_frame_dummy',
  'name': 'frame_dummy',
  'operator_name': None,
  'python_symbol': 'frame_dummy',
  'qualified_name': 'Global::frame_dummy',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_process_payload_block',
  'address': 1053001,
  'address_hex': '0x101149',
  'external': False,
  'function_id': 'function:0x101149',
  'generated_name': None,
  'module': 'functions.f_0000000000101149_process_payload_block',
  'name': 'process_payload_block',
  'operator_name': None,
  'python_symbol': 'process_payload_block',
  'qualified_name': 'Global::process_payload_block',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_main',
  'address': 1053156,
  'address_hex': '0x1011e4',
  'external': False,
  'function_id': 'function:0x1011e4',
  'generated_name': None,
  'module': 'functions.f_00000000001011e4_main',
  'name': 'main',
  'operator_name': None,
  'python_symbol': 'main',
  'qualified_name': 'Global::main',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_fini',
  'address': 1053256,
  'address_hex': '0x101248',
  'external': False,
  'function_id': 'function:0x101248',
  'generated_name': None,
  'module': 'functions.f_0000000000101248_fini',
  'name': '_fini',
  'operator_name': None,
  'python_symbol': '_fini',
  'qualified_name': 'Global::_fini',
  'status': 'decompiled',
  'thunk': False},
 {'active_name': 'f_libc_start_main',
  'address': 1069056,
  'address_hex': '0x105000',
  'external': False,
  'function_id': 'function:0x105000',
  'generated_name': None,
  'module': 'functions.f_0000000000105000_libc_start_main',
  'name': '__libc_start_main',
  'operator_name': None,
  'python_symbol': '__libc_start_main',
  'qualified_name': '<EXTERNAL>::__libc_start_main',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_ITM_deregisterTMCloneTable',
  'address': 1069064,
  'address_hex': '0x105008',
  'external': False,
  'function_id': 'function:0x105008',
  'generated_name': None,
  'module': 'functions.f_0000000000105008_ITM_deregisterTMCloneTable',
  'name': '_ITM_deregisterTMCloneTable',
  'operator_name': None,
  'python_symbol': '_ITM_deregisterTMCloneTable',
  'qualified_name': '<EXTERNAL>::_ITM_deregisterTMCloneTable',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_stack_chk_fail',
  'address': 1069072,
  'address_hex': '0x105010',
  'external': False,
  'function_id': 'function:0x105010',
  'generated_name': None,
  'module': 'functions.f_0000000000105010_stack_chk_fail',
  'name': '__stack_chk_fail',
  'operator_name': None,
  'python_symbol': '__stack_chk_fail',
  'qualified_name': '<EXTERNAL>::__stack_chk_fail',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_gmon_start',
  'address': 1069080,
  'address_hex': '0x105018',
  'external': False,
  'function_id': 'function:0x105018',
  'generated_name': None,
  'module': 'functions.f_0000000000105018_gmon_start',
  'name': '__gmon_start__',
  'operator_name': None,
  'python_symbol': '__gmon_start__',
  'qualified_name': '<EXTERNAL>::__gmon_start__',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_ITM_registerTMCloneTable',
  'address': 1069088,
  'address_hex': '0x105020',
  'external': False,
  'function_id': 'function:0x105020',
  'generated_name': None,
  'module': 'functions.f_0000000000105020_ITM_registerTMCloneTable',
  'name': '_ITM_registerTMCloneTable',
  'operator_name': None,
  'python_symbol': '_ITM_registerTMCloneTable',
  'qualified_name': '<EXTERNAL>::_ITM_registerTMCloneTable',
  'status': 'decompiled',
  'thunk': True},
 {'active_name': 'f_cxa_finalize',
  'address': 1069096,
  'address_hex': '0x105028',
  'external': False,
  'function_id': 'function:0x105028',
  'generated_name': None,
  'module': 'functions.f_0000000000105028_cxa_finalize',
  'name': '__cxa_finalize',
  'operator_name': None,
  'python_symbol': '__cxa_finalize',
  'qualified_name': '<EXTERNAL>::__cxa_finalize',
  'status': 'decompiled',
  'thunk': True})

FUNCTIONS_BY_ADDRESS = {
    record["address"]: record
    for record in FUNCTIONS
    if isinstance(record.get("address"), int)
}
FUNCTIONS_BY_ID = {
    record["function_id"]: record
    for record in FUNCTIONS
    if record.get("function_id")
}

FUNCTIONS_BY_NAME = {}
for _record in FUNCTIONS:
    FUNCTIONS_BY_NAME.setdefault(_record["name"], []).append(_record)
    qualified = _record.get("qualified_name")
    if qualified and qualified != _record["name"]:
        FUNCTIONS_BY_NAME.setdefault(qualified, []).append(_record)


def _registry_records():
    path = os.path.join(os.path.dirname(__file__), NAME_REGISTRY_PATH)
    try:
        with open(path, "rt", encoding="utf-8") as handle:
            return dict(json.load(handle).get("functions", {}) or {})
    except (OSError, ValueError, TypeError):
        return {}


def _address(value):
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        text = value.strip()
        try:
            return int(text, 16) if text.lower().startswith("0x") else int(text)
        except ValueError:
            return None
    return None


def records_for_name(name):
    name = str(name)
    matches = list(FUNCTIONS_BY_NAME.get(name, ()))
    if not matches:
        for function_id, contract in _registry_records().items():
            if name not in {
                contract.get("generated_name"), contract.get("operator_name"),
                contract.get("active_name"),
            }:
                continue
            record = FUNCTIONS_BY_ID.get(function_id)
            if record is not None and record not in matches:
                matches.append(record)
    return tuple(matches)


def resolve(key):
    address = _address(key)
    if address is not None:
        record = FUNCTIONS_BY_ADDRESS.get(address)
        if record is None:
            raise KeyError("unknown PAL function address: %r" % (key,))
        return record

    matches = records_for_name(key)
    if not matches:
        raise KeyError("unknown PAL function name: %r" % (key,))
    if len(matches) != 1:
        addresses = [record.get("address_hex") for record in matches]
        raise KeyError("ambiguous PAL function name %r: %s" % (key, addresses))
    return matches[0]


def load_module(key):
    record = resolve(key)
    if record.get("status") != "decompiled":
        raise RuntimeError(
            "PAL function %s is not decompiled (status=%s)"
            % (record.get("qualified_name"), record.get("status"))
        )
    return importlib.import_module(record["module"])


def load_callable(key):
    record = resolve(key)
    module = load_module(key)
    symbol = record.get("python_symbol")
    if not symbol:
        raise RuntimeError("PAL function has no emitted Python symbol")
    return getattr(module, symbol)
