# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::record_fault
# Entry address: 0x101aac
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_load, c_ptradd, c_return_bits, c_slt, c_store, c_zext

def record_fault(param_0, param_1):
    abi_context = c_abi_context('function_entry:1055404')
    v_60 = c_ptradd(param_0, 5, 4, 64)
    v_63 = c_load(MEM, v_60, 32)
    v_86 = c_ptradd(param_0, 5, 4, 64)
    c_store(MEM, v_86, c_add(v_63, 1, 32), 32)
    c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1055408:(ram, 0x101ad8, 41, 5):5')
    c_abi_call(abi_context, 'puts', (param_1,), plan_id='call_site:1055408:(ram, 0x101ae4, 48, 6):6')
    v_138 = c_ptradd(param_0, 5, 4, 64)
    v_141 = c_load(MEM, v_138, 32)
    c_abi_call(abi_context, 'printf', (0x103316, c_zext(v_141, 32, 64)), plan_id='call_site:1055408:(ram, 0x101b01, 63, 12):12')
    v_174 = c_ptradd(param_0, 5, 4, 64)
    v_177 = c_load(MEM, v_174, 32)
    if not c_slt(2, v_177, 32):
        pass
    else:
        c_store(MEM, param_0, 4, 32)
        c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1055506:(ram, 0x101b23, 95, 1):1')
        c_abi_call(abi_context, 'puts', (0x103328,), plan_id='call_site:1055506:(ram, 0x101b32, 100, 3):3')
    return c_return_bits(0, 64)
