# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_commit
# Entry address: 0x10229c
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_and, c_eq, c_load, c_mul, c_ptradd, c_return_bits, c_slt, c_store, c_xor, c_zext

def command_commit(param_0):
    abi_context = c_abi_context('function_entry:1057436')
    v_4172 = 1
    v_60 = c_load(MEM, param_0, 32)
    if c_eq(v_60, 2, 32):
        v_133 = c_ptradd(param_0, 4, 4, 64)
        v_136 = c_load(MEM, v_133, 32)
        v_151 = c_ptradd(param_0, 1, 4, 64)
        v_154 = c_load(MEM, v_151, 32)
        v_255 = c_ptradd(param_0, 3, 4, 64)
        v_258 = c_load(MEM, v_255, 32)
        c_abi_call(abi_context, 'puts', (0x103985,), plan_id='call_site:1057490:(ram, 0x10230c, 198, 12):12')
        v_539 = c_ptradd(param_0, 1, 4, 64)
        v_542 = c_load(MEM, v_539, 32)
        if c_slt(v_542, 350, 32):
            v_643 = c_ptradd(param_0, 1, 4, 64)
            v_646 = c_load(MEM, v_643, 32)
            c_abi_call(abi_context, 'printf', (0x103998, c_zext(v_646, 32, 64)), plan_id='call_site:1057581:(ram, 0x102345, 251, 5):5')
            v_4172 = 0
        else:
            v_591 = c_ptradd(param_0, 1, 4, 64)
            v_594 = c_load(MEM, v_591, 32)
            if not c_slt(520, v_594, 32):
                v_1304 = c_ptradd(param_0, 1, 4, 64)
                v_1307 = c_load(MEM, v_1304, 32)
                c_abi_call(abi_context, 'printf', (0x1039c0, c_zext(v_1307, 32, 64)), plan_id='call_site:1057619:(ram, 0x10236b, 515, 5):5')
            else:
                v_643 = c_ptradd(param_0, 1, 4, 64)
                v_646 = c_load(MEM, v_643, 32)
                c_abi_call(abi_context, 'printf', (0x103998, c_zext(v_646, 32, 64)), plan_id='call_site:1057581:(ram, 0x102345, 251, 5):5')
                v_4172 = 0
        v_688 = c_ptradd(param_0, 2, 4, 64)
        v_691 = c_load(MEM, v_688, 32)
        if c_slt(v_691, 81, 32):
            v_1268 = c_ptradd(param_0, 2, 4, 64)
            v_1271 = c_load(MEM, v_1268, 32)
            c_abi_call(abi_context, 'printf', (0x103a10, c_zext(v_1271, 32, 64)), plan_id='call_site:1057698:(ram, 0x1023ba, 500, 5):5')
        else:
            v_742 = c_ptradd(param_0, 2, 4, 64)
            v_745 = c_load(MEM, v_742, 32)
            c_abi_call(abi_context, 'printf', (0x1039e8, c_zext(v_745, 32, 64)), plan_id='call_site:1057660:(ram, 0x102394, 290, 5):5')
            v_4172 = 0
        v_787 = c_ptradd(param_0, 3, 4, 64)
        v_790 = c_load(MEM, v_787, 32)
        if not c_eq(v_790, 0, 32):
            v_1232 = c_ptradd(param_0, 3, 4, 64)
            v_1235 = c_load(MEM, v_1232, 32)
            c_abi_call(abi_context, 'printf', (0x103a58, c_zext(v_1235, 32, 64)), plan_id='call_site:1057762:(ram, 0x1023fa, 485, 5):5')
        else:
            c_abi_call(abi_context, 'puts', (0x103a38,), plan_id='call_site:1057738:(ram, 0x1023d4, 317, 1):1')
            v_4172 = 0
        v_854 = c_ptradd(param_0, 3, 4, 64)
        v_857 = c_load(MEM, v_854, 32)
        if not c_eq(c_and(c_xor(c_mul(v_258, 19, 32), c_xor(v_136, c_mul(v_154, 3, 32), 32), 32), 3, 32), c_and(c_add(v_857, 1, 32), 3, 32), 32):
            c_abi_call(abi_context, 'puts', (0x103a98,), plan_id='call_site:1057826:(ram, 0x10242c, 467, 1):1')
            v_4172 = 0
        else:
            c_abi_call(abi_context, 'puts', (0x103a7b,), plan_id='call_site:1057809:(ram, 0x10241b, 367, 1):1')
        v_977 = c_ptradd(param_0, 5, 4, 64)
        v_980 = c_load(MEM, v_977, 32)
        if c_eq(v_980, 0, 32):
            c_abi_call(abi_context, 'puts', (0x103ae0,), plan_id='call_site:1057897:(ram, 0x102473, 462, 1):1')
        else:
            v_1021 = c_ptradd(param_0, 5, 4, 64)
            v_1024 = c_load(MEM, v_1021, 32)
            c_abi_call(abi_context, 'printf', (0x103ab8, c_zext(v_1024, 32, 64)), plan_id='call_site:1057859:(ram, 0x10245b, 400, 5):5')
            v_4172 = 0
        if v_4172:
            c_store(MEM, param_0, 3, 32)
            v_1130 = c_ptradd(param_0, 8, 4, 64)
            c_store(MEM, v_1130, 1, 32)
            c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1057935:(ram, 0x1024ab, 442, 3):3')
            c_abi_call(abi_context, 'puts', (0x103b26,), plan_id='call_site:1057935:(ram, 0x1024ba, 447, 5):5')
            c_abi_call(abi_context, 'puts', (0x103b41,), plan_id='call_site:1057935:(ram, 0x1024c9, 452, 7):7')
            c_abi_call(abi_context, 'puts', (0x103b58,), plan_id='call_site:1057935:(ram, 0x1024d8, 457, 9):9')
        else:
            c_abi_call(abi_context, 'puts', (0x103b00,), plan_id='call_site:1057918:(ram, 0x102488, 423, 1):1')
    else:
        c_abi_call(abi_context, 'puts', (0x103960,), plan_id='call_site:1057470:(ram, 0x1022c8, 40, 1):1')
    return c_return_bits(0, 64)
