# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::command_pulse
# Entry address: 0x102006
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_and, c_eq, c_load, c_mul, c_ptradd, c_return_bits, c_sdiv, c_sle, c_slt, c_store, c_zext

def command_pulse(param_0, param_1):
    abi_context = c_abi_context('function_entry:1056774')
    v_60 = c_load(MEM, param_0, 32)
    if c_eq(v_60, 2, 32):
        v_146 = c_load(MEM, c_add(param_1, 0x10, 64), 32)
        if not c_eq(v_146, 0, 32):
            v_215 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
            if c_slt(v_215, 1, 32):
                c_abi_call(abi_context, 'record_fault', (param_0, 0x103828), plan_id='call_site:1056893:(ram, 0x10208e, 127, 1):1')
                return c_return_bits(0, 64)
            else:
                v_265 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                if not c_slt(8, v_265, 32):
                    local_14 = 1
                    while True:
                        v_351 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                        if not (c_sle(local_14, v_351, 32)):
                            break
                        v_474 = c_ptradd(param_0, 3, 4, 64)
                        v_477 = c_load(MEM, v_474, 32)
                        local_10 = c_add(local_14, c_mul(c_add(v_477, 3, 32), 2, 32), 32)
                        v_577 = c_ptradd(param_0, 3, 4, 64)
                        v_580 = c_load(MEM, v_577, 32)
                        local_c = c_add(c_sdiv(local_14, 2, 32), c_add(v_580, 7, 32), 32)
                        v_817 = c_ptradd(param_0, 4, 4, 64)
                        v_820 = c_load(MEM, v_817, 32)
                        if c_eq(c_and(v_820, 4, 32), 0, 32):
                            local_c = c_add(local_c, 1, 32)
                        else:
                            local_10 = c_add(local_10, 2, 32)
                        v_938 = c_ptradd(param_0, 1, 4, 64)
                        v_941 = c_load(MEM, v_938, 32)
                        v_994 = c_ptradd(param_0, 1, 4, 64)
                        c_store(MEM, v_994, c_add(v_941, local_10, 32), 32)
                        v_1010 = c_ptradd(param_0, 2, 4, 64)
                        v_1013 = c_load(MEM, v_1010, 32)
                        v_1066 = c_ptradd(param_0, 2, 4, 64)
                        c_store(MEM, v_1066, c_add(v_1013, local_c, 32), 32)
                        v_1082 = c_ptradd(param_0, 7, 4, 64)
                        v_1085 = c_load(MEM, v_1082, 32)
                        v_1108 = c_ptradd(param_0, 7, 4, 64)
                        c_store(MEM, v_1108, c_add(v_1085, 1, 32), 32)
                        c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1057004:(ram, 0x10212a, 427, 17):17')
                        v_1142 = c_ptradd(param_0, 4, 4, 64)
                        v_1145 = c_load(MEM, v_1142, 32)
                        v_1160 = c_ptradd(param_0, 2, 4, 64)
                        v_1163 = c_load(MEM, v_1160, 32)
                        v_1178 = c_ptradd(param_0, 1, 4, 64)
                        v_1181 = c_load(MEM, v_1178, 32)
                        v_1199 = c_load(MEM, c_add(param_1, 0x14, 64), 32)
                        c_abi_call(abi_context, 'printf', (0x103860, c_zext(local_14, 32, 64), c_zext(v_1199, 32, 64), c_zext(v_1181, 32, 64), c_zext(v_1163, 32, 64), c_zext(v_1145, 32, 64)), plan_id='call_site:1057004:(ram, 0x102165, 471, 36):36')
                        v_1250 = c_ptradd(param_0, 2, 4, 64)
                        v_1253 = c_load(MEM, v_1250, 32)
                        if c_slt(149, v_1253, 32):
                            c_store(MEM, param_0, 4, 32)
                            c_abi_call(abi_context, 'refresh_checksum', (param_0,), plan_id='call_site:1057144:(ram, 0x102189, 502, 1):1')
                            c_abi_call(abi_context, 'puts', (0x103898,), plan_id='call_site:1057144:(ram, 0x102198, 507, 3):3')
                            return c_return_bits(0, 64)
                        local_14 = c_add(local_14, 1, 32)
                    v_408 = c_ptradd(param_0, 2, 4, 64)
                    v_411 = c_load(MEM, v_408, 32)
                    if not c_slt(80, v_411, 32):
                        pass
                    else:
                        c_abi_call(abi_context, 'puts', (0x1038c8,), plan_id='call_site:1057215:(ram, 0x1021c9, 179, 1):1')
                else:
                    c_abi_call(abi_context, 'record_fault', (param_0, 0x103828), plan_id='call_site:1056893:(ram, 0x10208e, 127, 1):1')
        else:
            c_abi_call(abi_context, 'record_fault', (param_0, 0x1037f0), plan_id='call_site:1056843:(ram, 0x10205c, 78, 1):1')
    else:
        c_abi_call(abi_context, 'record_fault', (param_0, 0x1037c0), plan_id='call_site:1056805:(ram, 0x102036, 44, 1):1')
    return c_return_bits(0, 64)
    return c_return_bits(0, 64)
    return c_return_bits(0, 64)
    return c_return_bits(0, 64)
    return c_return_bits(0, 64)
