# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::print_status
# Entry address: 0x101392
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_load, c_ptradd, c_return_bits, c_zext

def print_status(param_0):
    abi_context = c_abi_context('function_entry:1053586')
    c_abi_call(abi_context, 'putchar', (0xa,), plan_id='call_site:1053590:(ram, 0x1013a7, 19, 0):0')
    v_62 = c_load(MEM, param_0, 32)
    v_691 = c_bits(c_abi_call(abi_context, 'mode_name', (v_62,), plan_id='call_site:1053590:(ram, 0x1013b4, 30, 2):2'), 64)
    c_abi_call(abi_context, 'printf', (0x103254, v_691), plan_id='call_site:1053590:(ram, 0x1013cb, 37, 4):4')
    v_105 = c_ptradd(param_0, 1, 4, 64)
    v_108 = c_load(MEM, v_105, 32)
    c_abi_call(abi_context, 'printf', (0x103263, c_zext(v_108, 32, 64)), plan_id='call_site:1053590:(ram, 0x1013e8, 52, 10):10')
    v_141 = c_ptradd(param_0, 2, 4, 64)
    v_144 = c_load(MEM, v_141, 32)
    c_abi_call(abi_context, 'printf', (0x103272, c_zext(v_144, 32, 64)), plan_id='call_site:1053590:(ram, 0x101405, 67, 16):16')
    v_177 = c_ptradd(param_0, 3, 4, 64)
    v_180 = c_load(MEM, v_177, 32)
    if not c_eq(v_180, 0, 32):
        v_405 = c_ptradd(param_0, 3, 4, 64)
        v_408 = c_load(MEM, v_405, 32)
        c_abi_call(abi_context, 'printf', (0x103292, c_zext(v_408, 32, 64)), plan_id='call_site:1053734:(ram, 0x10143e, 176, 5):5')
    else:
        c_abi_call(abi_context, 'puts', (0x103281,), plan_id='call_site:1053717:(ram, 0x10141f, 90, 1):1')
    v_236 = c_ptradd(param_0, 4, 4, 64)
    v_239 = c_load(MEM, v_236, 32)
    c_abi_call(abi_context, 'printf', (0x1032a1, c_zext(v_239, 32, 64)), plan_id='call_site:1053763:(ram, 0x10145b, 106, 5):5')
    v_272 = c_ptradd(param_0, 5, 4, 64)
    v_275 = c_load(MEM, v_272, 32)
    c_abi_call(abi_context, 'printf', (0x1032b4, c_zext(v_275, 32, 64)), plan_id='call_site:1053763:(ram, 0x101478, 121, 11):11')
    v_308 = c_ptradd(param_0, 6, 4, 64)
    v_311 = c_load(MEM, v_308, 32)
    c_abi_call(abi_context, 'printf', (0x1032c3, c_zext(v_311, 32, 64)), plan_id='call_site:1053763:(ram, 0x101495, 136, 17):17')
    v_344 = c_ptradd(param_0, 7, 4, 64)
    v_347 = c_load(MEM, v_344, 32)
    c_abi_call(abi_context, 'printf', (0x1032d2, c_zext(v_347, 32, 64)), plan_id='call_site:1053763:(ram, 0x1014b2, 151, 23):23')
    c_abi_call(abi_context, 'putchar', (0xa,), plan_id='call_site:1053763:(ram, 0x1014bc, 155, 24):24')
    return c_return_bits(0, 64)
