# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::print_banner
# Entry address: 0x1012a5
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_return_bits

def print_banner():
    abi_context = c_abi_context('function_entry:1053349')
    c_abi_call(abi_context, 'puts', (0x10304c,), plan_id='call_site:1053353:(ram, 0x1012b7, 8, 1):1')
    c_abi_call(abi_context, 'puts', (0x103068,), plan_id='call_site:1053353:(ram, 0x1012c6, 13, 3):3')
    return c_return_bits(0, 64)
