# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::abort
# Entry address: 0x1023d0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def abort():
    abi_context = c_abi_context('function_entry:1057744')
    c_abi_call(abi_context, PTR_abort_0010bdf8, (), plan_id='call_site:1057748:(ram, 0x1023d4, 0, 2):2')
    return c_return_bits(0, 64)
