# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00102740
# Entry address: 0x102740
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_and, c_bits, c_eq, c_load, c_lshr, c_ne, c_piece, c_ptradd, c_ptrsub, c_return_bits, c_sext, c_sle, c_slt, c_store, c_sub, c_subpiece, c_ult, c_xor, c_zext

def FUN_00102740(param_0, param_1):
    abi_context = c_abi_context('function_entry:1058624')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_st4 = c_abi_get(abi_context, 'machine_state', 'ST4', 80)
    abi_st3 = c_abi_get(abi_context, 'machine_state', 'ST3', 80)
    abi_st2 = c_abi_get(abi_context, 'machine_state', 'ST2', 80)
    abi_st1 = c_abi_get(abi_context, 'machine_state', 'ST1', 80)
    abi_st0 = c_abi_get(abi_context, 'machine_state', 'ST0', 80)
    abi_r14 = c_abi_get(abi_context, 'machine_state', 'R14', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    v_68260 = c_piece(local_114, local_118, 32, 32, 64)
    v_10 = int2float(1)
    v_68261 = c_load(MEM, param_1, 64)
    local_40 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    local_68 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64))[1])(c_subpiece(v_10, 0, 80, 64))
    uStack_60 = c_subpiece(c_lshr(v_10, 0x40, 80), 0, 80, 16)
    local_58 = 1
    uStack_50 = c_and(local_50, -0x100000000, 64)
    if c_eq(v_68261, 0, 64):
        v_10958 = c_load(MEM, c_load(MEM, 0x10bff0, 64), 64)
        c_abi_call(abi_context, 'fwrite', (0x109a90, 1, 0x37, v_10958), plan_id='call_site:1062227:(ram, 0x10356e, 4492, 20):20')
        c_abi_call(abi_context, 'abort', (), plan_id='call_site:1062227:(ram, 0x103573, 4495, 38):38')
    else:
        v_11243 = c_bits(c_abi_call(abi_context, 'strrchr', (v_68261, 0x2f), plan_id='call_site:1058708:(ram, 0x1027a2, 89, 33):33'), 64)
        v_21649 = v_68261
        if not c_ne(v_11243, 0, 64):
            pass
        else:
            v_68266 = c_ptradd(v_11243, 1, 1, 64)
            v_25128 = v_68266
            v_21649 = v_68261
            if not c_slt(6, c_sub(v_68266, v_68261, 64), 64):
                pass
            else:
                v_322 = c_ptradd(v_11243, -6, 1, 64)
                v_11252 = c_bits(c_abi_call(abi_context, 'strncmp', (v_322, 0x109185, 7), plan_id='call_site:1058751:(ram, 0x1027cf, 132, 34):34'), 32)
                v_21649 = v_68261
                if not c_eq(v_11252, 0, 32):
                    pass
                else:
                    v_11261 = c_bits(c_abi_call(abi_context, 'strncmp', (v_68266, 0x10918d, 3), plan_id='call_site:1058776:(ram, 0x1027ea, 150, 34):34'), 32)
                    v_21649 = v_68266
                    if c_eq(v_11261, 0, 32):
                        v_10939 = c_ptradd(v_11243, 4, 1, 64)
                        c_store(MEM, c_load(MEM, 0x10bfe0, 64), v_10939, 64)
                        v_21649 = v_10939
        c_store(MEM, c_load(MEM, 0x10bfd0, 64), v_21649, 64)
        v_11269 = c_bits(c_abi_call(abi_context, 'setlocale', (6, 0x10914a), plan_id='call_site:1058816:(ram, 0x102824, 172, 81):81'), 64)
        c_abi_call(abi_context, 'bindtextdomain', (0x109082, 0x109191), plan_id='call_site:1058816:(ram, 0x10283d, 188, 117):117')
        v_21618 = 0
        c_abi_call(abi_context, 'textdomain', (0x109082,), plan_id='call_site:1058816:(ram, 0x102847, 202, 152):152')
        v_67796 = c_ptrsub(0, 0x1084c0, 64)
        c_abi_call(abi_context, 'FUN_001088b0', (v_67796,), plan_id='call_site:1058816:(ram, 0x102853, 206, 186):186')
        v_532 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
        v_25021 = v_11243
        if not c_slt(v_532, param_0, 32):
            v_921 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
            v_932 = c_sub(param_0, v_921, 32)
            if c_eq(c_sub(param_0, v_921, 32), 0, 32):
                v_68302 = c_piece(local_114, local_118, 32, 32, 64)
                v_20016 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1091be, 5), plan_id='call_site:1062496:(ram, 0x10366e, 702, 62):62'), 64)
                c_abi_call(abi_context, 'error', (0, 0, v_20016), plan_id='call_site:1062496:(ram, 0x10367c, 736, 90):90')
                v_67710 = v_68302
                c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
            else:
                if not c_ult(3, c_sub(param_0, v_921, 32), 32):
                    v_10661 = c_ptradd(param_1, c_add(c_sext(v_921, 32, 64), 3, 64), 8, 64)
                    v_10664 = c_load(MEM, v_10661, 64)
                    v_24886 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_10664,), plan_id='call_site:1062115:(ram, 0x1034e8, 4374, 30):30'), 64)
                    v_22270 = 0x1091ce
                    v_19974 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, v_22270, 5), plan_id='call_site:1062140:(ram, 0x1034fe, 3886, 66):66'), 64)
                    c_abi_call(abi_context, 'error', (0, 0, v_19974, v_24886), plan_id='call_site:1062140:(ram, 0x10350f, 3921, 94):94')
                    v_67710 = v_67733
                    c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
                else:
                    if not c_ne(v_21618, 0, 64):
                        v_21590 = v_21618
                        v_6415 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                        if c_eq(c_sub(param_0, v_921, 32), 3, 32):
                            v_39101 = c_bits(c_abi_call(abi_context, 'FUN_00103d70', (), plan_id='call_site:1060711:(ram, 0x102f70, 4006, 36):36'), 8)
                            if c_eq(v_39101, 0, 8) or (c_eq(v_39218, 0, 8) and v_39221):
                                v_67701 = 0
                            v_9811 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                            v_9819 = c_ptradd(param_1, c_sext(v_9811, 32, 64), 8, 64)
                            v_9822 = c_load(MEM, v_9819, 64)
                            local_f8 = c_subpiece(v_9822, 0, 64, 32)
                            local_f4 = c_subpiece(c_lshr(v_9822, 0x20, 64), 0, 64, 32)
                            v_39119 = c_bits(c_abi_call(abi_context, 'FUN_00103d70', (v_9822,), plan_id='call_site:1060746:(ram, 0x102fa8, 4042, 74):74'), 8)
                            if not c_ne(v_39119, 0, 8):
                                v_68310 = c_ptrsub(abi_stack_pointer, -0x88, 64)
                                v_7008 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                                c_store(MEM, c_load(MEM, 0x10bfb8, 64), c_add(v_7008, 1, 32), 32)
                                v_7029 = c_ptradd(param_1, c_sext(v_7008, 32, 64), 8, 64)
                                v_7032 = c_load(MEM, v_7029, 64)
                                c_abi_call(abi_context, 'FUN_00108560', (v_68310, v_7032), plan_id='call_site:1059837:(ram, 0x102c23, 2852, 86):86')
                                local_70 = iStack_70
                                local_80 = uStack_80
                                local_88 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64))[1])(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64))
                                v_7084 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                                local_d8 = c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64)
                                local_d0 = uStack_80
                                if c_sle(param_0, v_7084, 32):
                                    local_108 = local_78
                                    c_store(MEM, c_load(MEM, 0x10bfb8, 64), c_add(v_7084, 1, 32), 32)
                                    v_8462 = c_ptradd(param_1, c_sext(v_7084, 32, 64), 8, 64)
                                    v_8465 = c_load(MEM, v_8462, 64)
                                    c_abi_call(abi_context, 'FUN_00108560', (v_68310, v_8465), plan_id='call_site:1060867:(ram, 0x103020, 3467, 50):50')
                                    v_8522 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                                    local_e8 = c_subpiece(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 0, 64, 8)
                                    local_e7 = c_subpiece(c_lshr(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 8, 64), 0, 64, 56)
                                    local_e0 = uStack_80
                                    v_24377 = local_78
                                    v_38889 = iStack_70
                                    if c_slt(v_8522, param_0, 32):
                                        v_9091 = int2float(0)
                                        v_51306 = c_piece(uStack_80, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 16, 64, 80)
                                        uStack_50 = c_piece(uStack_6c, iStack_70, 32, 32, 64)
                                        local_68 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64))[1])(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64))
                                        uStack_60 = uStack_80
                                        local_58 = local_78
                                        v_9192 = float_equal(v_51306, v_9091)
                                        if v_9192:
                                            c_store(MEM, c_load(MEM, 0x10bfb8, 64), c_add(v_8522, 1, 32), 32)
                                            v_9302 = c_ptradd(param_1, c_sext(v_8522, 32, 64), 8, 64)
                                            v_9305 = c_load(MEM, v_9302, 64)
                                            c_abi_call(abi_context, 'FUN_00108560', (v_68310, v_9305), plan_id='call_site:1061132:(ram, 0x103124, 3825, 49):49')
                                            local_e8 = c_subpiece(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 0, 64, 8)
                                            local_e7 = c_subpiece(c_lshr(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 8, 64), 0, 64, 56)
                                            local_e0 = uStack_80
                                            v_24377 = local_78
                                            v_38889 = iStack_70
                                            local_50 = c_subpiece(local_50, 0, 64, 32)
                                            v_40151 = bool_or(c_ne(local_50, 0, 32), v_38869)
                                            v_8673 = bool_or(v_40151, c_ne(v_38889, 0, 32))
                                            v_20656 = v_20666
                                            if (c_ne(local_50, 0, 32) or c_ne(v_38869, 0, 32)) or c_ne(v_38889, 0, 32):
                                                if c_eq(v_21590, 0, 64):
                                                    local_50 = c_subpiece(local_50, 0, 64, 32)
                                                    v_39322 = local_50
                                                    if c_sle(local_50, v_38870, 32):
                                                        pass
                                                    else:
                                                        v_39322 = v_38870
                                                    if c_eq(v_39322, 2147483647, 32):
                                                        v_68331 = c_piece(local_60, local_68, 16, 64, 80)
                                                        local_c8 = v_68331
                                                        v_20674 = v_20663
                                                    else:
                                                        if c_eq(v_38891, 2147483647, 32):
                                                            v_68331 = c_piece(local_60, local_68, 16, 64, 80)
                                                            local_c8 = v_68331
                                                            v_20674 = v_20663
                                                        else:
                                                            if not c_ne(c_load(MEM, 0x10c1ec, 8), 0, 8):
                                                                v_21596 = c_ptrsub(0, 0x10c1d0, 64)
                                                                v_67920 = c_ptrsub(0, 0x10c1d0, 64)
                                                                c_abi_call(abi_context, '__sprintf_chk', (v_67920, 1, 0x1c, 0x109233, v_67629), plan_id='call_site:1061828:(ram, 0x1033e4, 2338, 65):65')
                                                                v_68330 = c_piece(uStack_60, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64), 16, 64, 80)
                                                                local_c8 = v_68330
                                                                v_20674 = pcVar22
                                                            else:
                                                                v_2674 = c_ptradd(v_20660, c_sext(c_sub(v_39935, v_38871, 32), 32, 64), 1, 64)
                                                                v_2734 = c_ptradd(v_24384, c_sext(c_sub(v_39935, v_38892, 32), 32, 64), 1, 64)
                                                                if v_39935 != 0:
                                                                    if not c_eq(v_38892, 0, 32):
                                                                        pass
                                                                    else:
                                                                        v_2865 = c_ptradd(v_2734, c_zext(c_ne(v_39935, 0, 32), 8, 64), 1, 64)
                                                                    if not c_eq(v_38871, 0, 32):
                                                                        pass
                                                                    else:
                                                                        v_20720 = c_ptradd(v_2674, c_zext(c_ne(v_39935, 0, 32), 8, 64), 1, 64)
                                                                else:
                                                                    if not c_eq(v_38892, 0, 32):
                                                                        v_22336 = c_ptradd(v_2734, -1, 1, 64)
                                                                        v_20720 = c_ptradd(v_20660, c_sext(c_sub(v_39935, v_38871, 32), 32, 64), 1, 64)
                                                                    else:
                                                                        v_2865 = c_ptradd(v_2734, c_zext(c_ne(v_39935, 0, 32), 8, 64), 1, 64)
                                                                v_20710 = v_20720
                                                                if c_ult(v_20720, v_22336, 64):
                                                                    pass
                                                                else:
                                                                    v_20710 = v_22336
                                                                v_20717 = v_20710
                                                                in_ST3 = abi_st3
                                                                in_ST2 = abi_st2
                                                                in_ST1 = abi_st1
                                                                in_ST0 = abi_st0
                                                                if c_ult(v_20710, 2147483648, 64):
                                                                    v_21596 = c_ptrsub(0, 0x10c1d0, 64)
                                                                    v_67923 = c_ptrsub(0, 0x10c1d0, 64)
                                                                    c_abi_call(abi_context, '__sprintf_chk', (v_67923, 1, 0x1c, 0x109228, c_and(v_20717, 0xffffffff, 64)), plan_id='call_site:1062016:(ram, 0x1034a0, 2017, 67):67')
                                                                    v_68349 = c_piece(uStack_60, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64), 16, 64, 80)
                                                                    local_c8 = v_68349
                                                                    v_20674 = pcVar11
                                                                else:
                                                                    v_68331 = c_piece(local_60, local_68, 16, 64, 80)
                                                                    local_c8 = v_68331
                                                                    v_20674 = v_20663
                                                else:
                                                    v_68327 = c_piece(local_60, local_68, 16, 64, 80)
                                                    local_c8 = v_68327
                                                    v_20674 = v_20656
                                                    abi_r14 = v_25043
                                                    v_24989 = v_24965
                                                    v_21596 = v_21590
                                                v_3131 = int2float(0)
                                                v_38907 = float_less(local_c8, v_3131)
                                                if v_38907:
                                                    v_53013 = c_piece(local_d0, local_d8, 16, 64, 80)
                                                    v_51302 = c_piece(local_e7, local_e8, 56, 8, 64)
                                                    v_51301 = c_piece(local_e0, v_51302, 16, 64, 80)
                                                    v_39803 = float_less(v_53013, v_51301)
                                                else:
                                                    v_51282 = c_piece(local_e7, local_e8, 56, 8, 64)
                                                    v_51281 = c_piece(local_e0, v_51282, 16, 64, 80)
                                                    v_53004 = c_piece(local_d0, local_d8, 16, 64, 80)
                                                    v_39803 = float_less(v_51281, v_53004)
                                                if v_39803:
                                                    v_5127 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
                                                    if c_ne(local_40, v_5127, 64):
                                                        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1062264:(ram, 0x103578, 2125, 19):19')
                                                    else:
                                                        return c_return_bits(0, 64)
                                                else:
                                                    local_f0 = local_d0
                                                    local_108 = int2float(1)
                                                    v_67580 = 0
                                                    while not (c_slt(4294967295, v_39041, 32) or v_67580):
                                                        v_39041 = c_bits(c_abi_call(abi_context, '__printf_chk', (1, v_21596), plan_id='call_site:1060433:(ram, 0x102e63, 1395, 57):57'), 32)
                                                        v_3668 = float_mult(local_108, local_c8)
                                                        v_53010 = c_piece(local_d0, local_d8, 16, 64, 80)
                                                        v_3711 = float_add(v_53010, v_3668)
                                                        local_110 = c_subpiece(c_lshr(v_3711, 0x40, 80), 0, 80, 16)
                                                        v_3769 = int2float(0)
                                                        v_39046 = float_lessequal(v_3769, local_c8)
                                                        if v_39046:
                                                            v_51287 = c_piece(local_e7, local_e8, 56, 8, 64)
                                                            v_51286 = c_piece(local_e0, v_51287, 16, 64, 80)
                                                            v_38925 = float_less(v_51286, v_3711)
                                                            if v_38925:
                                                                v_4777 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
                                                                v_11664 = c_bits(c_abi_call(abi_context, 'fputs_unlocked', (c_load(MEM, 0x10c1f0, 64), v_4777), plan_id='call_site:1060383:(ram, 0x102e30, 1921, 57):57'), 32)
                                                                if c_eq(v_11664, 4294967295, 32):
                                                                    break
                                                                else:
                                                                    v_4846 = int2float(1)
                                                                    local_108 = float_add(v_4846, local_108)
                                                                    local_f0 = local_110
                                                            else:
                                                                lVar27 = in_ST0
                                                                v_68231 = in_ST1
                                                                v_68234 = in_ST2
                                                                v_68237 = in_ST3
                                                                v_68240 = abi_st4
                                                                in_ST4 = abi_st4
                                                                if c_load(MEM, 0x10c1ed, 8) != 0:
                                                                    c_abi_call(abi_context, 'setlocale', (1, 0x1090d9), plan_id='call_site:1060534:(ram, 0x102ec2, 1602, 30):30')
                                                                    lVar27 = in_ST0
                                                                    v_68231 = in_ST1
                                                                    v_68234 = in_ST2
                                                                    v_68237 = in_ST3
                                                                    v_68240 = in_ST4
                                                                    in_ST4 = lVar28
                                                                v_3992 = c_ptrsub(abi_stack_pointer, -0x98, 64)
                                                                v_38945 = c_bits(c_abi_call(abi_context, 'FUN_00106d80', (v_3992, v_21596), plan_id='call_site:1060096:(ram, 0x102d15, 1629, 61):61'), 32)
                                                                if c_load(MEM, 0x10c1ed, 8) != 0:
                                                                    c_abi_call(abi_context, 'setlocale', (1, 0x10914a), plan_id='call_site:1060658:(ram, 0x102f3e, 2167, 29):29')
                                                                local_98 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), 64))[1])(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), 64))
                                                                if c_slt(v_38945, 0, 32):
                                                                    break
                                                                else:
                                                                    v_4175 = c_ptrsub(abi_stack_pointer, -0x90, 64)
                                                                    v_4183 = c_ptradd(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), 64), c_sub(c_sext(v_38945, 32, 64), abi_r14, 64), 1, 64)
                                                                    c_store(MEM, v_4183, 0, 8)
                                                                    v_4194 = c_ptradd(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), 64), v_24989, 1, 64)
                                                                    v_11607 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1060148:(ram, 0x102d50, 1684, 47):47'), 64)
                                                                    c_store(MEM, v_11607, 0, 32)
                                                                    c_abi_call(abi_context, 'FUN_00103df0', (v_4194, v_4175), plan_id='call_site:1060148:(ram, 0x102d66, 1694, 89):89')
                                                        else:
                                                            v_51297 = c_piece(local_e7, local_e8, 56, 8, 64)
                                                            v_51296 = c_piece(local_e0, v_51297, 16, 64, 80)
                                                            v_39048 = float_less(v_3711, v_51296)
                                                            if v_39048:
                                                                pass
                                                    v_5061 = c_load(MEM, c_load(MEM, 0x10bfb0, 64), 64)
                                                    v_11651 = c_bits(c_abi_call(abi_context, 'fputs_unlocked', (0x10a2ef, v_5061), plan_id='call_site:1060584:(ram, 0x102ef9, 2047, 57):57'), 32)
                                                    if not c_ne(v_11651, 4294967295, 32):
                                                        c_abi_call(abi_context, 'FUN_00103c60', (), plan_id='call_site:1062011:(ram, 0x10347b, 1997, 61):61')
                                                        v_21596 = c_ptrsub(0, 0x10c1d0, 64)
                                                        v_67923 = c_ptrsub(0, 0x10c1d0, 64)
                                                        c_abi_call(abi_context, '__sprintf_chk', (v_67923, 1, 0x1c, 0x109228, c_and(v_20717, 0xffffffff, 64)), plan_id='call_site:1062016:(ram, 0x1034a0, 2017, 67):67')
                                                        v_68349 = c_piece(uStack_60, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64), 16, 64, 80)
                                                        local_c8 = v_68349
                                                        v_20674 = pcVar11
                                                    c_abi_call(abi_context, 'FUN_00103c60', (), plan_id='call_site:1062011:(ram, 0x10347b, 1997, 61):61')
                                            else:
                                                v_8717 = float2float(0)
                                                v_53016 = c_piece(local_80, local_88, 16, 64, 80)
                                                v_8763 = float_mult(v_53016, v_8717)
                                                v_8797 = float_equal(v_8763, v_8717)
                                                if v_8797:
                                                    if c_eq(v_21590, 0, 64):
                                                        v_8897 = 0
                                                        if local_50 < v_8897:
                                                            pass
                                                        else:
                                                            v_39935 = v_8897
                                                        v_38892 = 0
                                                        v_24384 = v_24377
                                                        v_20660 = local_78
                                                        v_38871 = v_8897
                                                    else:
                                                        v_68331 = c_piece(local_60, local_68, 16, 64, 80)
                                                        local_c8 = v_68331
                                                        v_20674 = v_20663
                                                else:
                                                    v_53022 = c_piece(local_80, local_88, 16, 64, 80)
                                                    v_9019 = float_lessequal(v_8717, v_53022)
                                                    v_24390 = v_24377
                                                    v_20666 = local_78
                                                    if v_9019:
                                                        pass
                                                    else:
                                                        if v_7569 or (v_39371 and v_7760):
                                                            v_24380 = v_24390
                                                            v_20656 = local_78
                                        else:
                                            v_9406 = c_ptradd(param_1, c_add(c_sext(v_8522, 32, 64), -1, 64), 8, 64)
                                            v_9409 = c_load(MEM, v_9406, 64)
                                            v_24886 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_9409,), plan_id='call_site:1062269:(ram, 0x103582, 3869, 31):31'), 64)
                                            v_22270 = 0x109b60
                                            v_21641 = v_21590
                                            v_19974 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, v_22270, 5), plan_id='call_site:1062140:(ram, 0x1034fe, 3886, 66):66'), 64)
                                            c_abi_call(abi_context, 'error', (0, 0, v_19974, v_24886), plan_id='call_site:1062140:(ram, 0x10350f, 3921, 94):94')
                                            v_67710 = v_67733
                                            c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
                                else:
                                    local_e8 = c_subpiece(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 0, 64, 8)
                                    local_e7 = c_subpiece(c_lshr(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64), 8, 64), 0, 64, 56)
                                    v_68012 = bool_and(c_eq(iStack_70, 0, 32), c_eq(c_subpiece(uStack_50, 0, 64, 32), 0, 32))
                                    if v_38869 == 0 and local_50 == 0:
                                        v_20666 = 1
                                        local_e0 = uStack_80
                                        v_7468 = int2float(1)
                                        local_d8 = c_subpiece(v_7468, 0, 80, 64)
                                        local_d0 = c_subpiece(c_lshr(v_7468, 0x40, 80), 0, 80, 16)
                                        v_24390 = local_78
                                    else:
                                        v_20656 = 1
                                        local_e0 = uStack_80
                                        v_7289 = int2float(1)
                                        local_d8 = c_subpiece(v_7289, 0, 80, 64)
                                        local_d0 = c_subpiece(c_lshr(v_7289, 0x40, 80), 0, 80, 16)
                                        v_24380 = local_78
                                        v_38891 = iStack_70
                            else:
                                v_9921 = c_ptradd(param_1, c_add(c_sext(v_9811, 32, 64), 1, 64), 8, 64)
                                v_9924 = c_load(MEM, v_9921, 64)
                                v_39126 = c_bits(c_abi_call(abi_context, 'FUN_00103d70', (v_9924,), plan_id='call_site:1060794:(ram, 0x102fcf, 4076, 36):36'), 8)
                                if not c_ne(v_39126, 0, 8):
                                    pass
                                else:
                                    if v_67701:
                                        pass
                                    else:
                                        v_10026 = c_ptradd(param_1, c_add(c_sext(v_9811, 32, 64), 2, 64), 8, 64)
                                        v_10029 = c_load(MEM, v_10026, 64)
                                        v_68082 = c_bits(c_abi_call(abi_context, 'FUN_00103d70', (v_10029,), plan_id='call_site:1060839:(ram, 0x102ff1, 4110, 36):36'), 8)
                                        local_118 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                                        local_f8 = c_subpiece(v_9822, 0, 64, 32)
                                        local_f4 = c_subpiece(c_lshr(v_9822, 0x20, 64), 0, 64, 32)
                                        local_80 = uStack_80
                                        local_70 = iStack_70
                                        local_6c = uStack_6c
                                        local_60 = uStack_60
                                        local_50 = uStack_50
                                        if not c_ne(v_68082, 0, 8):
                                            pass
                                        else:
                                            if c_load(MEM, 0x10c1ec, 8) == 1:
                                                pass
                                            else:
                                                if not c_eq(v_21590, 0, 64):
                                                    pass
                                                else:
                                                    v_11436 = c_bits(c_abi_call(abi_context, 'strlen', (c_load(MEM, 0x10c1f0, 64),), plan_id='call_site:1059708:(ram, 0x102b83, 2683, 32):32'), 64)
                                                    if not c_eq(v_11436, 1, 64):
                                                        pass
                                                    else:
                                                        v_6680 = float2float(DAT_0010a2f8)
                                                        v_68309 = c_piece(uStack_60, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64), 16, 64, 80)
                                                        v_67562 = 0x10917f
                                                        v_67563 = 0
                                                        if c_ne(c_sub(param_0, v_921, 32), 1, 32):
                                                            pass
                                                        else:
                                                            v_67563 = local_f4
                                                            v_67562 = local_f8
                                                        if v_6771:
                                                            v_9563 = float_sub(v_68309, v_6680)
                                                            v_9635 = round(v_9563)
                                                            v_21236 = c_xor(v_9635, -0x8000000000000000, 64)
                                                        else:
                                                            v_6881 = round(v_68309)
                                                            v_21236 = v_6881
                                                        v_49570 = c_piece(v_67563, v_67562, 32, 32, 64)
                                                        v_6950 = c_ptradd(param_1, c_zext(c_add(c_sub(v_932, 1, 32), local_118, 32), 32, 64), 8, 64)
                                                        v_6953 = c_load(MEM, v_6950, 64)
                                                        v_38850 = c_bits(c_abi_call(abi_context, 'FUN_00104140', (v_49570, v_6953, v_21236), plan_id='call_site:1059807:(ram, 0x102bf0, 2821, 39):39'), 8)
                                                        if c_ne(v_38850, 0, 8):
                                                            pass
                        else:
                            v_6458 = c_ptradd(param_1, c_sext(v_6415, 32, 64), 8, 64)
                            v_6461 = c_load(MEM, v_6458, 64)
                            local_f8 = c_subpiece(v_6461, 0, 64, 32)
                            local_f4 = c_subpiece(c_lshr(v_6461, 0x20, 64), 0, 64, 32)
                            v_38799 = c_bits(c_abi_call(abi_context, 'FUN_00103d70', (v_6461,), plan_id='call_site:1059639:(ram, 0x102b48, 2630, 39):39'), 8)
                            if not c_ne(v_38799, 0, 8):
                                pass
                            else:
                                if c_ne(c_sub(param_0, v_921, 32), 1, 32):
                                    v_9697 = c_ptradd(param_1, c_add(c_sext(v_6415, 32, 64), 1, 64), 8, 64)
                                    v_9700 = c_load(MEM, v_9697, 64)
                                    v_68082 = c_bits(c_abi_call(abi_context, 'FUN_00103d70', (v_9700,), plan_id='call_site:1061036:(ram, 0x1030b1, 3985, 36):36'), 8)
                                    local_118 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
                                    local_f8 = c_subpiece(v_6461, 0, 64, 32)
                                    local_f4 = c_subpiece(c_lshr(v_6461, 0x20, 64), 0, 64, 32)
                                    local_80 = uStack_80
                                    local_70 = iStack_70
                                    local_6c = uStack_6c
                                    local_60 = uStack_60
                                    local_50 = uStack_50
                    else:
                        v_21293 = 1
                        v_20215 = 0
                        while True:
                            v_1053 = c_ptradd(v_21618, v_20215, 1, 64)
                            v_1056 = c_load(MEM, v_1053, 8)
                            v_68280 = c_add(v_21293, -1, 64)
                            if c_eq(v_1056, 0, 8):
                                v_68281 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1061961:(ram, 0x10344c, 4303, 26):26'), 64)
                                v_19923 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1091df, 5), plan_id='call_site:1061961:(ram, 0x103462, 4319, 55):55'), 64)
                                c_abi_call(abi_context, 'error', (1, 0, v_19923, pcVar22), plan_id='call_site:1061961:(ram, 0x103476, 4345, 83):83')
                                break
                            else:
                                v_20681 = 1
                                abi_r14 = v_68282
                        v_11333 = c_bits(c_abi_call(abi_context, 'strspn', (v_1108, 0x1091fd), plan_id='call_site:1059330:(ram, 0x102a09, 468, 33):33'), 64)
                        v_68285 = c_add(v_68282, v_11333, 64)
                        v_1244 = c_ptradd(v_21618, v_68285, 1, 64)
                        v_11341 = c_bits(c_abi_call(abi_context, 'strspn', (v_1244, 0x1090bd), plan_id='call_site:1059330:(ram, 0x102a1d, 484, 72):72'), 64)
                        v_21255 = c_ptradd(v_68285, v_11341, 1, 64)
                        v_1270 = c_ptradd(v_21618, v_21255, 1, 64)
                        v_1273 = c_load(MEM, v_1270, 8)
                        if not c_eq(v_1273, 46, 8):
                            pass
                        else:
                            v_1308 = c_ptradd(v_21255, 1, 1, 64)
                            v_1316 = c_ptradd(v_21618, v_1308, 1, 64)
                            v_11349 = c_bits(c_abi_call(abi_context, 'strspn', (v_1316, 0x1090bd), plan_id='call_site:1059380:(ram, 0x102a3d, 511, 36):36'), 64)
                            v_21255 = c_ptradd(v_1308, v_11349, 1, 64)
                        v_1366 = c_ptradd(v_21618, v_21255, 1, 64)
                        v_1369 = c_load(MEM, v_1366, 8)
                        v_68290 = c_ptradd(v_21255, c_zext(c_eq(v_1369, 0x4c, 8), 8, 64), 1, 64)
                        v_25052 = v_68290
                        v_1413 = c_ptradd(v_21618, v_68290, 1, 64)
                        v_1426 = c_load(MEM, v_1413, 8)
                        if not c_ne(v_1426, 0, 8):
                            v_20007 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062446:(ram, 0x103631, 645, 57):57'), 64)
                            v_20010 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109204, 5), plan_id='call_site:1062446:(ram, 0x103647, 661, 86):86'), 64)
                            c_abi_call(abi_context, 'error', (1, 0, v_20010, v_20007), plan_id='call_site:1062446:(ram, 0x10365b, 687, 114):114')
                            local_108 = c_ptradd(v_21618, v_68290, 1, 64)
                            v_68302 = c_piece(local_114, local_118, 32, 32, 64)
                            v_20016 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1091be, 5), plan_id='call_site:1062496:(ram, 0x10366e, 702, 62):62'), 64)
                            c_abi_call(abi_context, 'error', (0, 0, v_20016), plan_id='call_site:1062496:(ram, 0x10367c, 736, 90):90')
                            v_67710 = v_68302
                            c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
                        else:
                            local_118 = c_sext(v_1426, 8, 32)
                            v_11357 = c_bits(c_abi_call(abi_context, 'strchr', (0x109219, local_118), plan_id='call_site:1059434:(ram, 0x102a81, 573, 34):34'), 64)
                            v_22926 = c_add(v_68290, 1, 64)
                            v_20123 = 1
                            if c_ne(v_11357, 0, 64):
                                while True:
                                    v_5982 = c_ptradd(v_21618, v_22926, 1, 64)
                                    v_5985 = c_load(MEM, v_5982, 8)
                                    v_68295 = c_add(v_20123, -1, 64)
                                    if not c_ne(v_5985, 0, 8):
                                        break
                                    else:
                                        v_20596 = 1
                                v_6278 = c_ptradd(v_22926, 2, 1, 64)
                                v_68297 = c_bits(c_abi_call(abi_context, 'FUN_001040e0', (v_6278,), plan_id='call_site:1059544:(ram, 0x102ae0, 2561, 33):33'), 64)
                                v_21590 = c_bits(c_abi_call(abi_context, 'memcpy', (v_68297, v_21618, v_21255), plan_id='call_site:1059544:(ram, 0x102aef, 2568, 68):68'), 64)
                                local_118 = c_subpiece(v_21590, 0, 64, 32)
                                local_114 = c_subpiece(c_lshr(v_21590, 0x20, 64), 0, 64, 32)
                                v_6349 = c_ptradd(v_21590, v_21255, 1, 64)
                                c_store(MEM, v_6349, 0x4c, 8)
                                v_6357 = c_ptradd(v_21590, 1, 1, 64)
                                v_6363 = c_ptradd(v_21255, v_6357, 1, 64)
                                c_abi_call(abi_context, 'strcpy', (v_6363, v_1413), plan_id='call_site:1059544:(ram, 0x102b0a, 2586, 123):123')
                                if c_load(MEM, 0x10c1ec, 8) != 0:
                                    v_19932 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109b18, 5), plan_id='call_site:1062299:(ram, 0x1035a9, 4250, 28):28'), 64)
                                    c_abi_call(abi_context, 'error', (0, 0, v_19932), plan_id='call_site:1062299:(ram, 0x1035b7, 4284, 56):56')
                                    c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062299:(ram, 0x1035c1, 4288, 84):84')
                                    v_19989 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062342:(ram, 0x1035c9, 2494, 56):56'), 64)
                                    v_19992 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109af0, 5), plan_id='call_site:1062342:(ram, 0x1035df, 2510, 85):85'), 64)
                                    c_abi_call(abi_context, 'error', (1, 0, v_19992, v_19989), plan_id='call_site:1062342:(ram, 0x1035f3, 2536, 113):113')
                                    v_25049 = v_68290
                                    v_19998 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062392:(ram, 0x1035fb, 596, 57):57'), 64)
                                    v_20001 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109ac8, 5), plan_id='call_site:1062392:(ram, 0x103611, 612, 86):86'), 64)
                                    c_abi_call(abi_context, 'error', (1, 0, v_20001, v_19998, local_118), plan_id='call_site:1062392:(ram, 0x103629, 641, 114):114')
                                    v_20007 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062446:(ram, 0x103631, 645, 57):57'), 64)
                                    v_20010 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109204, 5), plan_id='call_site:1062446:(ram, 0x103647, 661, 86):86'), 64)
                                    c_abi_call(abi_context, 'error', (1, 0, v_20010, v_20007), plan_id='call_site:1062446:(ram, 0x10365b, 687, 114):114')
                                    local_108 = c_ptradd(v_21618, v_68290, 1, 64)
                                    v_68302 = c_piece(local_114, local_118, 32, 32, 64)
                                    v_20016 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1091be, 5), plan_id='call_site:1062496:(ram, 0x10366e, 702, 62):62'), 64)
                                    c_abi_call(abi_context, 'error', (0, 0, v_20016), plan_id='call_site:1062496:(ram, 0x10367c, 736, 90):90')
                                    v_67710 = v_68302
                                    c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
                                v_19989 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062342:(ram, 0x1035c9, 2494, 56):56'), 64)
                                v_19992 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109af0, 5), plan_id='call_site:1062342:(ram, 0x1035df, 2510, 85):85'), 64)
                                c_abi_call(abi_context, 'error', (1, 0, v_19992, v_19989), plan_id='call_site:1062342:(ram, 0x1035f3, 2536, 113):113')
                                v_25049 = v_68290
                                v_19998 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062392:(ram, 0x1035fb, 596, 57):57'), 64)
                                v_20001 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109ac8, 5), plan_id='call_site:1062392:(ram, 0x103611, 612, 86):86'), 64)
                                c_abi_call(abi_context, 'error', (1, 0, v_20001, v_19998, local_118), plan_id='call_site:1062392:(ram, 0x103629, 641, 114):114')
                                v_20007 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062446:(ram, 0x103631, 645, 57):57'), 64)
                                v_20010 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109204, 5), plan_id='call_site:1062446:(ram, 0x103647, 661, 86):86'), 64)
                                c_abi_call(abi_context, 'error', (1, 0, v_20010, v_20007), plan_id='call_site:1062446:(ram, 0x10365b, 687, 114):114')
                                local_108 = c_ptradd(v_21618, v_68290, 1, 64)
                                v_68302 = c_piece(local_114, local_118, 32, 32, 64)
                                v_20016 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1091be, 5), plan_id='call_site:1062496:(ram, 0x10366e, 702, 62):62'), 64)
                                c_abi_call(abi_context, 'error', (0, 0, v_20016), plan_id='call_site:1062496:(ram, 0x10367c, 736, 90):90')
                                v_67710 = v_68302
                                c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
                                v_1912 = c_ptrsub(abi_stack_pointer, -0xa8, 64)
                                v_39549 = c_bits(c_abi_call(abi_context, 'FUN_00106d80', (v_1912, v_21603), plan_id='call_site:1062174:(ram, 0x103530, 767, 66):66'), 32)
                                v_24314 = local_108
                                if not c_slt(v_39549, 0, 32):
                                    v_2069 = c_load(MEM, local_a0, 8)
                                    if not c_ne(v_2069, 45, 8):
                                        c_abi_call(abi_context, 'free', (local_a0,), plan_id='call_site:1061481:(ram, 0x103275, 946, 52):52')
                                        c_abi_call(abi_context, 'free', (local_a8,), plan_id='call_site:1061481:(ram, 0x10327d, 950, 79):79')
                                        v_38891 = 0
                                        v_38870 = 0
                                        v_24384 = v_24314
                                    else:
                                        v_2102 = c_load(MEM, c_load(MEM, c_ptrsub(abi_stack_pointer, -0xa8, 64), 64), 8)
                                        if not c_ne(v_2102, 45, 8):
                                            c_abi_call(abi_context, 'free', (local_a0,), plan_id='call_site:1061481:(ram, 0x103275, 946, 52):52')
                                            c_abi_call(abi_context, 'free', (local_a8,), plan_id='call_site:1061481:(ram, 0x10327d, 950, 79):79')
                                            v_38891 = 0
                                            v_38870 = 0
                                            v_24384 = v_24314
                                        else:
                                            v_2155 = float2float(DAT_0010a2f8)
                                            v_2196 = float_lessequal(v_2155, local_c8)
                                            if v_2196:
                                                v_5867 = float_sub(local_c8, v_2155)
                                                v_5926 = round(v_5867)
                                                v_21313 = c_xor(v_5926, -0x8000000000000000, 64)
                                            else:
                                                v_2295 = round(local_c8)
                                                v_21313 = v_2295
                                            v_39287 = c_bits(c_abi_call(abi_context, 'FUN_00104140', (local_a0, c_load(MEM, c_ptrsub(abi_stack_pointer, -0xa8, 64), 64), v_21313), plan_id='call_site:1061444:(ram, 0x103253, 921, 27):27'), 8)
                                            if c_ne(v_39287, 0, 8):
                                                pass
                                            else:
                                                c_abi_call(abi_context, 'free', (local_a0,), plan_id='call_site:1061481:(ram, 0x103275, 946, 52):52')
                                                c_abi_call(abi_context, 'free', (local_a8,), plan_id='call_site:1061481:(ram, 0x10327d, 950, 79):79')
                                                v_38891 = 0
                                                v_38870 = 0
                                                v_24384 = v_24314
                                else:
                                    c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1062222:(ram, 0x10354e, 795, 38):38')
                            else:
                                v_19998 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062392:(ram, 0x1035fb, 596, 57):57'), 64)
                                v_20001 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109ac8, 5), plan_id='call_site:1062392:(ram, 0x103611, 612, 86):86'), 64)
                                c_abi_call(abi_context, 'error', (1, 0, v_20001, v_19998, local_118), plan_id='call_site:1062392:(ram, 0x103629, 641, 114):114')
                                v_20007 = c_bits(c_abi_call(abi_context, 'FUN_00108540', (v_21618,), plan_id='call_site:1062446:(ram, 0x103631, 645, 57):57'), 64)
                                v_20010 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x109204, 5), plan_id='call_site:1062446:(ram, 0x103647, 661, 86):86'), 64)
                                c_abi_call(abi_context, 'error', (1, 0, v_20010, v_20007), plan_id='call_site:1062446:(ram, 0x10365b, 687, 114):114')
                                local_108 = c_ptradd(v_21618, v_68290, 1, 64)
                                v_68302 = c_piece(local_114, local_118, 32, 32, 64)
                                v_20016 = c_bits(c_abi_call(abi_context, 'dcgettext', (0, 0x1091be, 5), plan_id='call_site:1062496:(ram, 0x10366e, 702, 62):62'), 64)
                                c_abi_call(abi_context, 'error', (0, 0, v_20016), plan_id='call_site:1062496:(ram, 0x10367c, 736, 90):90')
                                v_67710 = v_68302
                                c_abi_call(abi_context, 'FUN_001038a0', (1,), plan_id='call_site:1062164:(ram, 0x103519, 741, 64):64')
        else:
            v_573 = c_ptrsub(0, 0x10bb20, 64)
            v_39736 = c_load(MEM, c_load(MEM, 0x10bfb8, 64), 32)
            while True:
                v_580 = c_ptradd(param_1, c_sext(v_39736, 32, 64), 8, 64)
                v_68274 = c_load(MEM, v_580, 64)
                v_588 = c_load(MEM, v_68274, 8)
                v_67913 = c_ptrsub(0, 0x10bb20, 64)
                v_38635 = c_bits(c_abi_call(abi_context, 'getopt_long', (param_0, param_1, 0x1091a3, v_67913, 0), plan_id='call_site:1058979:(ram, 0x1028b2, 298, 34):34'), 32)
                v_21618 = v_21624
                if c_eq(v_38635, 4294967295, 32):
                    break
                v_39736 = c_load(MEM, PTR_optind_0010bfb8, 32)
                v_21618 = v_21614
                if c_slt(v_39736, param_0, 32):
                    pass
                else:
                    break
