# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00103df0
# Entry address: 0x103df0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptrsub, c_return_bits, c_store, c_ult

def FUN_00103df0(param_0, param_1):
    abi_context = c_abi_context('function_entry:1064432')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    local_30 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x30, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x30, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    v_112 = c_ptrsub(abi_stack_pointer, -0x40, 64)
    c_abi_call(abi_context, 'strtold', (param_0, v_112), plan_id='call_site:1064436:(ram, 0x103e1b, 46, 9):9')
    v_151 = c_load(MEM, c_load(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), 64), 8)
    local_40 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), 64))[1])(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), 64))
    v_3043 = local_40
    if c_ne(v_151, 0, 8):
        v_1097 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1064544:(ram, 0x103e65, 181, 5):5'), 64)
        v_472 = c_load(MEM, v_1097, 32)
        if c_load(MEM, 0x10c1c0, 64) == 0:
            DAT_0010c1c0 = (lambda _pal_v: (c_store(MEM, 0x10c1c0, _pal_v, 64), c_load(MEM, 0x10c1c0, 64))[1])(c_bits(c_abi_call(abi_context, 'newlocale', (0x1fbf, 0x1090d9, 0), plan_id='call_site:1064744:(ram, 0x103f38, 435, 6):6'), 64))
        if c_load(MEM, 0x10c1c0, 64) == 0:
            v_3043 = param_0
            local_38 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), 64))[1])(param_0)
            if c_ult(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), 64), param_0, 64):
                c_store(MEM, v_1097, v_472, 32)
                v_3043 = local_40
            local_40 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), 64))[1])(v_3043)
            if not c_ne(param_1, 0, 64):
                pass
            else:
                c_store(MEM, param_1, local_40, 64)
            v_266 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
            if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x30, 64), 64) != v_266:
                c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1064780:(ram, 0x103f4e, 157, 4):4')
            else:
                return c_return_bits(0, 64)
        else:
            v_1113 = c_bits(c_abi_call(abi_context, 'uselocale', (c_load(MEM, 0x10c1c0, 64),), plan_id='call_site:1064591:(ram, 0x103e92, 230, 5):5'), 64)
            if c_eq(v_1113, 0, 64):
                pass
            else:
                v_641 = c_ptrsub(abi_stack_pointer, -0x38, 64)
                c_abi_call(abi_context, 'strtold', (param_0, v_641), plan_id='call_site:1064610:(ram, 0x103eae, 268, 6):6')
                v_656 = c_load(MEM, v_1097, 32)
                v_1128 = c_bits(c_abi_call(abi_context, 'uselocale', (v_1113,), plan_id='call_site:1064610:(ram, 0x103ebd, 285, 13):13'), 64)
                if c_eq(v_1128, 0, 64):
                    c_abi_call(abi_context, 'abort', (), plan_id='call_site:1058592:(ram, 0x102720, 364, 2):2')
                else:
                    c_store(MEM, v_1097, v_656, 32)
                    local_38 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), 64))[1])(c_load(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), 64))
                    v_3043 = local_38
                    if c_load(MEM, c_ptrsub(abi_stack_pointer, -0x40, 64), 64) >= c_load(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), 64):
                        pass
