# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::nl_langinfo
# Entry address: 0x10d160
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_context, c_abi_return
from PALhelpers import c_return_bits

def nl_langinfo(param_0):
    abi_context = c_abi_context('function_entry:1102176')
    return c_abi_return(abi_context, 1, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1102176')
