# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00103d70
# Entry address: 0x103d70
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_load, c_return_bits, c_sext, c_sub, c_ult

def FUN_00103d70(param_0):
    abi_context = c_abi_context('function_entry:1064304')
    v_0 = c_load(MEM, param_0, 8)
    if not c_ult(c_sub(v_0, 48, 32), 10, 32):
        return c_return_bits(0, 8)
    else:
        v_238 = c_bits(c_abi_call(abi_context, 'strlen', (param_0,), plan_id='call_site:1064315:(ram, 0x103d81, 38, 0):0'), 64)
        v_246 = c_bits(c_abi_call(abi_context, 'strspn', (param_0, 0x1090bd), plan_id='call_site:1064315:(ram, 0x103d93, 44, 2):2'), 64)
        return c_return_bits(c_eq(v_246, v_238, 64), 8)
