# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00106d80
# Entry address: 0x106d80
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_add, c_bits, c_eq, c_load, c_ne, c_ptrsub, c_return_bits, c_store, c_ult

def FUN_00106d80():
    abi_context = c_abi_context('function_entry:1076608')
    abi_rdi = c_abi_get(abi_context, 'registers', 'RDI', 64)
    abi_rsi = c_abi_get(abi_context, 'registers', 'RSI', 64)
    abi_rdx = c_abi_get(abi_context, 'registers', 'RDX', 64)
    abi_rcx = c_abi_get(abi_context, 'registers', 'RCX', 64)
    abi_r8 = c_abi_get(abi_context, 'registers', 'R8', 64)
    abi_r9 = c_abi_get(abi_context, 'registers', 'R9', 64)
    abi_xmm0 = c_abi_get(abi_context, 'registers', 'XMM0_QA', 64)
    abi_xmm1 = c_abi_get(abi_context, 'registers', 'XMM1_QA', 64)
    abi_xmm2 = c_abi_get(abi_context, 'registers', 'XMM2_QA', 64)
    abi_xmm3 = c_abi_get(abi_context, 'registers', 'XMM3_QA', 64)
    abi_xmm4 = c_abi_get(abi_context, 'registers', 'XMM4_QA', 64)
    abi_xmm5 = c_abi_get(abi_context, 'registers', 'XMM5_QA', 64)
    abi_xmm6 = c_abi_get(abi_context, 'registers', 'XMM6_QA', 64)
    abi_xmm7 = c_abi_get(abi_context, 'registers', 'XMM7_QA', 64)
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    abi_tls_base = c_abi_get(abi_context, 'tls_base', 'FS_OFFSET', 64)
    abi_xmm_count = c_abi_get(abi_context, 'variadic_xmm_count', 'AL', 8)
    abi_overflow_arguments = c_abi_get(abi_context, 'overflow_argument_area', None, None)
    if not c_ne(abi_xmm_count, 0, 8):
        pass
    else:
        local_88 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x88, 64), 64))[1])(abi_xmm0)
        local_78 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x78, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x78, 64), 64))[1])(abi_xmm1)
        local_68 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x68, 64), 64))[1])(abi_xmm2)
        local_58 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x58, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x58, 64), 64))[1])(abi_xmm3)
        local_48 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x48, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x48, 64), 64))[1])(abi_xmm4)
        local_38 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x38, 64), 64))[1])(abi_xmm5)
        local_28 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x28, 64), 64))[1])(abi_xmm6)
        local_18 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x18, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x18, 64), 64))[1])(abi_xmm7)
    local_c0 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xc0, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xc0, 64), 64))[1])(c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64))
    local_d0 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xd0, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xd0, 64), 64))[1])(c_ptrsub(abi_stack_pointer, 8, 64))
    v_243 = c_ptrsub(abi_stack_pointer, -0xd8, 64)
    local_c8 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xc8, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xc8, 64), 64))[1])(c_ptrsub(abi_stack_pointer, -0xb8, 64))
    v_253 = c_ptrsub(abi_stack_pointer, -0xe0, 64)
    local_d8 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xd8, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xd8, 64), 32))[1])(0x10)
    local_d4 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xd4, 64), _pal_v, 32), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xd4, 64), 32))[1])(0x30)
    local_a8 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xa8, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xa8, 64), 64))[1])(abi_rdx)
    local_a0 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0xa0, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0xa0, 64), 64))[1])(abi_rcx)
    local_98 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x98, 64), 64))[1])(abi_r8)
    local_90 = (lambda _pal_v: (c_store(MEM, c_ptrsub(abi_stack_pointer, -0x90, 64), _pal_v, 64), c_load(MEM, c_ptrsub(abi_stack_pointer, -0x90, 64), 64))[1])(abi_r9)
    v_1986 = c_bits(c_abi_call(abi_context, 'FUN_00104c80', (0, v_253, abi_rsi, v_243), plan_id='call_site:1076704:(ram, 0x106e26, 109, 40):40'), 64)
    if c_eq(v_1986, 0, 64):
        v_628 = 0xffffffff
    else:
        if c_load(MEM, c_ptrsub(abi_stack_pointer, -0xe0, 64), 64) >= 2147483648:
            c_abi_call(abi_context, 'free', (v_1986,), plan_id='call_site:1076828:(ram, 0x106e5c, 179, 18):18')
            v_525 = c_bits(c_abi_call(abi_context, '__errno_location', (), plan_id='call_site:1076828:(ram, 0x106e61, 182, 37):37'), 64)
            c_store(MEM, v_525, 0x4b, 32)
            v_628 = 0xffffffff
        else:
            c_store(MEM, abi_rdi, v_1986, 64)
            v_628 = c_load(MEM, c_ptrsub(abi_stack_pointer, -0xe0, 64), 64)
    v_387 = c_load(MEM, c_add(abi_tls_base, 0x28, 64), 64)
    if c_load(MEM, c_ptrsub(abi_stack_pointer, -0xc0, 64), 64) != v_387:
        c_abi_call(abi_context, '__stack_chk_fail', (), plan_id='call_site:1076858:(ram, 0x106e7a, 174, 17):17')
    else:
        return c_return_bits(v_628, 64)
