# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::__printf_chk
# Entry address: 0x102640
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def __printf_chk():
    abi_context = c_abi_context('function_entry:1058368')
    c_abi_call(abi_context, PTR___printf_chk_0010bf30, (), plan_id='call_site:1058372:(ram, 0x102644, 0, 2):2')
    return c_return_bits(0, 64)
