# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::fputs_unlocked
# Entry address: 0x102550
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def fputs_unlocked(param_0, param_1):
    abi_context = c_abi_context('function_entry:1058128')
    v_16 = c_bits(c_abi_call(abi_context, PTR_fputs_unlocked_0010beb8, (), plan_id='call_site:1058132:(ram, 0x102554, 0, 2):2'), 32)
    return c_abi_return(abi_context, v_16, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1058128')
