# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: switchD_0010583e::caseD_0
# Entry address: 0x102725
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context

def caseD_0():
    abi_context = c_abi_context('function_entry:1058597')
    c_abi_call(abi_context, 'abort', (), plan_id='call_site:1058597:(ram, 0x102725, 2, 0):0')
