# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::abort
# Entry address: 0x10d020
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def abort():
    return c_return_bits(1, 32)
