# Generated by PALExecInterface.
# Controlled clear-case PAL project runtime.

from __future__ import annotations

import argparse
import importlib.util
import inspect
import json
import os
import sys
from pathlib import Path

EXEC_ROOT = Path(__file__).resolve().parent
RUNTIME_ROOT = EXEC_ROOT / "runtime"
SHIMS_ROOT = EXEC_ROOT / "shims"
FUNCTIONS_ROOT = EXEC_ROOT / "functions"
for _path in (str(RUNTIME_ROOT), str(SHIMS_ROOT), str(FUNCTIONS_ROOT), str(EXEC_ROOT)):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from PALMEM import PALMemory
from PALShims import PALPrintShims, PALProcessExit


class PALPublishedRuntimeError(RuntimeError):
    pass


def _read_json(path):
    with open(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def _key_names(record):
    names = set()
    for key in (
        "name", "qualified_name", "python_symbol", "active_name",
        "generated_name", "operator_name", "pal_name", "ssa_name",
        "function_id", "entry_hex",
    ):
        value = record.get(key)
        if value not in (None, ""):
            names.add(str(value))
    entry = record.get("entry")
    if isinstance(entry, int):
        names.add(str(entry))
        names.add(hex(entry))
    return names


def _abi_internal_target_names(index):
    """Derive internal target spellings from the published plan authority."""
    names = set()
    call_plans = dict((index or {}).get("call_plans") or {})
    for plan in call_plans.values():
        if not isinstance(plan, dict):
            continue
        compatibility = dict(plan.get("target_compatibility") or {})
        linkage = dict(plan.get("linkage_contract") or {})
        internal = bool(
            str(plan.get("dispatch_policy") or "") == "PAL_internal_dispatch"
            or compatibility.get("internal_target") is True
            or linkage.get("semantic_internal") is True
        )
        if not internal:
            continue
        target = dict(plan.get("target") or {})
        for key in (
            "name", "qualified_name", "python_symbol", "active_name",
            "generated_name", "operator_name", "pal_name", "ssa_name",
            "function_id", "entry_hex",
        ):
            value = target.get(key)
            if value not in (None, ""):
                names.add(str(value))
        entry = target.get("entry")
        if isinstance(entry, int):
            names.add(str(entry))
            names.add(hex(entry))
            names.add("function:%s" % hex(entry))
    return names


class PALProjectRuntime:
    def __init__(self, root=None):
        self.root = Path(root or EXEC_ROOT).resolve()
        self.config = _read_json(self.root / "config.exec.json")
        self.abi_plans = _read_json(self.root / "PAL_abi_plans.json")
        self.memory = PALMemory()
        self.records = list(self.config.get("functions") or [])
        self._record_index = {}
        self._module_cache = {}
        self._callable_cache = {}

        # Config is a useful publication summary, but the frozen ABI plan
        # index is the runtime dispatch authority.  Re-derive ownership here
        # so stale or incomplete publisher classifications cannot redirect an
        # internal call into shim city.
        self.internal_call_targets = set(
            str(name) for name in (self.config.get("internal_call_targets") or [])
        )
        self.internal_call_targets.update(
            _abi_internal_target_names(self.abi_plans)
        )

        # Every published executable artifact is available in the internal
        # namespace.  External shims live in a separate namespace; the same
        # spelling may validly exist in both and dispatch_policy chooses.
        self.internal_names = set()
        for record in self.records:
            names = _key_names(record)
            self.internal_names.update(names)
            for name in names:
                self._record_index.setdefault(name, []).append(record)

        external_names = set(self.config.get("external_targets") or [])
        external_names.update(self.config.get("thunk_targets") or [])
        self.shims = PALPrintShims(self.memory).mapping(sorted(external_names))

    def _record_identity(self, record):
        return str(
            record.get("function_id")
            or record.get("entry_hex")
            or record.get("name")
        )

    def _is_internal_record(self, record):
        # A published module is an internal callable regardless of stale
        # manifest external/thunk labeling.  Boundary metadata controls
        # top-level convenience behavior, not ABI dispatch ownership.
        return bool(record.get("published_module"))

    def _unique_records(self, name):
        unique = []
        seen = set()
        for record in list(self._record_index.get(str(name)) or []):
            identity = self._record_identity(record)
            if identity in seen:
                continue
            seen.add(identity)
            unique.append(record)
        return unique

    def records_for(self, key):
        text = str(key)
        records = list(self._record_index.get(text) or [])
        if not records:
            try:
                number = int(text, 16) if text.lower().startswith("0x") else int(text)
            except ValueError:
                number = None
            if number is not None:
                records = [r for r in self.records if r.get("entry") == number]
        return records

    def resolve(self, key):
        records = self.records_for(key)
        if not records:
            raise PALPublishedRuntimeError("unknown published PAL function: %r" % key)
        if len(records) != 1:
            raise PALPublishedRuntimeError(
                "ambiguous published PAL function %r: %s"
                % (key, [record.get("entry_hex") for record in records])
            )
        return records[0]

    def _module_path(self, record):
        return self.root / str(record["published_module"])

    def _direct_shim_globals(self):
        return dict(self.shims)

    def _internal_wrapper(self, record):
        identity = str(record.get("function_id") or record.get("entry_hex") or record.get("name"))
        if identity in self._callable_cache:
            return self._callable_cache[identity]

        def invoke(*values):
            # Internal ABI dispatch must execute the published artifact.  It
            # must never re-enter top-level shim-boundary selection.
            function = self._published_callable(record)
            return self._invoke_adapted(function, values)

        invoke.__name__ = str(record.get("python_symbol") or record.get("name") or "pal_function")
        self._callable_cache[identity] = invoke
        return invoke

    def _all_internal_globals(self):
        table = {}
        for name in sorted(self._record_index):
            if not str(name).isidentifier():
                continue
            records = self._unique_records(name)
            if len(records) == 1:
                table[name] = self._internal_wrapper(records[0])
        return table

    def load_module(self, record_or_key):
        record = record_or_key if isinstance(record_or_key, dict) else self.resolve(record_or_key)
        identity = str(record.get("function_id") or record.get("entry_hex") or record.get("name"))
        cached = self._module_cache.get(identity)
        if cached is not None:
            return cached
        path = self._module_path(record)
        if not path.is_file():
            raise PALPublishedRuntimeError("published function module is missing: %s" % path)
        module_name = "palexec_%s" % str(record.get("module_stem") or path.stem)
        spec = importlib.util.spec_from_file_location(module_name, path)
        if spec is None or spec.loader is None:
            raise PALPublishedRuntimeError("cannot load published module: %s" % path)
        module = importlib.util.module_from_spec(spec)
        module.MEM = self.memory
        # Inject published internal wrappers before shims.  Local definitions
        # in the module overwrite these during exec, while cross-function
        # direct calls retain internal ownership.
        module.__dict__.update(self._all_internal_globals())
        for _name, _value in self._direct_shim_globals().items():
            module.__dict__.setdefault(_name, _value)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)
        module.MEM = self.memory
        for _name, _value in self._all_internal_globals().items():
            module.__dict__.setdefault(_name, _value)
        for _name, _value in self._direct_shim_globals().items():
            module.__dict__.setdefault(_name, _value)
        self._module_cache[identity] = module
        return module

    def _published_callable(self, record):
        module = self.load_module(record)
        symbol = record.get("python_symbol")
        function = getattr(module, str(symbol), None)
        if not callable(function):
            raise PALPublishedRuntimeError(
                "published module %s has no callable %r"
                % (record.get("published_module"), symbol)
            )
        return function

    def load_callable(self, record_or_key):
        record = record_or_key if isinstance(record_or_key, dict) else self.resolve(record_or_key)
        # Direct user selection of a genuine boundary may use its shim, but
        # internal wrappers bypass this path and always execute published code.
        if record.get("is_shim_boundary"):
            for name in _key_names(record):
                if name in self.shims:
                    return self.shims[name]
        return self._published_callable(record)

    def _invoke_adapted(self, function, values):
        try:
            signature = inspect.signature(function)
            positional = [
                parameter
                for parameter in signature.parameters.values()
                if parameter.kind in (
                    inspect.Parameter.POSITIONAL_ONLY,
                    inspect.Parameter.POSITIONAL_OR_KEYWORD,
                )
            ]
            varargs = any(
                parameter.kind == inspect.Parameter.VAR_POSITIONAL
                for parameter in signature.parameters.values()
            )
            if not positional and not varargs:
                return function()
            return function(*tuple(values))
        except (TypeError, ValueError):
            return function(*tuple(values))

    def _materialize_value(self, value):
        if isinstance(value, str) and value.startswith("str:"):
            return self.memory.allocate_c_string(value[4:])
        return value

    def _context(self, record, fixed_arguments, variadic_arguments):
        try:
            from PALABI import PALCallContext, PALVariadicArguments
        except ImportError as exc:
            raise PALPublishedRuntimeError("PALABI runtime is unavailable: %s" % exc)
        values = tuple(self._materialize_value(value) for value in fixed_arguments)
        var_values = tuple(self._materialize_value(value) for value in variadic_arguments)
        var_builder = PALVariadicArguments.from_values(*var_values) if var_values else None
        context = PALCallContext.for_sysv_amd64(
            self.memory,
            fixed_arguments=values,
            variadic_arguments=var_builder,
            variadic=bool(var_values),
            entry_plan_id=record.get("entry_plan_id"),
        )
        context.register_metadata(self.abi_plans)

        # Internal and external dispatch are independent namespaces.
        # Register every unambiguous published alias internally.
        for name in sorted(self._record_index):
            records = self._unique_records(name)
            if len(records) == 1:
                context.register_internal(name, self._internal_wrapper(records[0]))

        # Shims are external-only.  Never place a trap into internal_functions;
        # doing so converts a linker/classification error into a false external
        # execution path and masks the real ownership defect.
        for name, shim in self.shims.items():
            context.register_external(name, shim)

        missing = []
        ambiguous = []
        for name in sorted(self.internal_call_targets):
            records = self._unique_records(name)
            if len(records) == 1:
                context.register_internal(name, self._internal_wrapper(records[0]))
            elif not records:
                missing.append(name)
            else:
                ambiguous.append(
                    "%s -> %s"
                    % (name, [self._record_identity(record) for record in records])
                )
        if missing or ambiguous:
            parts = []
            if missing:
                parts.append("missing internal targets: %s" % ", ".join(missing))
            if ambiguous:
                parts.append("ambiguous internal targets: %s" % "; ".join(ambiguous))
            raise PALPublishedRuntimeError(
                "PAL ABI internal-dispatch preflight failed; " + " | ".join(parts)
            )
        return context, values

    def run(self, function_key=None, arguments=(), variadic_arguments=()):
        key = function_key or self.config.get("default_entry")
        if not key:
            raise PALPublishedRuntimeError("no execution entry was selected")
        record = self.resolve(key)
        function = self.load_callable(record)
        values = tuple(self._materialize_value(value) for value in arguments)
        if record.get("runtime_mode") == "abi_context":
            context, frame_values = self._context(record, values, variadic_arguments)
            with context.activate():
                return self._invoke_adapted(function, frame_values)
        return self._invoke_adapted(function, values)


def run(function=None, arguments=(), variadic_arguments=()):
    return PALProjectRuntime().run(function, arguments, variadic_arguments)
