# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_001040e0
# Entry address: 0x1040e0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_eq, c_ne, c_return_bits

def FUN_001040e0(param_0):
    abi_context = c_abi_context('function_entry:1065184')
    v_116 = c_bits(c_abi_call(abi_context, 'malloc', (param_0,), plan_id='call_site:1065184:(ram, 0x1040e4, 6, 0):0'), 64)
    if not c_eq(v_116, 0, 64):
        return c_return_bits(0, 64)
    else:
        if c_ne(param_0, 0, 64):
            c_abi_call(abi_context, 'FUN_00103db0', (), plan_id='call_site:1065205:(ram, 0x1040f5, 38, 0):0')
