# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::fseeko
# Entry address: 0x10d1b8
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_context, c_abi_return
from PALhelpers import c_return_bits

def fseeko(param_1, param_0, param_2):
    abi_context = c_abi_context('function_entry:1102264')
    return c_abi_return(abi_context, 1, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1102264')
