# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::_DT_INIT
# Entry address: 0x102000
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_ne, c_return_bits, c_store

def _DT_INIT():
    abi_context = c_abi_context('function_entry:1056768')
    if c_load(MEM, 0x10bfc8, 64) == 0:
        pass
    else:
        c_abi_call(abi_context, PTR___gmon_start___0010bfc8, (), plan_id='call_site:1056788:(ram, 0x102014, 23, 2):2')
    return c_return_bits(0, 64)
