# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::__ctype_get_mb_cur_max
# Entry address: 0x102480
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def __ctype_get_mb_cur_max():
    abi_context = c_abi_context('function_entry:1057920')
    v_14 = c_bits(c_abi_call(abi_context, PTR___ctype_get_mb_cur_max_0010be50, (), plan_id='call_site:1057924:(ram, 0x102484, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_14, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1057920')
