# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_001088b0
# Entry address: 0x1088b0
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def FUN_001088b0(param_0):
    abi_context = c_abi_context('function_entry:1083568')
    c_abi_call(abi_context, '__cxa_atexit', (param_0, 0, c_load(MEM, 0x10c008, 64)), plan_id='call_site:1083572:(ram, 0x1088bd, 11, 1):1')
    return c_return_bits(0, 64)
