# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::clearerr_unlocked
# Entry address: 0x10d060
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def clearerr_unlocked(param_0):
    return c_return_bits(1, 32)
