# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::strtold
# Entry address: 0x102670
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def strtold(param_1, param_0):
    abi_context = c_abi_context('function_entry:1058416')
    v_42 = c_bits(c_abi_call(abi_context, PTR_strtold_0010bf48, (), plan_id='call_site:1058420:(ram, 0x102674, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_42, 64, (('register', 'XMM0_Qa', 64, 'register:4608:8'),), plan_id='function_entry:1058416')
