# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::error
# Entry address: 0x102680
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def error():
    abi_context = c_abi_context('function_entry:1058432')
    c_abi_call(abi_context, PTR_error_0010bf50, (), plan_id='call_site:1058436:(ram, 0x102684, 0, 2):2')
    return c_return_bits(0, 64)
