# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::FUN_00102020
# Entry address: 0x102020
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_load, c_return_bits, c_store

def FUN_00102020():
    abi_context = c_abi_context('function_entry:1056800')
    c_abi_call(abi_context, PTR_0010bde0, (), plan_id='call_site:1056800:(ram, 0x102026, 3, 3):3')
    return c_return_bits(1, 32)
