# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::lseek
# Entry address: 0x102500
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def lseek(param_0, param_1, param_2):
    abi_context = c_abi_context('function_entry:1058048')
    v_17 = c_bits(c_abi_call(abi_context, PTR_lseek_0010be90, (), plan_id='call_site:1058052:(ram, 0x102504, 0, 2):2'), 64)
    return c_abi_return(abi_context, v_17, 64, (('register', 'RAX', 64, 'register:0:8'),), plan_id='function_entry:1058048')
