# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::printf
# Entry address: 0x101050
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_get, c_abi_return
from PALhelpers import c_bits, c_load, c_return_bits, c_store

def printf(param_0):
    abi_context = c_abi_context('function_entry:1052752')
    abi_overflow_arguments = c_abi_get(abi_context, 'overflow_argument_area', None, None)
    v_15 = c_bits(c_abi_call(abi_context, PTR_printf_00103fd0, (), plan_id='call_site:1052756:(ram, 0x101054, 0, 2):2'), 32)
    return c_abi_return(abi_context, v_15, 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1052752')
