# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::mutate
# Entry address: 0x101149
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_mul, c_return_bits, c_xor

def mutate(param_0):
    return c_return_bits(c_xor(c_mul(param_0, 2, 32), 0x55, 32), 32)
