# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::__do_global_dtors_aux
# Entry address: 0x101110
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_eq, c_load, c_ne, c_return_bits, c_store

def __do_global_dtors_aux():
    abi_context = c_abi_context('function_entry:1052944')
    if not c_eq(c_load(MEM, 1065016, 8), 0, 8):
        return c_return_bits(0, 64)
    else:
        if not c_ne(c_load(MEM, 1064928, 64), 0, 64):
            pass
        else:
            c_abi_call(abi_context, '__cxa_finalize', (c_load(MEM, 0x104020, 64),), plan_id='call_site:1052971:(ram, 0x101132, 30, 3):3')
        c_abi_call(abi_context, 'deregister_tm_clones', (), plan_id='call_site:1052983:(ram, 0x101137, 33, 6):6')
        return c_return_bits(0, 64)
