# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::apply_burn
# Entry address: 0x1014a6
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_load, c_ptradd, c_return_bits, c_slt, c_store, c_sub

def apply_burn(param_0, param_1):
    v_34 = c_ptradd(param_0, 2, 4, 64)
    v_37 = c_load(MEM, v_34, 32)
    local_14 = param_1
    if not c_slt(v_37, param_1, 32):
        pass
    else:
        v_94 = c_ptradd(param_0, 2, 4, 64)
        local_14 = c_load(MEM, v_94, 32)
    v_120 = c_ptradd(param_0, 2, 4, 64)
    v_123 = c_load(MEM, v_120, 32)
    v_182 = c_ptradd(param_0, 2, 4, 64)
    c_store(MEM, v_182, c_sub(v_123, local_14, 32), 32)
    v_198 = c_ptradd(param_0, 1, 4, 64)
    v_201 = c_load(MEM, v_198, 32)
    v_224 = c_ptradd(param_0, 1, 4, 64)
    c_store(MEM, v_224, c_add(v_201, 2, 32), 32)
    v_240 = c_ptradd(param_0, 1, 4, 64)
    v_243 = c_load(MEM, v_240, 32)
    v_302 = c_ptradd(param_0, 1, 4, 64)
    c_store(MEM, v_302, c_sub(v_243, local_14, 32), 32)
    v_318 = c_load(MEM, param_0, 32)
    v_333 = c_ptradd(param_0, 1, 4, 64)
    v_336 = c_load(MEM, v_333, 32)
    c_store(MEM, param_0, c_sub(v_318, v_336, 32), 32)
    v_392 = c_ptradd(param_0, 3, 4, 64)
    v_395 = c_load(MEM, v_392, 32)
    v_418 = c_ptradd(param_0, 3, 4, 64)
    c_store(MEM, v_418, c_add(v_395, 1, 32), 32)
    v_434 = c_load(MEM, param_0, 32)
    if not c_slt(30, v_434, 32):
        pass
    else:
        c_store(MEM, param_0, 0x1e, 32)
        v_498 = c_ptradd(param_0, 1, 4, 64)
        c_store(MEM, v_498, 0, 32)
    v_514 = c_load(MEM, param_0, 32)
    if not c_slt(v_514, 1, 32):
        pass
    else:
        c_store(MEM, param_0, 0, 32)
        v_576 = c_ptradd(param_0, 4, 4, 64)
        c_store(MEM, v_576, 0, 32)
        v_592 = c_ptradd(param_0, 1, 4, 64)
        v_595 = c_load(MEM, v_592, 32)
        if c_slt(v_595, 4294967294, 32):
            v_733 = c_ptradd(param_0, 5, 4, 64)
            c_store(MEM, v_733, 0, 32)
        else:
            v_643 = c_ptradd(param_0, 1, 4, 64)
            v_646 = c_load(MEM, v_643, 32)
            if not c_slt(3, v_646, 32):
                v_733 = c_ptradd(param_0, 5, 4, 64)
                c_store(MEM, v_733, 0, 32)
            else:
                v_699 = c_ptradd(param_0, 5, 4, 64)
                c_store(MEM, v_699, 1, 32)
    return c_return_bits(0, 64)
