# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::read_burn
# Entry address: 0x101437
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context, c_abi_get
from PALhelpers import c_bits, c_eq, c_load, c_ptrsub, c_return_bits, c_slt, c_store

def read_burn(param_0):
    abi_context = c_abi_context('function_entry:1053751')
    abi_stack_pointer = c_abi_get(abi_context, 'stack_pointer', 'RSP', 64)
    v_46 = c_ptrsub(abi_stack_pointer, -0x28, 64)
    v_237 = c_bits(c_abi_call(abi_context, 'fgets', (v_46, 0x10, c_load(MEM, 0x104030, 64)), plan_id='call_site:1053751:(ram, 0x101456, 23, 2):2'), 64)
    if not c_eq(v_237, 0, 64):
        v_129 = c_ptrsub(abi_stack_pointer, -0x28, 64)
        v_700 = c_bits(c_abi_call(abi_context, 'parse_burn', (v_129, param_0), plan_id='call_site:1053814:(ram, 0x101484, 57, 2):2'), 32)
        if v_700 >= 0:
            pass
        else:
            c_abi_call(abi_context, 'puts', (0x102270,), plan_id='call_site:1053842:(ram, 0x10149c, 79, 3):3')
            v_700 = local_c
    else:
        c_abi_call(abi_context, 'puts', (0x10225f,), plan_id='call_site:1053792:(ram, 0x10146a, 39, 2):2')
        v_700 = 0
    return c_return_bits(v_700, 32)
