# Generated by PAL batch_v2h_final_abi_authority_publication
# Ghidra function: Global::lander_exit_code
# Entry address: 0x1016bd
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2h_final_abi_authority_publication
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALlibrary.FunctionCFG = PALlibrary_v23e_clothed_emperor_cfg_truth
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = PALSemanticGraphBuilder_v38_clothed_emperor_edgetruth_tristate_custody
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v60u_mars_exact_inplace_state_write_terminator_v1
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALhelpers import c_add, c_eq, c_load, c_return_bits

def lander_exit_code(param_0):
    v_29 = c_load(MEM, c_add(param_0, 0x14, 64), 32)
    if c_eq(v_29, 0, 32):
        v_93 = c_load(MEM, c_add(param_0, 0x18, 64), 32)
        if c_eq(v_93, 0, 32):
            v_183 = 3
        else:
            v_183 = 2
    else:
        v_183 = 0
    return c_return_bits(v_183, 64)
