# Generated by PALExecInterface.
# Controlled clear-case PAL project runtime.

from __future__ import annotations

PAL_PROJECT_RUNTIME_VERSION = "v11_x86_64_register_family_truth_runtime"
PAL_ABI_RUNTIME_REQUIRED_VERSION = "v1d_x86_64_register_family_alias_truth"
import argparse
import importlib.util
import inspect
import json
import os
import sys
from pathlib import Path

EXEC_ROOT = Path(__file__).resolve().parent
RUNTIME_ROOT = EXEC_ROOT / "runtime"
SHIMS_ROOT = EXEC_ROOT / "shims"
FUNCTIONS_ROOT = EXEC_ROOT / "functions"
for _path in (str(RUNTIME_ROOT), str(SHIMS_ROOT), str(FUNCTIONS_ROOT), str(EXEC_ROOT)):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from PALMEM import PALMemory
from PALShims import PALPrintShims, PALProcessExit


class PALPublishedRuntimeError(RuntimeError):
    pass


def _read_json(path):
    with open(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def _truthy_environment(name, default=False):
    value = os.environ.get(str(name))
    if value is None:
        return bool(default)
    return str(value).strip().lower() not in {
        "",
        "0",
        "false",
        "no",
        "off",
    }


class PALRuntimeTrace:
    """Append-only internal-call and memory-custody trace."""

    def __init__(self, root, memory, *, enabled=False, stderr=False):
        self.root = Path(root)
        self.memory = memory
        self.enabled = bool(enabled)
        self.stderr = bool(stderr)
        self.path = self.root / "PAL_runtime_trace.jsonl"
        self.sequence = 0
        if self.enabled:
            try:
                self.path.unlink()
            except FileNotFoundError:
                pass

    def _json_value(self, value):
        if value is None or isinstance(value, (bool, int, float, str)):
            return value
        if isinstance(value, (list, tuple)):
            return [self._json_value(item) for item in value]
        if isinstance(value, dict):
            return {
                str(key): self._json_value(item)
                for key, item in value.items()
            }
        return repr(value)

    def pointer_preview(self, value, *, limit=32):
        if not isinstance(value, int):
            return None
        address = int(value)
        if not hasattr(self.memory, "has_byte"):
            return None
        if not self.memory.has_byte(address):
            return None
        raw = self.memory.read_bytes(address, int(limit))
        nul = raw.find(b"\0")
        bounded = raw if nul < 0 else raw[: nul + 1]
        text = None
        try:
            payload = bounded[:-1] if bounded.endswith(b"\0") else bounded
            decoded = payload.decode("utf-8", errors="strict")
            if decoded and all(
                character.isprintable() or character in "\t\r\n"
                for character in decoded
            ):
                text = decoded
        except UnicodeDecodeError:
            text = None
        return {
            "address": hex(address),
            "hex": bounded.hex(),
            "cstring": text,
            "nul_terminated_within_preview": nul >= 0,
        }

    def describe_values(self, values):
        described = []
        for value in tuple(values):
            record = {"value": self._json_value(value)}
            preview = self.pointer_preview(value)
            if preview is not None:
                record["pointer"] = preview
            described.append(record)
        return described

    def emit(self, kind, **fields):
        if not self.enabled:
            return
        self.sequence += 1
        record = {
            "sequence": self.sequence,
            "kind": str(kind),
            "memory_id": id(self.memory),
            "memory_root_token": getattr(
                self.memory,
                "root_token",
                "PALMEM:%x" % id(self.memory),
            ),
        }
        record.update(
            {
                str(key): self._json_value(value)
                for key, value in fields.items()
            }
        )
        line = json.dumps(
            record,
            sort_keys=True,
            ensure_ascii=True,
            allow_nan=False,
        )
        with open(self.path, "at", encoding="utf-8", newline="\n") as handle:
            handle.write(line + "\n")
        if self.stderr:
            print("PAL TRACE", line, file=sys.stderr, flush=True)


def _carrier_value_records(context, carriers):
    records = []
    for raw in tuple(carriers or ()):
        if isinstance(raw, dict):
            kind = raw.get("kind") or raw.get("carrier_kind")
            register = raw.get("register") or raw.get("carrier")
            width = raw.get("carrier_width_bits") or raw.get("width_bits")
        else:
            item = tuple(raw)
            kind = item[0] if len(item) > 0 else None
            register = item[1] if len(item) > 1 else None
            width = item[2] if len(item) > 2 else None
        record = {
            "kind": kind,
            "register": register,
            "width_bits": width,
            "value": None,
        }
        if kind == "register" and register and isinstance(width, int):
            try:
                record["value"] = context.frame.get_register(
                    register,
                    width,
                )
            except Exception as exc:
                record["read_error"] = "%s: %s" % (
                    type(exc).__name__,
                    exc,
                )
        records.append(record)
    return records


def _install_abi_trace_hooks():
    """Observe PALABI v1c without replacing its custody decisions."""
    from PALABI import (
        PALCallContext,
        PALSysVAMD64CallFrame,
        current_abi_context,
    )

    marker = "_pal_exec_v1q_abi_trace_hooks"
    if getattr(PALCallContext, marker, False):
        return

    original_child_context = PALCallContext._child_context
    original_materialize = (
        PALSysVAMD64CallFrame.materialize_entry_arguments
    )
    original_complete_return = PALCallContext._complete_internal_return
    original_call = PALCallContext.call

    def traced_call(context, target, values, plan_id):
        plan = dict(
            context.call_plans.get(str(plan_id)) or {}
        )
        bridge = dict(
            plan.get("partial_argument_bridge") or {}
        )
        logical_values = list(values)
        if bridge.get("active") is True:
            expected = len(
                [
                    item
                    for item in list(plan.get("arguments") or [])
                    if isinstance(item, dict)
                ]
            )
            supplied = len(logical_values)
            if supplied < expected:
                logical_values.extend(
                    [0] * (expected - supplied)
                )
            trace = getattr(context, "_pal_exec_trace", None)
            if trace is not None:
                trace.emit(
                    "abi_argument_bridge",
                    call_plan_id=plan_id,
                    target=target,
                    supplied_argument_count=supplied,
                    runtime_argument_count=len(logical_values),
                    zero_filled=max(expected - supplied, 0),
                    actions=list(bridge.get("actions") or []),
                    contract_ids=list(
                        bridge.get("contract_ids") or []
                    ),
                    policy=bridge.get("policy"),
                )
        return original_call(
            context,
            target,
            tuple(logical_values),
            plan_id,
        )

    def traced_child_context(parent, frame, entry_plan_id):
        child = original_child_context(parent, frame, entry_plan_id)
        trace = getattr(parent, "_pal_exec_trace", None)
        if trace is not None:
            child._pal_exec_trace = trace
        return child

    def traced_materialize(
        frame,
        call_plan,
        entry_plan,
        *,
        original_values=(),
    ):
        materialized = original_materialize(
            frame,
            call_plan,
            entry_plan,
            original_values=original_values,
        )
        trace = None
        try:
            trace = getattr(
                current_abi_context(),
                "_pal_exec_trace",
                None,
            )
        except Exception:
            trace = None
        if trace is not None:
            arguments = []
            for item in sorted(
                [
                    dict(value)
                    for value in list(call_plan.get("arguments") or [])
                    if isinstance(value, dict)
                ],
                key=lambda value: (
                    value.get("index") is None,
                    value.get("index")
                    if isinstance(value.get("index"), int)
                    else 0,
                ),
            ):
                arguments.append({
                    "index": item.get("index"),
                    "source_sid": item.get("source_sid"),
                    "argument_class": item.get("argument_class"),
                    "source_width_bits": item.get("source_width_bits"),
                    "carrier_kind": item.get("carrier_kind"),
                    "carrier": item.get("carrier"),
                    "stack_slot": item.get("stack_slot"),
                    "parameter_region": item.get("parameter_region"),
                })
            trace.emit(
                "abi_child_frame_arguments",
                call_plan_id=call_plan.get("plan_id"),
                target_entry_plan_id=entry_plan.get("plan_id"),
                child_frame_entry_plan_id=getattr(
                    frame,
                    "entry_plan_id",
                    None,
                ),
                child_frame_call_plan_id=getattr(
                    frame,
                    "call_plan_id",
                    None,
                ),
                stack_pointer=getattr(frame, "stack_pointer", None),
                overflow_stack_base=getattr(
                    frame,
                    "overflow_stack_base",
                    None,
                ),
                carrier_plan=arguments,
                caller_values=trace.describe_values(original_values),
                materialized_values=trace.describe_values(materialized),
                argument_source="materialized_child_frame",
            )
        return materialized

    def traced_complete_return(
        parent,
        *,
        child,
        result,
        plan,
        entry_plan,
        target_name,
    ):
        trace = getattr(parent, "_pal_exec_trace", None)
        if trace is not None:
            trace.emit(
                "abi_callee_semantic_result",
                target=target_name,
                call_plan_id=plan.get("plan_id"),
                target_entry_plan_id=entry_plan.get("plan_id"),
                callee_semantic_result=result,
                child_return_value_before_completion=child.return_value,
                child_return_carriers_before_completion=(
                    _carrier_value_records(child, child.return_carriers)
                ),
            )
        try:
            caller_view = original_complete_return(
                parent,
                child=child,
                result=result,
                plan=plan,
                entry_plan=entry_plan,
                target_name=target_name,
            )
        except BaseException as exc:
            if trace is not None:
                trace.emit(
                    "abi_return_transfer_raise",
                    target=target_name,
                    call_plan_id=plan.get("plan_id"),
                    target_entry_plan_id=entry_plan.get("plan_id"),
                    exception_type=type(exc).__name__,
                    exception=str(exc),
                )
            raise
        if trace is not None:
            trace.emit(
                "abi_return_transfer",
                target=target_name,
                call_plan_id=plan.get("plan_id"),
                target_entry_plan_id=entry_plan.get("plan_id"),
                callee_semantic_result=result,
                child_return_value=child.return_value,
                child_return_carriers=(
                    _carrier_value_records(child, child.return_carriers)
                ),
                parent_return_carriers=(
                    _carrier_value_records(
                        parent,
                        parent.last_call_return_carriers,
                    )
                ),
                parent_last_call_result_raw=parent.last_call_result_raw,
                parent_last_call_result_width_bits=(
                    parent.last_call_result_width_bits
                ),
                parent_transfer_status=parent.last_call_transfer_status,
                caller_visible_result=caller_view,
            )
        return caller_view

    PALCallContext.call = traced_call
    PALCallContext._child_context = traced_child_context
    PALSysVAMD64CallFrame.materialize_entry_arguments = traced_materialize
    PALCallContext._complete_internal_return = traced_complete_return
    setattr(PALCallContext, marker, True)


def _audit_abi_chain_publication(root, config):
    publication = dict(config.get("abi_chain_publication") or {})
    authority = dict(config.get("abi_authority_loading") or {})
    partial = dict(config.get("abi_partial_publication") or {})
    health = str(publication.get("health") or "BROKEN").upper()
    failures = []
    if health not in {"READY", "DEGRADED", "BROKEN"}:
        failures.append({"kind": "invalid_abi_chain_health", "health": health})

    observed = {}
    import hashlib
    for key, record in dict(authority.get("artifacts") or {}).items():
        if not isinstance(record, dict):
            continue
        name = str(record.get("name") or "")
        expected = str(record.get("sha256") or "")
        path = Path(root) / name
        actual = None
        if path.is_file():
            digest = hashlib.sha256()
            with open(path, "rb") as handle:
                while True:
                    chunk = handle.read(1024 * 1024)
                    if not chunk:
                        break
                    digest.update(chunk)
            actual = digest.hexdigest()
            if expected and actual != expected:
                failures.append({
                    "kind": "abi_authority_sha256_mismatch",
                    "artifact": key,
                    "expected": expected,
                    "observed": actual,
                })
        else:
            failures.append({
                "kind": "abi_authority_artifact_missing",
                "artifact": key,
                "path": str(path),
            })
        observed[key] = {
            "path": str(path),
            "expected_sha256": expected or None,
            "observed_sha256": actual,
        }

    if partial.get("active"):
        partial_name = str(
            partial.get("artifact")
            or "PAL_abi_partial_publication.json"
        )
        partial_expected = str(partial.get("sha256") or "")
        partial_path = Path(root) / partial_name
        if not partial_path.is_file():
            failures.append({
                "kind": "abi_partial_publication_artifact_missing",
                "path": str(partial_path),
            })
        else:
            digest = hashlib.sha256()
            with open(partial_path, "rb") as handle:
                while True:
                    chunk = handle.read(1024 * 1024)
                    if not chunk:
                        break
                    digest.update(chunk)
            partial_observed = digest.hexdigest()
            if (
                partial_expected
                and partial_observed != partial_expected
            ):
                failures.append({
                    "kind": "abi_partial_publication_sha256_mismatch",
                    "expected": partial_expected,
                    "observed": partial_observed,
                })
            observed["partial_publication"] = {
                "path": str(partial_path),
                "expected_sha256": partial_expected or None,
                "observed_sha256": partial_observed,
            }

        bridge_name = str(
            partial.get("argument_bridge_artifact") or ""
        )
        bridge_expected = str(
            partial.get("argument_bridge_sha256") or ""
        )
        if bridge_name:
            bridge_path = Path(root) / bridge_name
            if not bridge_path.is_file():
                failures.append({
                    "kind": "abi_argument_bridge_artifact_missing",
                    "path": str(bridge_path),
                })
            else:
                digest = hashlib.sha256()
                with open(bridge_path, "rb") as handle:
                    while True:
                        chunk = handle.read(1024 * 1024)
                        if not chunk:
                            break
                        digest.update(chunk)
                bridge_observed = digest.hexdigest()
                if (
                    bridge_expected
                    and bridge_observed != bridge_expected
                ):
                    failures.append({
                        "kind": "abi_argument_bridge_sha256_mismatch",
                        "expected": bridge_expected,
                        "observed": bridge_observed,
                    })
                observed["argument_bridge"] = {
                    "path": str(bridge_path),
                    "expected_sha256": bridge_expected or None,
                    "observed_sha256": bridge_observed,
                }

    runtime_index = _read_json(Path(root) / "PAL_abi_plans.json")
    source_index = dict(authority.get("artifacts") or {}).get("plan_index") or {}
    source_receipt = dict(authority.get("artifacts") or {}).get("final_authority") or {}
    if runtime_index.get("format") != "pal_runtime_abi_plan_index":
        failures.append({"kind": "runtime_abi_plan_index_format_mismatch"})
    if runtime_index.get("phase") != authority.get("phase"):
        failures.append({"kind": "runtime_abi_plan_index_phase_mismatch"})
    if runtime_index.get("source_plan_index_sha256") != source_index.get("sha256"):
        failures.append({"kind": "runtime_plan_index_source_hash_mismatch"})
    if runtime_index.get("source_final_authority_sha256") != source_receipt.get("sha256"):
        failures.append({"kind": "runtime_final_authority_source_hash_mismatch"})

    audit = {
        "active": bool(publication.get("active")),
        "health": health,
        "source_mode": authority.get("source_mode"),
        "phase": authority.get("phase"),
        "artifacts": observed,
        "counts": dict(publication.get("counts") or {}),
        "failures": failures,
    }
    if failures or health == "BROKEN":
        reasons = list(
            failures
            or publication.get("broken_reasons")
            or ["unspecified ABI authority failure"]
        )
        formatted = []
        for index, reason in enumerate(reasons, 1):
            if isinstance(reason, dict):
                detail = json.dumps(reason, sort_keys=True)
            else:
                detail = str(reason).replace("_", " ")
            formatted.append("  %02d | ERROR | %s" % (index, detail))
        raise PALPublishedRuntimeError(
            "PAL ABI AUTHORITY GATE // BROKEN\n"
            + "\n".join(formatted)
        )
    return audit


def _audit_static_string_helper_load(memory, root):
    """Verify required bytes through PALhelpers.c_load."""
    report_path = Path(root) / "PAL_static_string_completion.json"
    if not report_path.is_file():
        return {
            "active": False,
            "reason": "completion_report_not_present",
            "verified_strings": 0,
        }

    from PALhelpers import c_load

    report = _read_json(report_path)
    required = dict(report.get("required_strings") or {})
    failures = []
    for raw_address, value in required.items():
        address = int(str(raw_address), 0)
        expected = str(value).encode("utf-8") + b"\0"
        observed = bytes(
            c_load(memory, address + index, 8)
            for index in range(len(expected))
        )
        if observed != expected:
            failures.append({
                "address": hex(address),
                "expected_hex": expected.hex(),
                "observed_hex": observed.hex(),
            })

    audit = {
        "active": True,
        "verified_strings": len(required),
        "failures": failures,
        "rule": (
            "published_static_string_bytes_must_match_through_"
            "PALhelpers_c_load_on_the_runtime_root_memory"
        ),
    }
    if failures:
        raise PALPublishedRuntimeError(
            "PAL helper-load static-string audit failed: %s" % failures
        )
    return audit


def _audit_static_string_memory(memory, root):
    report_path = (
        Path(root)
        / "PAL_static_string_completion.json"
    )
    if not report_path.is_file():
        return {
            "active": False,
            "reason": "completion_report_not_present",
            "verified_strings": 0,
        }

    report = _read_json(report_path)
    required = dict(
        report.get("required_strings") or {}
    )
    counts = dict(report.get("counts") or {})
    translation = dict(
        report.get("address_translation") or {}
    )
    unresolved = int(
        counts.get(
            "unresolved_ptrsub_references",
            translation.get(
                "unresolved_references",
                0,
            ),
        )
        or 0
    )
    failures = []

    for raw_address, text in required.items():
        address = int(str(raw_address), 0)
        expected = (
            str(text).encode("utf-8")
            + b"\0"
        )
        actual = memory.read_bytes(
            address,
            len(expected),
        )
        if actual != expected:
            failures.append({
                "address": hex(address),
                "expected_hex": expected.hex(),
                "actual_hex": actual.hex(),
            })

    audit = {
        "active": True,
        "health": (
            "BROKEN"
            if failures
            else (
                "DEGRADED"
                if unresolved
                else "READY"
            )
        ),
        "report": str(report_path),
        "verified_strings": len(required),
        "direct_resolved_references": int(
            counts.get(
                "direct_resolved_references",
                translation.get(
                    "direct_resolved_references",
                    0,
                ),
            )
            or 0
        ),
        "rebased_resolved_references": int(
            counts.get(
                "rebased_resolved_references",
                translation.get(
                    "rebased_resolved_references",
                    0,
                ),
            )
            or 0
        ),
        "unresolved_references": unresolved,
        "address_translation": translation,
        "failures": failures,
        "rule": (
            "every_completed_static_string_must_"
            "be_byte_visible_through_the_same_"
            "PALMemory_seen_by_lifted_c_load"
        ),
    }

    if failures:
        raise PALPublishedRuntimeError(
            "PAL static-string memory audit "
            "failed: %s" % failures
        )

    return audit



def _key_names(record):
    names = set()
    for key in (
        "name", "qualified_name", "python_symbol", "active_name",
        "generated_name", "operator_name", "pal_name", "ssa_name",
        "function_id", "entry_hex",
    ):
        value = record.get(key)
        if value not in (None, ""):
            names.add(str(value))
    entry = record.get("entry")
    if isinstance(entry, int):
        names.add(str(entry))
        names.add(hex(entry))
    return names


def _abi_internal_target_names(index):
    """Derive internal target spellings from the published plan authority."""
    names = set()
    call_plans = dict((index or {}).get("call_plans") or {})
    for plan in call_plans.values():
        if not isinstance(plan, dict):
            continue
        compatibility = dict(plan.get("target_compatibility") or {})
        linkage = dict(plan.get("linkage_contract") or {})
        internal = bool(
            str(plan.get("dispatch_policy") or "") == "PAL_internal_dispatch"
            or compatibility.get("internal_target") is True
            or linkage.get("semantic_internal") is True
        )
        if not internal:
            continue
        target = dict(plan.get("target") or {})
        for key in (
            "name", "qualified_name", "python_symbol", "active_name",
            "generated_name", "operator_name", "pal_name", "ssa_name",
            "function_id", "entry_hex",
        ):
            value = target.get(key)
            if value not in (None, ""):
                names.add(str(value))
        entry = target.get("entry")
        if isinstance(entry, int):
            names.add(str(entry))
            names.add(hex(entry))
            names.add("function:%s" % hex(entry))
    return names


class PALProjectRuntime:
    def __init__(self, root=None):
        self.root = Path(root or EXEC_ROOT).resolve()
        self.config = _read_json(self.root / "config.exec.json")
        self.abi_plans = _read_json(self.root / "PAL_abi_plans.json")
        from PALABI import PAL_ABI_RUNTIME_VERSION
        if (
            PAL_ABI_RUNTIME_VERSION
            != PAL_ABI_RUNTIME_REQUIRED_VERSION
        ):
            raise PALPublishedRuntimeError(
                "PALABI runtime build mismatch; required=%s observed=%s"
                % (
                    PAL_ABI_RUNTIME_REQUIRED_VERSION,
                    PAL_ABI_RUNTIME_VERSION,
                )
            )
        self.memory = PALMemory()
        self.records = list(self.config.get("functions") or [])
        self._record_index = {}
        self._module_cache = {}
        self._callable_cache = {}

        # Config is a useful publication summary, but the frozen ABI plan
        # index is the runtime dispatch authority.  Re-derive ownership here
        # so stale or incomplete publisher classifications cannot redirect an
        # internal call into shim city.
        self.internal_call_targets = set(
            str(name) for name in (self.config.get("internal_call_targets") or [])
        )
        self.internal_call_targets.update(
            _abi_internal_target_names(self.abi_plans)
        )

        # Every published executable artifact is available in the internal
        # namespace.  External shims live in a separate namespace; the same
        # spelling may validly exist in both and dispatch_policy chooses.
        self.internal_names = set()
        for record in self.records:
            names = _key_names(record)
            self.internal_names.update(names)
            for name in names:
                self._record_index.setdefault(name, []).append(record)

        external_names = set(self.config.get("external_targets") or [])
        external_names.update(self.config.get("thunk_targets") or [])
        self.shims = PALPrintShims(self.memory).mapping(sorted(external_names))
        self.trace = PALRuntimeTrace(
            self.root,
            self.memory,
            enabled=_truthy_environment("PAL_EXEC_TRACE"),
            stderr=_truthy_environment("PAL_EXEC_TRACE_STDERR"),
        )
        self.abi_chain_runtime_audit = _audit_abi_chain_publication(
            self.root,
            self.config,
        )
        self.trace.emit(
            "abi_chain_publication",
            audit=self.abi_chain_runtime_audit,
        )
        self.static_string_memory_audit = _audit_static_string_memory(
            self.memory,
            self.root,
        )
        self.static_string_helper_load_audit = (
            _audit_static_string_helper_load(
                self.memory,
                self.root,
            )
        )
        self.trace.emit(
            "runtime_memory_root",
            mapped_byte_count=(
                self.memory.mapped_byte_count()
                if hasattr(self.memory, "mapped_byte_count")
                else len(self.memory)
            ),
            static_memory_audit=self.static_string_memory_audit,
            static_helper_load_audit=self.static_string_helper_load_audit,
        )

    def _assert_module_memory(self, module, record, phase):
        observed = getattr(module, "MEM", None)
        if observed is not self.memory:
            raise PALPublishedRuntimeError(
                "PAL module memory-root custody failed; "
                "function=%s phase=%s expected=%s observed=%s"
                % (
                    self._record_identity(record),
                    phase,
                    id(self.memory),
                    id(observed) if observed is not None else None,
                )
            )
        self.trace.emit(
            "module_memory_custody",
            function=self._record_identity(record),
            name=record.get("name"),
            phase=phase,
            module_memory_id=id(observed),
            root_identity=True,
        )

    def _bind_module_memory(self, module, record, phase):
        module.MEM = self.memory
        self._assert_module_memory(module, record, phase)
        return module

    def _assert_context_memory(self, context, phase):
        context_memory = getattr(context, "memory", None)
        thread = getattr(context, "thread", None)
        thread_memory = getattr(thread, "memory", None)
        if (
            context_memory is not self.memory
            or thread_memory is not self.memory
        ):
            raise PALPublishedRuntimeError(
                "PAL ABI memory-root custody failed; "
                "phase=%s root=%s context=%s thread=%s"
                % (
                    phase,
                    id(self.memory),
                    id(context_memory) if context_memory is not None else None,
                    id(thread_memory) if thread_memory is not None else None,
                )
            )
        self.trace.emit(
            "abi_memory_custody",
            phase=phase,
            context_memory_id=id(context_memory),
            thread_memory_id=id(thread_memory),
            root_identity=True,
        )

    def _invoke_record(self, record, values):
        if record.get("runtime_mode") == "abi_trunk":
            result = int(record.get("trunk_return_value") or 0)
            self.trace.emit(
                "abi_trunk_call",
                function=self._record_identity(record),
                name=record.get("name"),
                reason=record.get("trunk_reason"),
                source_status=record.get("source_status"),
                arguments=self.trace.describe_values(values),
                result=result,
                policy="explicit_user_approved_void_zero_trunk",
            )
            return result
        module = self.load_module(record)
        self._bind_module_memory(
            module,
            record,
            "immediately_before_invocation",
        )
        symbol = record.get("python_symbol")
        function = getattr(module, str(symbol), None)
        if not callable(function):
            raise PALPublishedRuntimeError(
                "published module %s has no callable %r"
                % (record.get("published_module"), symbol)
            )

        identity = self._record_identity(record)
        self.trace.emit(
            "internal_call_enter",
            function=identity,
            name=record.get("name"),
            runtime_mode=record.get("runtime_mode"),
            arguments=self.trace.describe_values(values),
        )
        try:
            result = self._invoke_adapted(function, values)
        except BaseException as exc:
            self.trace.emit(
                "internal_call_raise",
                function=identity,
                name=record.get("name"),
                exception_type=type(exc).__name__,
                exception=str(exc),
            )
            raise
        self._assert_module_memory(
            module,
            record,
            "immediately_after_invocation",
        )
        self.trace.emit(
            "internal_call_exit",
            function=identity,
            name=record.get("name"),
            result=result,
            result_pointer=self.trace.pointer_preview(result),
        )
        return result

    def _record_identity(self, record):
        return str(
            record.get("function_id")
            or record.get("entry_hex")
            or record.get("name")
        )

    def _is_internal_record(self, record):
        # A published module is an internal callable regardless of stale
        # manifest external/thunk labeling.  Boundary metadata controls
        # top-level convenience behavior, not ABI dispatch ownership.
        return bool(record.get("published_module"))

    def _unique_records(self, name):
        unique = []
        seen = set()
        for record in list(self._record_index.get(str(name)) or []):
            identity = self._record_identity(record)
            if identity in seen:
                continue
            seen.add(identity)
            unique.append(record)
        return unique

    def records_for(self, key):
        text = str(key)
        records = list(self._record_index.get(text) or [])
        if not records:
            try:
                number = int(text, 16) if text.lower().startswith("0x") else int(text)
            except ValueError:
                number = None
            if number is not None:
                records = [r for r in self.records if r.get("entry") == number]
        return records

    def resolve(self, key):
        records = self.records_for(key)
        if not records:
            raise PALPublishedRuntimeError("unknown published PAL function: %r" % key)
        if len(records) != 1:
            raise PALPublishedRuntimeError(
                "ambiguous published PAL function %r: %s"
                % (key, [record.get("entry_hex") for record in records])
            )
        return records[0]

    def _module_path(self, record):
        return self.root / str(record["published_module"])

    def _direct_shim_globals(self):
        return dict(self.shims)

    def _internal_wrapper(self, record):
        identity = str(record.get("function_id") or record.get("entry_hex") or record.get("name"))
        if identity in self._callable_cache:
            return self._callable_cache[identity]

        def invoke(*values):
            # Internal ABI dispatch executes exactly one published artifact
            # under the shared PALMemory root and records the call boundary.
            return self._invoke_record(record, values)

        invoke.__name__ = str(record.get("python_symbol") or record.get("name") or "pal_function")
        self._callable_cache[identity] = invoke
        return invoke

    def _all_internal_globals(self):
        table = {}
        for name in sorted(self._record_index):
            if not str(name).isidentifier():
                continue
            records = self._unique_records(name)
            if len(records) == 1:
                table[name] = self._internal_wrapper(records[0])
        return table

    def load_module(self, record_or_key):
        record = record_or_key if isinstance(record_or_key, dict) else self.resolve(record_or_key)
        identity = str(record.get("function_id") or record.get("entry_hex") or record.get("name"))
        cached = self._module_cache.get(identity)
        if cached is not None:
            return self._bind_module_memory(
                cached,
                record,
                "cached_module_return",
            )
        path = self._module_path(record)
        if not path.is_file():
            raise PALPublishedRuntimeError("published function module is missing: %s" % path)
        module_name = "palexec_%s" % str(record.get("module_stem") or path.stem)
        spec = importlib.util.spec_from_file_location(module_name, path)
        if spec is None or spec.loader is None:
            raise PALPublishedRuntimeError("cannot load published module: %s" % path)
        module = importlib.util.module_from_spec(spec)
        self._bind_module_memory(
            module,
            record,
            "before_module_exec",
        )
        # Inject published internal wrappers before shims.  Local definitions
        # in the module overwrite these during exec, while cross-function
        # direct calls retain internal ownership.
        module.__dict__.update(self._all_internal_globals())
        for _name, _value in self._direct_shim_globals().items():
            module.__dict__.setdefault(_name, _value)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)
        self._bind_module_memory(
            module,
            record,
            "after_module_exec",
        )
        for _name, _value in self._all_internal_globals().items():
            module.__dict__.setdefault(_name, _value)
        for _name, _value in self._direct_shim_globals().items():
            module.__dict__.setdefault(_name, _value)
        self._module_cache[identity] = module
        self.trace.emit(
            "module_loaded",
            function=identity,
            name=record.get("name"),
            module_name=module_name,
            module_path=str(path),
            module_memory_id=id(module.MEM),
        )
        return module

    def _published_callable(self, record):
        module = self.load_module(record)
        symbol = record.get("python_symbol")
        function = getattr(module, str(symbol), None)
        if not callable(function):
            raise PALPublishedRuntimeError(
                "published module %s has no callable %r"
                % (record.get("published_module"), symbol)
            )
        return function

    def load_callable(self, record_or_key):
        record = record_or_key if isinstance(record_or_key, dict) else self.resolve(record_or_key)
        # Direct user selection of a genuine boundary may use its shim, but
        # internal wrappers bypass this path and always execute published code.
        if record.get("is_shim_boundary"):
            for name in _key_names(record):
                if name in self.shims:
                    return self.shims[name]
        return self._internal_wrapper(record)

    def _invoke_adapted(self, function, values):
        """
        Bind arguments before invocation and execute the callable exactly once.

        The former implementation caught ``TypeError`` around the function
        call itself and retried it.  A TypeError raised inside published PAL
        code was therefore misclassified as a signature-adaptation failure,
        duplicating side effects and obscuring the original stack.
        """
        values = tuple(values)
        try:
            signature = inspect.signature(function)
        except (TypeError, ValueError):
            # Some extension/builtin callables do not expose a signature.
            # There is no safe adaptation available; call exactly once.
            return function(*values)

        positional = [
            parameter
            for parameter in signature.parameters.values()
            if parameter.kind in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
            )
        ]
        varargs = any(
            parameter.kind == inspect.Parameter.VAR_POSITIONAL
            for parameter in signature.parameters.values()
        )
        call_values = () if not positional and not varargs else values

        try:
            signature.bind(*call_values)
        except TypeError as exc:
            raise PALPublishedRuntimeError(
                "published PAL function argument binding failed; "
                "function=%r signature=%s supplied_positional=%d error=%s"
                % (
                    getattr(function, "__name__", repr(function)),
                    signature,
                    len(call_values),
                    exc,
                )
            ) from exc

        # Do not catch TypeError here.  Any exception raised after function
        # entry belongs to the published function/runtime and must propagate
        # without a second invocation.
        return function(*call_values)

    def _materialize_value(self, value):
        if isinstance(value, str) and value.startswith("str:"):
            return self.memory.allocate_c_string(value[4:])
        return value

    def _context(self, record, fixed_arguments, variadic_arguments):
        try:
            from PALABI import PALCallContext, PALVariadicArguments
        except ImportError as exc:
            raise PALPublishedRuntimeError("PALABI runtime is unavailable: %s" % exc)
        values = tuple(self._materialize_value(value) for value in fixed_arguments)
        var_values = tuple(self._materialize_value(value) for value in variadic_arguments)
        var_builder = PALVariadicArguments.from_values(*var_values) if var_values else None
        context = PALCallContext.for_sysv_amd64(
            self.memory,
            fixed_arguments=values,
            variadic_arguments=var_builder,
            variadic=bool(var_values),
            entry_plan_id=record.get("entry_plan_id"),
        )
        entry_plans = dict(
            self.abi_plans.get("entry_plans") or {}
        )
        call_plans = dict(
            self.abi_plans.get("call_plans") or {}
        )
        for plan_id, plan in entry_plans.items():
            if not isinstance(plan, dict):
                raise PALPublishedRuntimeError(
                    "runtime entry-plan record is not a mapping: %s"
                    % plan_id
                )
            context.register_entry_plan(plan)
        for plan_id, plan in call_plans.items():
            if not isinstance(plan, dict):
                raise PALPublishedRuntimeError(
                    "runtime call-plan record is not a mapping: %s"
                    % plan_id
                )
            context.register_call_plan(plan)
        _install_abi_trace_hooks()
        context._pal_exec_trace = self.trace
        self._assert_context_memory(
            context,
            "top_level_context_constructed",
        )

        # Internal and external dispatch are independent namespaces.
        # Register every unambiguous published alias internally.
        for name in sorted(self._record_index):
            records = self._unique_records(name)
            if len(records) == 1:
                context.register_internal(name, self._internal_wrapper(records[0]))

        # Shims are external-only.  Never place a trap into internal_functions;
        # doing so converts a linker/classification error into a false external
        # execution path and masks the real ownership defect.
        for name, shim in self.shims.items():
            context.register_external(name, shim)

        missing = []
        ambiguous = []
        for name in sorted(self.internal_call_targets):
            records = self._unique_records(name)
            if len(records) == 1:
                context.register_internal(name, self._internal_wrapper(records[0]))
            elif not records:
                missing.append(name)
            else:
                ambiguous.append(
                    "%s -> %s"
                    % (name, [self._record_identity(record) for record in records])
                )
        if missing or ambiguous:
            parts = []
            if missing:
                parts.append("missing internal targets: %s" % ", ".join(missing))
            if ambiguous:
                parts.append("ambiguous internal targets: %s" % "; ".join(ambiguous))
            raise PALPublishedRuntimeError(
                "PAL ABI internal-dispatch preflight failed; " + " | ".join(parts)
            )
        return context, values

    def run(self, function_key=None, arguments=(), variadic_arguments=()):
        key = function_key or self.config.get("default_entry")
        if not key:
            raise PALPublishedRuntimeError("no execution entry was selected")
        record = self.resolve(key)
        function = self.load_callable(record)
        values = tuple(self._materialize_value(value) for value in arguments)
        if record.get("runtime_mode") == "abi_context":
            context, frame_values = self._context(record, values, variadic_arguments)
            with context.activate():
                return self._invoke_adapted(function, frame_values)
        return self._invoke_adapted(function, values)


def run(function=None, arguments=(), variadic_arguments=()):
    return PALProjectRuntime().run(function, arguments, variadic_arguments)
