# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::main
# Entry address: 0x101273
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_return_bits

def main():
    abi_context = c_abi_context('function_entry:1053299')
    v_268 = c_bits(c_abi_call(abi_context, 'PALexec', (0xabcd1234, 0xfffffe0c, 0x7fff), plan_id='call_site:1053303:(ram, 0x1012a1, 40, 0):0'), 32)
    return c_return_bits(v_268, 32)
