# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::frame_dummy
# Entry address: 0x101120
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_return_bits

def frame_dummy():
    abi_context = c_abi_context('function_entry:1052960')
    c_abi_call(abi_context, 'register_tm_clones', (), plan_id='call_site:1052964:(ram, 0x101124, 0, 0):0')
    return c_return_bits(0, 64)
