# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: <EXTERNAL>::__gmon_start__
# Entry address: 0x105010
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def __gmon_start__():
    return c_return_bits(1, 32)
