# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::main
# Entry address: 0x101273
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_bits, c_return_bits

def main():
    abi_context = c_abi_context('function_entry:1053299')
    v_268 = c_bits(c_abi_call(abi_context, 'PALexec', (0xabcd1234, 0xfffffe0c, 0x7fff), plan_id='call_site:1053303:(ram, 0x1012a1, 40, 0):0'), 32)
    return c_return_bits(v_268, 32)
