# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::transform_b
# Entry address: 0x10115e
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_context, c_abi_return
from PALhelpers import c_add, c_ashr, c_mul, c_return_bits

def transform_b(param_0):
    abi_context = c_abi_context('function_entry:1053022')
    return c_abi_return(abi_context, c_add(c_ashr(param_0, 1, 32), c_mul(param_0, 7, 32), 32), 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1053022')
