# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::_fini
# Entry address: 0x10136c
# This executable projection remains governed by its PAL icecube metadata.

from PALhelpers import c_return_bits

def _fini():
    return c_return_bits(0, 64)
