# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::check_bit
# Entry address: 0x10117e
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_context, c_abi_return
from PALhelpers import c_and, c_ashr, c_return_bits, c_subpiece

def check_bit(param_1, param_0):
    abi_context = c_abi_context('function_entry:1053054')
    return c_abi_return(abi_context, c_and(c_ashr(param_1, c_and(c_subpiece(param_0, 0, 32, 8), 0x1f, 8), 32), 1, 32), 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1053054')
