# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::mutate
# Entry address: 0x101149
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_context, c_abi_return
from PALhelpers import c_mul, c_return_bits, c_xor

def mutate(param_0):
    abi_context = c_abi_context('function_entry:1053001')
    return c_abi_return(abi_context, c_xor(c_mul(param_0, 2, 32), 0x55, 32), 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1053001')
