# Generated by PAL batch_v2_project_global_function_name_registry
# Ghidra function: Global::main
# Entry address: 0x10117d
# This executable projection remains governed by its PAL icecube metadata.

from PALABI import c_abi_call, c_abi_context, c_abi_return
from PALhelpers import c_add, c_and, c_ashr, c_bits, c_eq, c_ne, c_return_bits, c_slt, c_srem, c_sub, c_ult, c_xor, c_zext

def main():
    abi_context = c_abi_context('function_entry:1053053')
    local_20 = 0x10
    local_1c = 0x20
    local_18 = 0
    local_14 = 0
    while True:
        local_20 = c_bits(c_abi_call(abi_context, 'mutate', (c_add(local_14, local_20, 32),), plan_id='call_site:1053093:(ram, 0x1011af, 47, 5):5'), 32)
        local_10 = 0
        while not (c_slt(9, local_10, 32) or c_slt(local_1c, 1, 32)):
            v_1736 = c_bits(c_abi_call(abi_context, 'feedback', (local_20, local_10), plan_id='call_site:1053123:(ram, 0x1011cd, 237, 0):0'), 32)
            if not c_eq(c_srem(c_xor(v_1736, local_1c, 32), 3, 32), 0, 32):
                v_1176 = c_and(v_1736, 7, 32)
                local_18 = v_1736
                if c_eq(c_and(v_1736, 7, 32), 3, 32):
                    local_18 = v_1736
                    while not c_slt(local_18, 1, 32):
                        local_18 = c_bits(c_abi_call(abi_context, 'mutate', (c_ashr(local_18, 1, 32),), plan_id='call_site:1053237:(ram, 0x10123c, 618, 1):1'), 32)
                        if not c_ne(local_18, 15, 32):
                            break
                else:
                    if not c_ult(c_and(v_1736, 7, 32), 4, 32):
                        local_20 = c_sub(local_20, local_1c, 32)
                        local_18 = v_1736
                    else:
                        if not c_ult(c_and(v_1736, 7, 32), 2, 32):
                            if not c_ne(c_and(v_1736, 7, 32), 2, 32):
                                local_1c = c_add(local_1c, 5, 32)
                                local_18 = v_1736
                            else:
                                local_20 = c_sub(local_20, local_1c, 32)
                                local_18 = v_1736
                        else:
                            local_20 = c_xor(local_20, 0xaa, 32)
                            local_1c = c_add(local_1c, 5, 32)
                            local_18 = v_1736
                if not c_slt(4294967295, local_20, 32):
                    local_20 = 0
                    break
            else:
                local_1c = c_add(local_1c, 0xfffffffe, 32)
                local_18 = v_1736
                local_10 = c_add(local_10, 1, 32)
                continue
            local_10 = c_add(local_10, 1, 32)
        v_4658 = local_20
        if not c_ne(c_and(local_14, 1, 32), 0, 32):
            pass
        else:
            local_20 = local_1c
            local_1c = v_4658
        local_14 = c_add(local_14, 1, 32)
        if not c_slt(4, local_14, 32):
            pass
        else:
            if not c_slt(99, local_20, 32):
                pass
            else:
                break
    c_abi_call(abi_context, 'printf', (0x102004, c_zext(local_20, 32, 64), c_zext(local_1c, 32, 64), c_zext(local_18, 32, 64)), plan_id='call_site:1053363:(ram, 0x1012cd, 198, 7):7')
    return c_abi_return(abi_context, c_add(local_1c, local_20, 32), 32, (('register', 'EAX', 32, 'register:0:4'),), plan_id='function_entry:1053053')
