# Generated by PAL batch_v2d_explicit_stdio_overlay_authority
# Ghidra function: Global::main
# Entry address: 0x10117d
# This executable projection remains governed by its PAL icecube metadata.

#======= PAL stack versioning ======
# PALStaticStringPublisher = static_strings_v1_defined_ghidra_data
# PALBatchDecompiler = batch_v2d_explicit_stdio_overlay_authority
# PALHumanizer = humanizer_v2_oncs_varnames_recovery
# PALDecompilerPipeline = unknown
# PALlibrary.PALLifter = unknown
# PALlibrary.FunctionCFG = unknown
# PALSymbolResolver = unknown
# PALRawAudit = unknown
# PALCompute = v23b_abi_thunk_compatibility_return_reconciliation
# PALSemanticGraphBuilder = unknown
# PALSGLdecomp = unknown
# PALPHIfolder = v23_abi_f_entry_state_convergence_custody
# PALemitter = v46p_immutable_abi_context_continuity
# PALCodeDocument = im_d_v1_projection_alias_edit_sidecars
#====================================

from PALABI import c_abi_call, c_abi_context
from PALhelpers import c_add, c_and, c_ashr, c_bits, c_eq, c_ne, c_return_bits, c_slt, c_srem, c_sub, c_ult, c_xor, c_zext

def main():
    abi_context = c_abi_context('function_entry:1053053')
    local_2c = 0x10
    local_28 = 0
    local_24 = 0
    local_20 = 0
    while True:
        local_2c = c_bits(c_abi_call(abi_context, 'mutate', (c_add(local_20, local_2c, 32),), plan_id='call_site:1053107:(ram, 0x1011bd, 53, 5):5'), 32)
        local_1c = 0
        while not (c_slt(9, local_1c, 32) or c_slt(local_28, 1, 32)):
            v_4453 = c_bits(c_abi_call(abi_context, 'feedback', (local_2c, local_1c), plan_id='call_site:1053137:(ram, 0x1011db, 268, 0):0'), 32)
            if not c_eq(c_srem(c_xor(v_4453, local_28, 32), 3, 32), 0, 32):
                v_1257 = c_and(v_4453, 7, 32)
                if c_eq(c_and(v_4453, 7, 32), 3, 32):
                    local_18 = 0
                    local_24 = v_4453
                    while not (c_slt(local_24, 1, 32) or c_slt(15, local_18, 32)):
                        local_24 = c_bits(c_abi_call(abi_context, 'mutate', (c_ashr(local_24, 1, 32),), plan_id='call_site:1053260:(ram, 0x101253, 671, 2):2'), 32)
                        local_18 = c_add(local_18, 1, 32)
                        if not c_ne(local_24, 15, 32):
                            break
                else:
                    if not c_ult(c_and(v_4453, 7, 32), 4, 32):
                        local_2c = c_sub(local_2c, local_28, 32)
                    else:
                        if not c_ult(c_and(v_4453, 7, 32), 2, 32):
                            if not c_ne(c_and(v_4453, 7, 32), 2, 32):
                                local_28 = c_add(local_28, 5, 32)
                                local_24 = v_4453
                            else:
                                local_2c = c_sub(local_2c, local_28, 32)
                        else:
                            local_2c = c_xor(local_2c, 0xaa, 32)
                            local_28 = c_add(local_28, 5, 32)
                            local_24 = v_4453
                if not c_slt(4294967295, local_2c, 32):
                    local_2c = 0
                    break
            else:
                local_28 = c_sub(local_28, 2, 32)
                local_24 = v_4453
                local_1c = c_add(local_1c, 1, 32)
                continue
            local_1c = c_add(local_1c, 1, 32)
        v_5265 = local_2c
        if not c_ne(c_and(local_20, 1, 32), 0, 32):
            pass
        else:
            local_2c = local_28
            local_28 = v_5265
        local_20 = c_add(local_20, 1, 32)
        if not c_slt(4, local_20, 32):
            pass
        else:
            if not c_slt(99, local_2c, 32):
                break
        if c_slt(11, local_20, 32):
            pass
        else:
            break
    c_abi_call(abi_context, 'printf', (0x102008, c_zext(local_20, 32, 64), c_zext(local_2c, 32, 64), c_zext(local_28, 32, 64), c_zext(local_24, 32, 64)), plan_id='call_site:1053404:(ram, 0x1012fc, 229, 5):5')
    return c_return_bits(c_add(local_28, local_2c, 32), 32)
